### ISSUE TITLE
Support set returning functions (srf)

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#1139]
https://www.postgresql.org/docs/current/functions-srf.html 

https://github.com/singularity-data/risingwave-legacy/pull/2209 we formerly supported `generate_series` in the Java Frontend, as well as implemented a GenerateSeriesExecutor in rust ComputeNode. Now we need to reimplement the frontend part in rust.

```rust
pub enum Relation {
    BaseTable(Box<BoundBaseTable>),
    Subquery(Box<BoundSubquery>),
    Join(Box<BoundJoin>),
    TableFunction(Box<TableFunction>),
}
```

The first todo is adding another relation type: TableFunction in binder. 

```rust
enum TableFunction {
    GenerateSeries(Vec<ExprImpl>),
}
```

In the planner this function should be converted into LogicalTableFunction, which subsequently converts to BatchGenerateSeries in physcial planning phase.

Please note that BatchGenerateSeries is only a temporary construct for table function because for now we only support this table function. Others that pg supports include: 

- generate_subscripts
- unnest(ARRAY)

So eventually they should be encapsulated as a `BatchTableFunction` and its associate compute executor `TableFunctionScanExecutor`.

**Comment by xiangjinwu** [comment]
Tracked by #2443: There is already tumble, hop and generate_series on timestamp
