### ISSUE TITLE
Discussion: Merge `VARCHAR` and `CHAR` into one?

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#1274]
> This depends on wheter we want to provide two types CHAR and VARCHAR like PG (Product interface). They are different in PG when dealing with trailing space issues. Personally I prefer simple megre to one, cuz I guess no people wants to understand the difference of CHAR and VARCHAR before use it.

Agree. This is not a high-priority issue, let's open a discussion for that

_Originally posted by @fuyufjh in https://github.com/singularity-data/risingwave/pull/1270#issuecomment-1078702461_

**Comment by lmatz** [comment]
Seems the decision for `Char` has already been made

Has the decision for `INT8`, `INT16`, `INT32`, `INT64` been made?

**Comment by xiangjinwu** [comment]
* There is no `INT8`, ever.
* Our support of `INT16` is pretty good now. It is not a big simplification from `int16, int32, int64` to `int32, int64`. So there is no plan to spend time on removing `int16`.
