### ISSUE TITLE
Introduce value serialization

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#13]
Currently, we serialize both key and value using memcomparable format, which is meaningless for values.
Cockroach has both key encoding and value encoding, maybe we can refer that format or others.

In https://github.com/singularity-data/risingwave-dev/issues/396, we only fixed the issue for MaterializeExecutor. Therefore, if any executor didn't use value encoding for Decimal, the result will be wrong -- it will lose `000` at the end.

- [ ] TopN
- [ ] AppendOnlyTopN
- [ ] HashAgg
- [ ] HashJoin
- [ ] Find other places...

**Comment by WindowsXp-Beta** [comment]
I'm back aaaagin 🤣
