### ISSUE TITLE
frontend: bind & plan subquery expr

### ISSUE THREAD

**Issue by xxchan** [singularity-data/risingwave#1343]
- [x] https://github.com/singularity-data/risingwave/pull/1308
- [ ] in other clauses
- [ ] https://github.com/singularity-data/risingwave/pull/1497
- a [doc](https://singularity-data.quip.com/lha2AGhoVxnH/Subquery-Expr-Unsupported) about subquery expr that we are not interested to support right now.

**Comment by lmatz** [comment]
was there any reason why `in` is not implemented?

cannot login quip anymore

**Comment by xxchan** [comment]
can you give an example SQL?

**Comment by stdrc** [comment]
> can you give an example SQL?

```sql
create table t0 (
    some_id int
);

create table t1 (
    some_id int
);

create table t2 (
    some_id int
) append only;

create materialized view mv as
select
    some_id,
    some_id in (select some_id from t1) as has_1,
    some_id in (select some_id from t2) as has_2
from t0;
```
