### ISSUE TITLE
frontend: support stream sort / TopN operator

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1459]

**Comment by fuyufjh** [comment]
`order by` actually has been implemented by adding sort key into `pk_columns`

**Comment by skyzh** [comment]
but limit + order by is not implemented 🤣

**Comment by fuyufjh** [comment]
Yes, I'll take this

**Comment by skyzh** [comment]
@xiangjinwu has already given some instructions in https://github.com/singularity-data/risingwave/issues/1419, also @nanderstabel is working on this. Maybe you can first sync progress with him.
