### ISSUE TITLE
Distinct aggregation in Streaming

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#146]
e.g. `create materialized view mv1 as select count(distinct c1) from t1`

**Comment by fuyufjh** [comment]
There is a common practice in handling distinct aggregation in MPP databases. For example, here is a blog talking about the implementation in Presto:

https://www.qubole.com/blog/presto-optimizes-aggregations-over-distinct-values

----------------

The basic idea is to treat the `distinct` column as another group-by column to dedup, and then, use a secondary aggregation to aggregate.

But how to deal with queries with multiple (distinct) aggregation functions?

Here is a general example, assume the user query is

```sql
select dept,
       count(distinct sal),
       count(distinct gender),
       max(age)
from emp
group by dept
```

First, we expand one row to multiple rows with an `Expand` operator.

```
                           ┌──────────┐        [dept, sal,  NULL,   $e=1, NULL]
[dept, sal, gender] ─────► │  EXPAND  │ ─────► [dept, NULL, gender, $e=2, NULL]
                           └──────────┘        [dept, NULL, NULL,   $e=3, age ]
```

And the full plan is:

```
                     GROUP BY (dept)
      ┌───────────┐  - COUNT(*) FILTER $e=1
      │ Aggregate │  - COUNT(*) FILTER $e=2
      └─────┬─────┘  - MAX(age) FILTER $e=3
            │
            │
  ┌─────────┴──────────┐
  │ Shuffle by Hash(d) │
  └─────────┬──────────┘
            │
            │
      ┌─────┴─────┐  GROUP BY (dept,salary,gender,$e)
      │ Aggregate │  - MAX(age)
      └─────┬─────┘
            │
            │
┌───────────┴───────────────┐  [dept, sal,  NULL,   $e=1, NULL]
│ Shuffle by Hash(d,s,g,$e) │  [dept, NULL, gender, $e=2, NULL]
└───────────┬───────────────┘  [dept, NULL, NULL,   $e=3, age ]
            │
      ┌─────┴─────┐
      │  Expand   │
      └─────┬─────┘
            │
            │
      ┌─────┴─────┐
      │ ..input.. │   [dept, sal, gender]
      └───────────┘
```

**Comment by xiangjinwu** [comment]
Just to clarify, agg(distinct) is not supported in streaming yet. It just moved to be tracked in #3589
