### ISSUE TITLE
remove async_trait from ExchangeSource

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#1463]
https://github.com/singularity-data/risingwave/blob/main/rust/rpc_client/src/compute_client.rs#L128-L132
```
/// Each ExchangeSource maps to one task, it takes the execution result from task chunk by chunk.
#[async_trait::async_trait]
pub trait ExchangeSource: Send {
    async fn take_data(&mut self) -> Result<Option<DataChunk>>;
}
```
`take_data` gets frequently called and is on the critical path. We may need to remove the overhead of `async_trait`.

Same as what #1132 did.

**Comment by KivenChen** [comment]
Hi @lmatz! May I try to resolve this issue? The intuition behind it seems similar to this tutorial: https://www.skyzh.dev/posts/articles/2022-01-31-gat-async-trait/

**Comment by lmatz** [comment]
> Hi @lmatz! May I try to resolve this issue? The intuition behind it seems similar to this tutorial: https://www.skyzh.dev/posts/articles/2022-01-31-gat-async-trait/

Sure!

**Comment by KivenChen** [comment]
A PR has been created to solve this issue. PTAL #3586
