### ISSUE TITLE
frontend: use two-phase agg

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1612]

**Comment by TennyZhuang** [comment]
> Local simple agg is not used anywhere in the new Rust front end. Also I don’t think we will have 2-phase agg in the future.

Why do you think we will not have 2-phase agg in the future?

**Comment by skyzh** [comment]
I think we will. Let's change the title to 2-phase agg in frontend.

**Comment by skyzh** [comment]
I believe this is being tracked in another issue
