### ISSUE TITLE
binder: support natural join

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#1633]

**Comment by lmatz** [comment]
Is this issue open to be taken?

**Comment by xiangjinwu** [comment]
> Is this issue open to be taken?
> 
> https://github.com/singularity-data/risingwave/blob/main/src/frontend/src/binder/relation/join.rs#L114-L116

It requires some prior refactoring to be fully correct. The current `BindContext` implementation is buggy (#2771 #3352) and seems not easily extensible to keep only one copy of the join columns (#2683)
