### ISSUE TITLE
risedev: support `advertise-addr` for all components

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1692]
**Is your feature request related to a problem? Please describe.**
If we want to deploy or generate config for multiple nodes, we need to specify listen addr = 0.0.0.0, and advertise addr = real ip

**Describe the solution you'd like**
support `advertise-addr` for all components in RiseDev

**Describe alternatives you've considered**
automatically determine addr when deploying?

**Additional context**

**Comment by yezizp2012** [comment]
@zbzbw has added an option `client_address` for frontend and compute node. That's the real ip or host address(in k8s) for component. Is it the same with `advertise-addr` you mentioned here?

**Comment by skyzh** [comment]
Yes, exactly. We should support setting that arg in risedev.
