### ISSUE TITLE
Support system table (`pg_catalog`)

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#1695]
A first attempt: #886 

We need to review and refine it.

**Comment by lmatz** [comment]
Is there agreement reached for implementing system catalogs?

It has many parts that can be implemented independently by interns and community contributors, after the fundamentals are set up. 😄

**Comment by fuyufjh** [comment]
@TennyZhuang had some ideas. We may discuss it tomorrow

**Comment by xiaoyong-z** [comment]
Is there any further discussion about this?

**Comment by lmatz** [comment]
> Is there any further discussion about this?

Temporarily no, will push a bit in the near future.☺️

**Comment by TennyZhuang** [comment]
> Is there any further discussion about this?

@yezizp2012 is working on this

**Comment by yezizp2012** [comment]
duplicate with #2954
