### ISSUE TITLE
metrics(storage): add metrics for block cache

### ISSUE THREAD

**Issue by hzxa21** [singularity-data/risingwave#1717]

**Comment by twocode** [comment]
Currently `sstable_store` has a reference to state store metrics and record staff like #block requests/#block fetched remotely and durations.

**Comment by Little-Wallace** [comment]
But it seems that the block-cache can only record the number of blocks, rather the total memory keep in block cache...

**Comment by MrCroxx** [comment]
> But it seems that the block-cache can only record the number of blocks, rather the total memory keep in block cache...

It's counting on the size by a weighter after #1512

**Comment by Little-Wallace** [comment]
> > But it seems that the block-cache can only record the number of blocks, rather the total memory keep in block cache...
> 
> It's counting on the size by a weigher after #1512

Ok, I made a mistake. But how could get the accurate current memory usage?

**Comment by Little-Wallace** [comment]
And as https://github.com/singularity-data/risingwave/issues/1773#issuecomment-1094980829 mentioned, the block reference in iterator will not be calculate in capacity of Cache if the entry has been evict.

**Comment by MrCroxx** [comment]
> And as [#1773 (comment)](https://github.com/singularity-data/risingwave/issues/1773#issuecomment-1094980829) mentioned, the block reference in iterator will not be calculate in capacity of Cache if the entry has been evict.

Yep. That would be a problem.

**Comment by Little-Wallace** [comment]
I have ported BlockCache from `RocksDB` to my own project https://github.com/rust-lib-project/calibur/blob/table-cache/src/util/cache.rs.  And it will only reduce memory when iterator release the cache-entry,

Maybe I could copy it to risingwave.

**Comment by MrCroxx** [comment]
> Maybe I could copy it to risingwave.

It seems that the implementation doesn't include an async wait map. We need one to prevent multiple requests of the same block from leading to multiple s3 web requests. 🤔 @Little-Wallace

**Comment by Little-Wallace** [comment]
> > Maybe I could copy it to risingwave.
> 
> It seems that the implementation doesn't include an async wait map. We need one to prevent multiple requests on the same block from leading to multiple s3 web requests. 🤔 @Little-Wallace

Good catch. I'm thinking solution for this problem
