### ISSUE TITLE
frontend: unexpected EOF on risedev's wait_tcp

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#1721]
**Describe the bug**
When starting the frontend with risedev, it will establish a TCP connection to check whether the service is ready. This will cause an error log.
```
2022-04-08T20:07:36.809467Z  INFO pgwire::pg_server: Server Listening at 127.0.0.1:4566
2022-04-08T20:07:36.819307Z  INFO pgwire::pg_server: New connection: 127.0.0.1:45652
2022-04-08T20:07:36.819718Z ERROR pgwire::pg_server: error Kind(UnexpectedEof)!
```

**To Reproduce**
Start the frontend with risedev.

**Expected behavior**
Ignore this empty connection.

**Comment by liurenjie1024** [comment]
I think this is ok. Remote client may close connection accidently.

**Comment by BowenXiao1999** [comment]
Revisit this a lot but still can not figure out a good way to detect this empty TCP connection. Maybe change `wait_tcp` to `wait_psql`?. Not sure whether @skyzh has better idea?

**Comment by skyzh** [comment]
I don't think it's necessary to handle this case, and I don't even think this is an error. For unexpected eof, we can simply clean up session info and stop the connection, without printing to log.

**Comment by BugenZhao** [comment]
> I don't think it's necessary to handle this case, and I don't even think this is an error. For unexpected eof, we can simply clean up session info and stop the connection, without printing to log.

Sounds OK. 🤣

**Comment by BowenXiao1999** [comment]
I'll fix this.
