### ISSUE TITLE
bug: starting query execution failed: RecvError(())

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1723]
**Describe the bug**
```
failed to run `e2e_test/v2/batch_distributed/tpch.slt`

Caused by:
    test error at e2e_test/v2/batch_distributed/../../batch/tpch/q5.slt.part:1: query failed: db error: ERROR: internal error: Starting query execution failed: RecvError(())
```

**To Reproduce**
https://github.com/singularity-data/risingwave/runs/5885274933?check_suite_focus=true

**Expected behavior**
Successfully run

**Additional context**

**Comment by skyzh** [comment]
The issue is reproduced on main branch:
https://github.com/singularity-data/risingwave/runs/5887994149?check_suite_focus=true

**Comment by liurenjie1024** [comment]
It's really weird and difficult to reproduce.

**Comment by skyzh** [comment]
reproduced at https://github.com/singularity-data/risingwave/runs/5967180078?check_suite_focus=true

**Comment by skyzh** [comment]
reproduced at https://github.com/singularity-data/risingwave/runs/5968840303?check_suite_focus=true

**Comment by skyzh** [comment]
reproduced at https://github.com/singularity-data/risingwave/runs/5971168845?check_suite_focus=true

**Comment by skyzh** [comment]
one observation: better to be observed in release mode

**Comment by liurenjie1024** [comment]
tomorrow for sure

**Comment by skyzh** [comment]
https://github.com/singularity-data/risingwave/runs/5983459865?check_suite_focus=true 🤪
