### ISSUE TITLE
Forks can't load github secrets, all CI will fail.

### ISSUE THREAD

**Issue by Xuanwo** [singularity-data/risingwave#1727]
Oooops, forks can't load github secrets. So all CI will fail.

@skyzh How about skipping ci for forks?

_Originally posted by @Xuanwo in https://github.com/singularity-data/risingwave/issues/1726#issuecomment-1093024555_

**Comment by skyzh** [comment]
Sorry for the bad experience. We will have someone to look into this next week on workdays :) For small PRs, we can actually skip CI, or let maintainers help check-in.

**Comment by skyzh** [comment]
Or we can use bors bot to do the job. bors will get commits onto the `staging` branch of this repo, which could easily bypass the issue. Anyway, we will need more time to look into this.

**Comment by skyzh** [comment]
We've got a temporary workaround for this issue in https://github.com/singularity-data/risingwave/pull/1748, relying on maintainers to manually check-in contributors' PR. Will have better solution in the future, but I think it's enough for now.
