### ISSUE TITLE
RFC: Add grouping to labels.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#1753]
To better classify our issues, we should add grouping to our labels. Currently, I would suggest add at least two kinds of grouping:

1. *type*. Used to identify type of issue, such as bug, feature, regression, etc.
2. *component*. Used to identify ares of issue involved, such as parser, optimizer, batch, streaming, storage, meta, etc.

**Comment by BowenXiao1999** [comment]
LGTM
