### ISSUE TITLE
risedev: set meta recovery mode

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1761]
ref https://github.com/singularity-data/risingwave/pull/1754/

Developers on their local machine would be confused if recovery is disabled by default on CI, but enabled by default locally.

**Comment by skyzh** [comment]
Also we can consider deprecating `RW_CI` env variable little by little. 🤣

**Comment by yezizp2012** [comment]
Disable recovery in CI is just to not mislead the troubleshooting when CI fails and to reduce logs when start/stop components in e2e tests. Except for in CI, recovery enabled should be by default. I agree to make recovery mode configurable with `set` command as well as deprecating `RW_CI` env variable. Let's change it step by step.  🤣
