### ISSUE TITLE
Remove single node batch query

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#1764]
For example, `QueryManager#schedule_single()`  or `RW_DIST_QUERY=1` etc...

Do you think it's ok to do this now? cc @liurenjie1024

**Comment by liurenjie1024** [comment]
Let's postpone this since we need to review design of local execution mode.

**Comment by fuyufjh** [comment]
+1. Please remove single node mode

@liurenjie1024 Local execution mode still needs Exchange node. It's a different topic.

**Comment by liurenjie1024** [comment]
Yes, I'm working on this.
