### ISSUE TITLE
bug(stream): incorrect `Row` equal comparison in case null value exist.

### ISSUE THREAD

**Issue by yuhao-su** [singularity-data/risingwave#1772]
Currently, the equal comparison for `Row` is auto derived. However, since we are using `None` to represent the null value, an equal comparison between two identical rows with null values will produce `True`. Here null value (_unknow_) should be treated as false.
```rust
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]
pub struct Row(pub Vec<Datum>);

pub type Datum = Option<ScalarImpl>;
```

cc. @TennyZhuang

**Comment by skyzh** [comment]
should implement your own eq function if you want to do this, never change the eq impl of Row. Otherwise there might be problems with `Hash`.

**Comment by skyzh** [comment]
In a nutshell, SQL's eq should be different from our internal Eq.

**Comment by skyzh** [comment]
Nope. I'm talking about a general HashMap object. For example,

x: HashMap<Row, Row>

Now we have x.insert(empty_row), but we cannot call x.get(empty_row) to get a record, and even call x.remove(empty_row) to delete a record. That's not acceptable for a hashmap object.

**Comment by yuhao-su** [comment]
> Nope. I'm talking about a general HashMap object. For example,
> 
> x: HashMap<Row, Row>
> 
> Now we have x.insert(empty_row), but we cannot call x.get(empty_row) to get a record, and even call x.remove(empty_row) to delete a record. That's not acceptable for a hashmap object.

Got it. In this case I will not change the impl for `Row`. Instead I will use `trait HashKey` as the key in the hash map. i.e. `HashMap<SerializedKey, Row>` or `HashMap<FixedKey, Row>`.
