### ISSUE TITLE
BlockCache: support for more precise memory control and observation

### ISSUE THREAD

**Issue by Little-Wallace** [singularity-data/risingwave#1773]
## Problem Description
We use `moka::future::Cache` to store block cache of hummock. But it can only set capacity for the number of items. It means that we don't have precise control over memory usage, and of course, we also do not know the precise memory usage. For a long term design, we may need to control and observe the memory usage of every module, and block-cache may be one of the largest memory-usage in all modules. 

## Solution
I suggest port block-cache like `RocksDB` to risingwave to replace `moka::future::Cache` so that we can exactly know memory in any time.

Similar to https://github.com/singularity-data/risingwave/issues/1717

**Comment by skyzh** [comment]
moka supports byte or credit-based LRU control. The most significant problem is that, moka doesn't prevent users to hold a reference to the value. For example, users can hold `Arc<Block>`, moka evicts it, but the memory is not freed.

**Comment by skyzh** [comment]
A even bigger problem is that most of our system needs a re-design. Either iterators need to hold a reference, or the new block cache will need to take reference count to `Arc` into account.

**Comment by skyzh** [comment]
But if we only need to observe the memory usage, I think the implementation can be simple -- when creating `Block` object, +1 for block_count. When dropping `Block` object, -1 for block_count metrics. But for control usage, it's harder.

**Comment by Little-Wallace** [comment]
close by https://github.com/singularity-data/risingwave/pull/1994.
But we need more metrics not only for block-cache, but also for other read statistic.
