### ISSUE TITLE
bench: hummock service benchmark

### ISSUE THREAD

**Issue by hzxa21** [singularity-data/risingwave#1790]
We have basic funtionalities implemented in hummock service (backed by etcd) but we haven't done any quantitative analysis on it. The goal here is to figure out performance and limitations on hummock service via metadata benchmark. 

Currently [hummock service](https://github.com/singularity-data/risingwave/blob/main/src/meta/src/rpc/service/hummock_service.rs) provides the following interfaces:
- Checkpoint interfaces: [get_new_table_id](https://github.com/singularity-data/risingwave/blob/6b68bf1df74969da7b6fa24e61ab23698e82549b/src/meta/src/rpc/service/hummock_service.rs#L187), [add_tables](https://github.com/singularity-data/risingwave/blob/6b68bf1df74969da7b6fa24e61ab23698e82549b/src/meta/src/rpc/service/hummock_service.rs#L91), [commit_epoch](https://github.com/singularity-data/risingwave/blob/6b68bf1df74969da7b6fa24e61ab23698e82549b/src/meta/src/rpc/service/hummock_service.rs#L163), [abort_epoch](https://github.com/singularity-data/risingwave/blob/6b68bf1df74969da7b6fa24e61ab23698e82549b/src/meta/src/rpc/service/hummock_service.rs#L175)

      Current usage:
      1. Checkpoint on epoch1 is initiated
      2. Compute Nodes (CNs) request table_id from hummock service, upload SSTs to S3 and notify hummock service:
          - CN1: get_new_table_id -> .. (write to S3) .. -> add_tables
          - CN2: get_new_table_id -> .. (write to S3) .. -> add_tables
          - ..
      3. Barrier manager invokes commit_epoch to complete checkpoint or abort_epoch to rollback checkpoint

- Reader interfaces: [pin_version](https://github.com/singularity-data/risingwave/blob/6b68bf1df74969da7b6fa24e61ab23698e82549b/src/meta/src/rpc/service/hummock_service.rs#L58), [unpin_version](https://github.com/singularity-data/risingwave/blob/6b68bf1df74969da7b6fa24e61ab23698e82549b/src/meta/src/rpc/service/hummock_service.rs#L76), [pin_snapshot](https://github.com/singularity-data/risingwave/blob/6b68bf1df74969da7b6fa24e61ab23698e82549b/src/meta/src/rpc/service/hummock_service.rs#L130), [unpin_snapshot](https://github.com/singularity-data/risingwave/blob/6b68bf1df74969da7b6fa24e61ab23698e82549b/src/meta/src/rpc/service/hummock_service.rs#L148)
      
      Current usage:
      - Each CN maintains a LocalVersionManager which keeps track of a cached version via a periodically triggered background task:
        pin_version -> track version ref cnt -> unpin_version
         
      - Each frontend is notified when a new checkpoint is completed and matiains a snapshot cache
        pin_snapshot -> track snapshot ref cnt -> unpin_snapshot

- Compact/Vacuum interfaces: [report_compact_task](https://github.com/singularity-data/risingwave/blob/6b68bf1df74969da7b6fa24e61ab23698e82549b/src/meta/src/rpc/service/hummock_service.rs#L109), [report_vacuum_task](https://github.com/singularity-data/risingwave/blob/6b68bf1df74969da7b6fa24e61ab23698e82549b/src/meta/src/rpc/service/hummock_service.rs#L211)

      Current usage:
      1. Compaction/Vacuum taisk is periodically triggered via a background rountine and the task is assigned to a node
      2. When the node finishes the compaction/vacuum task, it invokes report_compact_task/report_vacuum_task to report to hummock service

The focuses of this benchmark are:
1. For each interface, figure out how QPS scales with increasing number of nodes interacting with hummock service.
2. For each interface, figure out how QPS scales with increasing number of metadata (i.e. SSTs) in hummock service
3. For each interafce, figure out its bottleneck.

**Comment by hzxa21** [comment]
In order to identify hummock service bottleneck, we can run the benchmark using different meta store ([EtcdMetaStore](https://github.com/singularity-data/risingwave/blob/main/src/meta/src/storage/etcd_meta_store.rs), v.s. [MemMetaStore](https://github.com/singularity-data/risingwave/blob/main/src/meta/src/storage/mem_meta_store.rs)).

**Comment by zwang28** [comment]
NotificationManager is now sending notification to CNs synchronously in `commit_epoch` which compromises performance. It's expected to be refactored soon.
https://github.com/singularity-data/risingwave/pull/1693#discussion_r852659258
