### ISSUE TITLE
array: implement value_at_unchecked

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#1814]
We introduce an index based chunk iterator in #1813, it's critical path and some bound checks are unnecessary.

**Comment by skyzh** [comment]
We can also implement trusted length iterator to make fewer branches.

**Comment by ichn-hu** [comment]
maybe I can give it a try :-)

**Comment by TennyZhuang** [comment]
Any updates?

**Comment by ichn-hu** [comment]
> Any updates?

sorry for the delay, will be working on it this weekend
