### ISSUE TITLE
array: impl TrustedLen for *ArrayIter

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#1819]
https://doc.rust-lang.org/stable/std/iter/trait.TrustedLen.html

_Originally posted by @skyzh in https://github.com/singularity-data/risingwave/issues/1814#issuecomment-1097822435_

**Comment by LittleFall** [comment]
Hi @TennyZhuang, I want to do this issue, could you assign it to me?

**Comment by TennyZhuang** [comment]
Any updates?

**Comment by LittleFall** [comment]
> Any updates?

sorry for the late, working in progress
