### ISSUE TITLE
streaming: use `StreamChunk::rows` to iterate on rows

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#1839]
We're also splitting stream chunks into ops and data chunks and using `DataChunk::rows` everywhere. Maybe we should refactor them as well.

_Originally posted by @BugenZhao in https://github.com/singularity-data/risingwave/pull/1813#pullrequestreview-940627675_

**Comment by lmatz** [comment]
This has been implemented, right?
