### ISSUE TITLE
Frontend doesn't handle left semi join correctly.

### ISSUE THREAD

**Issue by likg227** [singularity-data/risingwave#1849]
**Describe the bug**
When left semi join has predicates reference the column of right child, it will panic.

**Additional context**
This bug is related to these three functions: out_column_num, o2l_col_mapping_inner, o2r_col_mapping_inner.

**Comment by noneback** [comment]
Assign it to me plz. I want to give it a shot although I have no experience in DB front-end before.

**Comment by likg227** [comment]
[code link](https://github.com/singularity-data/risingwave/blob/ecbd5a559338e7e8ab7b764f9587315e69f579b1/src/frontend/src/optimizer/plan_node/logical_join.rs#L284)
```
let mut visitor = CollectInputRef::new(required_cols.clone());
self.on.visit_expr(&mut visitor);
let left_right_required_cols = visitor.collect();
```
The` required_cols `only contains the columns of left child of left semi join, so when `on` contains condition references conlumns of right child of left semi join, it will panic.

**Comment by jon-chuang** [comment]
Another issue is `FixedBitSet`’s capacity is not calibrated for insertion due to the on Condition visitation.
