### ISSUE TITLE
frontend: NLJ selected when hash join could be used

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1861]
**Describe the bug**

Sometimes, the optimizer could have selected hash join.

**To Reproduce**
```
create table t1(v1 int not null);
create table t2(v1 int not null);
create materialized view mv2 as select * from t1, t2 where t1.v1 = t1.v1;
```

will panic because NLJ is not implemented for stream.

**Expected behavior**
Build plan using hash join.

**Additional context**

**Comment by BowenXiao1999** [comment]
This is strange. It should be solved by Optimizer.

**Comment by xiangjinwu** [comment]
Is it supposed to be **t2**`.v1`? NLJ is required for `where t1.v1 = t1.v1`.

**Comment by skyzh** [comment]
Oh, that's true! Sorry for the typo.

**Comment by skyzh** [comment]
Verified to work if `t1.v1 == t2.v1`.
