### ISSUE TITLE
frontend: Support Join Reorder to avoid Cross Join in TPC-H Q2/Q8/Q9

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#1866]
> It does not need nested loop join if we put lineitem at the beginning of from. Join reordering is the better solution here.

As @xiangjinwu mention, our current planner will generate nested loop join in above query. However, tweak the join order and we can get all Hash Join. This is the basic ability of Optimizer so list as issue.

Relates:  
Q2: #1851 
Q8: #1853 
Q9: #1854

**Comment by xiangjinwu** [comment]
@skyzh @likg227 
Q2 should be able to use `p_partkey = ps_partkey` (condition pulled up).
Q4 should be able to use `l_orderkey = o_orderkey` (condition pulled up).
Q17 should be able to use `l_partkey = p_partkey` (condition pulled up).

**Comment by BowenXiao1999** [comment]
> Hi, I'm interested in this issue : ). How do you guys want to implement it? Columbia optimizer or Dphyp algorithm or others? Can I participate in it?

cc @xiangjinwu Any thoughts on this?

**Comment by xiangjinwu** [comment]
We do not have cost estimation on PlanNodes. The minimum requirement of this issue is to consider all tables listed in `from a, b, c` together with filter conditions above (e.g. `a.z=c.z and b.y=c.y`), and reorder them to avoid cross join as much as possible.
cc @st1page

**Comment by XieJiann** [comment]
Maybe we can just use the trivial cost models (like https://github.com/cmu-db/noisepage/blob/master/src/include/optimizer/cost_model/trivial_cost_model.h) right now just for avoiding nest loop join.

**Comment by st1page** [comment]
- we don't have Statistics of tables, and also it's difficult to give statistics for streaming. so we can not implement any join-reorder algorithm based on the cost model. now we just want to consider the eq-condition, or edge on the join graph to avoid cross join.
- now there is no actual "search space" in our optimizer and all rules and other transformation seems just heuristic, so we can not do the join reorder by join commute rule like Calcite or Columbia. 
- propose to implement it:
   1. add a `LogicalMultiJoin` PlanNode, which means inner join of multiple inputs.
   2. implement a `MergeJoinRule` which will try to merge all the adjacent inner `LogicalJoin` nodes to `LogicalMultiJoin` node
   3. implement the `JoinReorderRule` which will transform `LogicalMultiJoin` to `LogicalMultiJoin` with better join order
   4. implement the `SplitMultiJoinRule` which will split the `LogicalMultiJoin` to  `LogicalJoin` nodes

**Comment by liurenjie1024** [comment]
Calcite's join reorder program in fact is a heuristic method, you can take a reference: https://github1s.com/singularity-data/risingwave/blob/HEAD/legacy/planner/src/main/java/com/risingwave/planner/program/JoinReorderProgram.java

**Comment by XieJiann** [comment]
Ok, I get it. I'll try to implement LogicalMultiJoin first

**Comment by xiangjinwu** [comment]
> * we don't have Statistics of tables, and also it's difficult to give statistics for streaming. so we can not implement any join-reorder algorithm based on the cost model. now we just want to consider the eq-condition, or edge on the join graph to avoid cross join.
> * now there is no actual "search space" in our optimizer and all rules and other transformation seems just heuristic, so we can not do the join reorder by join commute rule like Calcite or Columbia.
> * propose to implement it:
>   
>   1. add a `LogicalMultiJoin` PlanNode, which means inner join of multiple inputs.
>   2. implement a `MergeJoinRule` which will try to merge all the adjacent inner `LogicalJoin` nodes to `LogicalMultiJoin` node
>   3. implement the Join reorder in the `to_batch` and `to_stream` of `LogicalMultiJoin`

Agree with most of it. Some extra comments:
* Is this `LogicalMultiJoin` the same (or reusable by) #1907 ? @skyzh 
* We may need to extend the existing FilterJoin rule to this `LogicalMultiJoin`, so that it can absorb the equality from Filter into this join.

**Comment by skyzh** [comment]
Yes, I'd like to re-use the LogicalMultiWayJoin which will be implemented along with join reordering.

**Comment by st1page** [comment]
> Is this LogicalMultiJoin the same (or reusable by) https://github.com/singularity-data/risingwave/issues/1907 ? 

yes I think so.

> We may need to extend the existing FilterJoin rule to this LogicalMultiJoin, so that it can absorb the equality from Filter into this join.

we should push all predicate down passing LogicalJoin(binary join) before merging them to LogicalMultiJoin, so the filter-multijoin rule seems not necessary

**Comment by jon-chuang** [comment]
> implement a MergeJoinRule which will try to merge all the adjacent inner LogicalJoin nodes to LogicalMultiJoin node

To my mind the binder should detect a multijoin and write it as a LogicalMultiJoin immediately. What do you think?

**Comment by st1page** [comment]
> To my mind the binder should detect a multijoin and write it as a LogicalMultiJoin immediately. What do you think?
- some optimize are easier to implement on binary LogicalJoin such as column prune and predicate push down, so we want to do those on binary LogicalJoin instead of LogicalMultiJoin.
-  there might be inner joins generated from subquery after optimizing, and we should merge it to LogicalMultiJoin, so if we must do the merge, merging them together is simpler.

**Comment by st1page** [comment]
> Btw, should the original field ordering (based on join order) be preserved?
Sorry, what is the meaning of the field ordering? do you mean the fields of the query results? I think it should be immutable after binding.

**Comment by jon-chuang** [comment]
> Sorry, what is the meaning of the field ordering? do you mean the fields of the query results in the case like select * from t1,t2,t3? I think it should be immutable after binding.

I meant the column ordering of the LogicalMultiJoin, after we do a join reordering, if the column ordering has changed, shouldn't we do a project to reorder the columns?

**Comment by st1page** [comment]
> I meant the column ordering of the LogicalMultiJoin, after we do a join reordering, if the column ordering has changed, shouldn't we do a project to reorder the columns back to the original ordering?

yes, I think so. because the multi join's parent can not be aware of the change. 
Btw, after #1922 it will be easier for binary logical join. and for multi join I think it should have a field `output_index: vec<usize>` storing output column indexes.
