### ISSUE TITLE
proposal: deprecate `Broadcast` and `Simple` dispatcher

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1874]
For broadcast -- it is only used by chain node, and only useful when chain node has single parallelism. If there are multi-parallelism chain actors, we should use multi-dispatcher to ensure each set of chain fragment gets its desired distribution.

For simple -- I didn't know why it exists. Seems only useful when exchange distribution is single. We can use NoShuffle exchange instead.

**Comment by D2Lark** [comment]
From my simple understanding of dispather, the connection between them should look like this, right?
```
        Dispatcher  -->  MergeNode B Actor Dispatcher 
ActorA  Dispatcher  -->  MergeNode B Actor Dispatcher 
        Dispatcher  -->  MergeNode B Actor Dispatcher 

A Actor Dispatcher -->
A Actor Dispatcher ---> MergeNode B Actor Dispatcher
A Actor Dispatcher -->
```

**Comment by skyzh** [comment]
Actors can have multiple outputs, and downstream actors can have multiple inputs. The illustration looks correct, but doesn't cover all cases.

**Comment by TennyZhuang** [comment]
Not sure.

There are also some other cases need Broadcast, e.g. NLJ with a small stream.
