### ISSUE TITLE
streaming: support mutation of multiple dispatchers

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1901]
Currently, all mutations are only applicable to single-dispatcher actors. We need to redesign the barrier proto to make this work.

**Comment by xxchan** [comment]
drop MV for multiple dispatchers is fixed in #2244

**Comment by skyzh** [comment]
Already supported, but the create MV process can still be optimized. See https://github.com/singularity-data/risingwave/pull/2041 for details.
