### ISSUE TITLE
frontend: support `create index` statements

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1909]
Need more discussion. A trivial idea is:

```
create index join_index on t1 (join_key);
```

will create a materialize view, where we use `join_key + pk` as materialize key. Then lookup executor can directly use this index.

**Comment by TennyZhuang** [comment]
Are the following two SQLs share the same behavior?

```sql
CREATE INDEX idx_1 ON t1(v1);
```

```sql
CREATE MATERIALIZED VIEW idx_1 AS SELECT v1, pk FROM t1 ORDER BY v1;
```

**Comment by skyzh** [comment]
Yes, exactly, except that users don't need to specify pk.
