### ISSUE TITLE
StateStoreIter may need to use async_trait again but there are also alternatives

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#1930]
`StateStoreIter` was refactored to avoid async_trait. And it was good.

The problem occurs if we want to use `StateStoreIter` instead of `keyspace.scan()` in executors such as TopN to get an undetermined number of kv-pairs from the storage.

The reason we may want to use `Iter` is that we don't really know exactly how many kv pairs to be scanned as cell-based storage format does not store `null`.

The compiler requires adding a `Send` bound on the `NextFuture` returned by the function `next`, which is perfectly reasonble.
However, this would cause:
![SCR-20220419-j8x](https://user-images.githubusercontent.com/5791930/163930011-898dbb58-3fdd-4acf-9edb-6b678c1b00c0.png)

I asked on the rust forum https://users.rust-lang.org/t/impl-future-with-without-send-bound-gives-different-compilation-results/74290, and some rust veteran suggests that this is a known issue found in 2021 and it has not been solved.

Some alternatives:
1. Maintain the status quo: we always `over-scan` to get `n` rows as specified by the `top_n_cache`, but of course, it leads to bad performance.  No good.
2. Use `async_trait` again, aka `Pin<Box<dyn XXX>>>`.  Probably also no, not a long-term direction.
3. Use `scan_with_start_key`, and make an alternative iter as the wrapper around it. Buffer scanned kv pairs inside the iter and offer a `next` interface to the executor. This is similar to what we implement `CellBasedTableRowIter`.  But it seems `MonitoredStoreIter` cannot collect its statistics.
4. ......

**Comment by skyzh** [comment]
> MonitoredStoreIter cannot collect its statistics

`MonitoredStoreIter` doesn't seem to collect metrics any more? I remembered that `next` metrics has been removed.

**Comment by skyzh** [comment]
Well, yet another compiler bug 🤪 We may first try removing `MonitoredStoreIter`. If it still not works, let's refactor everything back 😇

**Comment by lmatz** [comment]
> MonitoredStoreIter doesn't seem to collect metrics any more?

Indeed... I thought it has not been implemented.
Maybe we remove `MonitoredStoreIter`? Will anything else be affected and need to be taken care of?  @BugenZhao

**Comment by BugenZhao** [comment]
> > MonitoredStoreIter doesn't seem to collect metrics any more?
> 
> Indeed... I thought it has not been implemented. Maybe we remove `MonitoredStoreIter`? Will anything else be affected and need to be taken care of? @BugenZhao

I'm running into this problem as well when working on #1859. I was to extract the logic of `scan_with_start_key` to another stream and stuck on this issue, so I give up and only remove some redundant code in that PR. 🤣

I'm okay with removing that, however the metrics of iterators cannot be collected any more. We may also ask other ones about this.

**Comment by lmatz** [comment]
After removing `MonitoredStoreIter` and using `iter` in `TopNState`, it seems to still trigger a compiler bug. 
![SCR-20220419-klv](https://user-images.githubusercontent.com/5791930/163943143-ec1c56a5-43cc-4cd0-80d1-bb96c6d5c8e4.png)
. 😢 
`Self:'a` and `AssociateType<'a>: XXX + 'a` haven been added to everywhere.

**Comment by skyzh** [comment]
Well, let's refactor back to the old school's way 🤣

One alternative: return IteratorImplEnum instead of concrete state iter type.

**Comment by BugenZhao** [comment]
The main reason for this issue might be related to the lifetime of the iterator. Considering that we're using `Arc` in the iterator of shared buffer, we may first remove the lifetime on these iterator types.
