### ISSUE TITLE
Use futures-async-stream to refactor  HashJoinExecutor.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#1947]

**Comment by D2Lark** [comment]
There are still some unresolved issues, such as Calling child.execute() twice at the same time shows the problem of ownership

>    --> src/batch/src/executor2/join/hash_join.rs:174:17
>     |
> 170 |         let mut right_child_stream = self.right_child.execute();
>     |                                                       --------- `self.right_child` partially moved due to this method call
> ...
> 174 |                 self.build(build_table, right_child_stream).await?
>     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ value borrowed here after partial move
>     |
> note: this function takes ownership of the receiver `self`, which moves `self.right_child`
>    --> src/batch/src/executor2/mod.rs:67:16
>     |
> 67  |     fn execute(self: Box<Self>) -> BoxedDataChunkStream;
>     |                ^^^^
>     = note: partial move occurs because `self.right_child` has type `std::boxed::Box<dyn executor2::Executor2>`, which does not implement the `Copy` trait
> 
> error[E0382]: use of moved value: `left_child_stream`
