### ISSUE TITLE
streaming: improve through-put of ingesting data via `insert`

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#1954]
**Is your feature request related to a problem? Please describe.**

The `INSERT` statement is useful for data ingestion from user's customized data pipeline, so the performance matters.

**Describe the solution you'd like**

We may do some benchmarking and profiling first to see where could be improved.

**Comment by skyzh** [comment]
FYI, in release mode

<img width="653" alt="image" src="https://user-images.githubusercontent.com/4198311/163978639-2ba1338d-ea94-49ea-9f7b-ce273799d412.png">

**Comment by fuyufjh** [comment]
Around 15,000 row/sec in single connection.

**Comment by fuyufjh** [comment]
This issue is just a reminder that we didn't do any testing/benchmarking on this case yet. May not be very critical now.
