### ISSUE TITLE
panic: there is no limit stream operator

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#1982]
Q3 fails with:

thread 'tokio-runtime-worker' panicked at 'there is no limit stream operator', frontend/src/optimizer/plan_node/logical_limit.rs:107:9

_Originally posted by @skyzh in https://github.com/singularity-data/risingwave/issues/1457#issuecomment-1084155443_

**Comment by lmatz** [comment]
Do we intend to have a `StreamLimit` operator? If yes, we may list this as a good-first issue.

**Comment by skyzh** [comment]
I don't think we will have StreamLimit operator. We cannot know the arriving order of data in storage. The only way to implement limit is when there is an order.

**Comment by fuyufjh** [comment]
Yes. This issue should be closed by https://github.com/singularity-data/risingwave/pull/2038
