### ISSUE TITLE
storage: refine `scan` interface of `Keyspace`

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#1989]
The purpose of `Keyspace` is to only expose the records with the specific prefix, so we hardly use the current `scan` interface, which does not strip the prefix.

We may remove the public interface of `scan` and directly expose `scan_strip_prefix` as `scan` to users, similar to what we did in #1969. Ditto for `scan_with_start_key`.

https://github.com/singularity-data/risingwave/blob/8ca6a1efbe866407f8f0a4719d6e4d8d59552bba/src/storage/src/keyspace.rs#L120-L162

**Comment by ClearloveWei** [comment]
I'd like to take this issue. Could you please assign it to me?
