### ISSUE TITLE
source: BrokerTransportFailure on CI

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1996]
```
Meta data fetch error: BrokerTransportFailure (Local: Broker transport failure)
```

https://github.com/singularity-data/risingwave/runs/6093864195?check_suite_focus=true

**Comment by neverchanje** [comment]
I also occasionally met this problem, sometimes the local Kafka even failed to connect with my kafcat/Kafkacat.

**Comment by skyzh** [comment]
https://github.com/singularity-data/risingwave/pull/1997 maybe fixed by checking Kafka health using API instead of TCP port.

**Comment by skyzh** [comment]
Also in no-persist-data mode, we should delete Zookeeper / Kafka directory. Otherwise Kafka will complain broker id doesn't match node id.
