### ISSUE TITLE
ci: migrate from uber/prototool to bufbuild/buf

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#2008]
* [uber/prototool](https://github.com/uber/prototool) is archived and suggest to use [bufbuild/buf](https://github.com/bufbuild/buf) in README
* I can not use prototool in M1 Mac via brew. Not try build from source.
Runtime issue:
```shell
prototool format
unsupported value for runtime.GOARCH: arm64
```

**Comment by skyzh** [comment]
We already have buf in CI, but not enforced.

**Comment by BowenXiao1999** [comment]
Okay NVM, I just see a prototool fmt error in CI and can not reproduce local. So post this issue. If it's solved pls closed.

**Comment by BowenXiao1999** [comment]
> We already have buf in CI, but not enforced.

Okay NVM, I just see a prototool fmt error in CI and can not reproduce local. So post this issue. If it's solved pls closed.

**Comment by TennyZhuang** [comment]
claim
