### ISSUE TITLE
improve(states-store): get number of table_ids from fe

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#2032]
After discuss with @st1page, we found a problem in #2028 . And plus some feedback about let fe to provide table ids.

We decide to fix this via:
1. FE provides info (how many table ids allocate for each node) to meta. So there may be a vec table_ref_id in related stateful op.
2. FE provides a `total_table_id_cnt` in root StreamNode. It tells meta the total number of needed table ids in this whole MV. It's like a PlanMeta (Not decide yet).

1 is must needed if we do not want meta to know how many table states need for each op.

Why 2? This is due to Rust async recursive inability. The get of table id is a async op so we can not get id when doing node traverse. So we have to get all table ids outside the recurse. If we do not have 2, meta needs to traverse stream node again and sum up total needed table ids number. This may makes the fragmenter code more complicated (now it is).

Therefore, I propose 1 and 2. Not post to discussion cuz it's too detail.  

cc @skyzh @st1page @BugenZhao @fuyufjh

**Comment by skyzh** [comment]
I don't think FE needs providing anything. In fragmenter, we can allocate table ids.

**Comment by fuyufjh** [comment]
> So there may be a repeated table_ref_id in related stateful op.

What does this mean?

**Comment by skyzh** [comment]
The fragmenter will work like...

1. visit all plan nodes, and calculate and allocate so-called `LocalTableId`.
2. allocate global table ids, revisit all plan nodes, and assign real table ids.

**Comment by skyzh** [comment]
The process should be similar to allocating actor id and fragment id.

**Comment by BowenXiao1999** [comment]
> > So there may be a repeated table_ref_id in related stateful op.
> 
> What does this mean?

For example, HashJoin may have a Vec with capacity 2. So meta knows to allocate 2 ids for this op.

**Comment by fuyufjh** [comment]
> For example, HashJoin may have a Vec with capacity 2. So meta knows to allocate 2 ids for this op.

Well. I think it's okay to let the meta decide how many table-ids to allocate according to the type of PlanNode. Maybe just around 10 LOC, I guess

**Comment by BugenZhao** [comment]
> 1. visit all plan nodes, and calculate and allocate so-called `LocalTableId`.

So we should still make it a general field for number of requested table ids in the node proto?

**Comment by BowenXiao1999** [comment]
> The fragmenter will work like...
> 
> 1. visit all plan nodes, and calculate and allocate so-called `LocalTableId`.
> 2. allocate global table ids, revisit all plan nodes, and assign real table ids.

Yes this is a way. This will post one more StreamNode traverse in fragmenter. The problem is how much meta should understand the op. Collecting some suggestions that fe do this.

**Comment by fuyufjh** [comment]
... And compared with `repeated int table_ref_id`, I think multiple fields e.g. `int left_hash_table_id` `int right_hash_table_id` may be better?

**Comment by skyzh** [comment]
> Yes this is a way. This will post one more StreamNode traverse in fragmenter. The problem is how much meta should understand the op. Collecting some suggestions that fe do this.

The fragmenter might be moved back to frontend in the future, so I think it's okay to let meta understand these plan nodes.

**Comment by BowenXiao1999** [comment]
> ... And compared with `repeated int table_ref_id`, I think multiple fields e.g. `int left_hash_table_id` and `int right_hash_table_id` may be better?

Yes that's the way now. I think let fragmenter understand is ok. ignore the first proposal..

**Comment by BowenXiao1999** [comment]
> > Yes this is a way. This will post one more StreamNode traverse in fragmenter. The problem is how much meta should understand the op. Collecting some suggestions that fe do this.
> 
> The fragmenter might be moved back to frontend in the future, so I think it's okay to let meta understand these plan nodes.

Agreed. Then one more run of StreamNode traverse in fragmenter is needed (to assign table id). I'm OK with that.

**Comment by BowenXiao1999** [comment]
To conclude some takeaways:
1. fragmenter can understand the table ids stuff (how many table ids need for each op) cuz it may moved to fe.
2. table ids should be placed at internal plan like HashJoin, and better not use vector
3. fragmenter now needs to add another run of StreamNode traverse. Compute total needed table ids (1st) + assign table id to each node (2nd)
