### ISSUE TITLE
fronted: Supports the Redpanda connector

### ISSUE THREAD

**Issue by pangzhenzhou** [singularity-data/risingwave#2033]
Because Redpanda is compatible with the Kafka protocol, RisingWave does not need to do additional development (it can reuse the Kafka source reader), but in order to be more user-friendly and extensible in the future.

Suggest the RisingWave front-end supports the Redpanda connector, for example:

`create [materialized] source redpanda_source (v1 int, v2 varchar ) with ( 'connector'='redpanda', 'redpanda.topic'='t2', 'redpanda.brokers'='127.0.0.1:9092', 'redpanda.scan.startup.mode'='latest' ) row format json;`

**Comment by neverchanje** [comment]
If redpanda is 100% compatible with kafka, do we need to redefine another bunch of configurations for redpanda?

**Comment by neverchanje** [comment]
I've just tested redpanda via rpk that on a 3-node cluster the command around kafka also perfectly worked on redpanda.

Start a 3-node redpanda cluster:
```
rpk container start -n 3
Starting cluster
Waiting for the cluster to be ready...
  NODE ID  ADDRESS          
  0        127.0.0.1:58501  
  1        127.0.0.1:58508  
  2        127.0.0.1:58507  

Cluster started! You may use rpk to interact with it. E.g:

rpk cluster info --brokers 127.0.0.1:58501,127.0.0.1:58508,127.0.0.1:58507
```

Load the data:
```
kcat -P -l -b 127.0.0.1:58501,127.0.0.1:58508,127.0.0.1:58507 -t kafka_1_partition_topic.1 ./scripts/source/test_data/kafka_1_partition_topic.1
```

Read from source:
```
dev=> create materialized source s (v1 int, v2 varchar) with ( 'connector' = 'kafka', 'kafka.topic' = 'kafka_1_partition_topic.1', 'kafka.brokers' = '127.0.0.1:58501,127.0.0.1:58508,127.0.0.1:58507', 'kafka.scan.startup.mode'='earliest' ) row format json;
CREATE_SOURCE
dev=> select * from s;
 v1 |  v2  
----+------
  1 | 1
  2 | 22
  3 | 333
  4 | 4444
(4 rows)
```

**Comment by pangzhenzhou** [comment]
> I've just tested redpanda via rpk that on a 3-node cluster the command around kafka also perfectly worked on redpanda.
> 
> Start a 3-node redpanda cluster:
> 
> ```
> rpk container start -n 3
> Starting cluster
> Waiting for the cluster to be ready...
>   NODE ID  ADDRESS          
>   0        127.0.0.1:58501  
>   1        127.0.0.1:58508  
>   2        127.0.0.1:58507  
> 
> Cluster started! You may use rpk to interact with it. E.g:
> 
> rpk cluster info --brokers 127.0.0.1:58501,127.0.0.1:58508,127.0.0.1:58507
> ```
> 
> Load the data:
> 
> ```
> kcat -P -l -b 127.0.0.1:58501,127.0.0.1:58508,127.0.0.1:58507 -t kafka_1_partition_topic.1 ./scripts/source/test_data/kafka_1_partition_topic.1
> ```
> 
> Read from source:
> 
> ```
> dev=> create materialized source s (v1 int, v2 varchar) with ( 'connector' = 'kafka', 'kafka.topic' = 'kafka_1_partition_topic.1', 'kafka.brokers' = '127.0.0.1:58501,127.0.0.1:58508,127.0.0.1:58507', 'kafka.scan.startup.mode'='earliest' ) row format json;
> CREATE_SOURCE
> dev=> select * from s;
>  v1 |  v2  
> ----+------
>   1 | 1
>   2 | 22
>   3 | 333
>   4 | 4444
> (4 rows)
> ```
> 
> Looks like we have no work to do on redpanda!!!

Users may be more confused when defining the source schema（with option）, so just the front-end work and the configuration of Kafka are the same.

**Comment by neverchanje** [comment]
I don't think they will be confused. As they claim redpanda is kafka-compatible, they want people to use it as if it is completely a kafka rather than anything else. Just like we want users to connect RisingWave as if it is Postgres.

**Comment by pangzhenzhou** [comment]
> I don't think they will be confused. As they claim redpanda is kafka-compatible, they want people to use it as if it is completely a kafka rather than anything else. Just like we want users to connect RisingWave as if it is Postgres.

OK， so close this issue.

**Comment by neverchanje** [comment]
No worry, we can reopen this issue in case there is any incompatibility issue.
