### ISSUE TITLE
frontend: Explain should output distributed query plan.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#2037]
**Describe the bug**

Currently distributed query is enabled by default, and explain should generate distributed plan.

**To Reproduce**

explain any query.

**Expected behavior**

Generated distributed query plan.

**Comment by skyzh** [comment]
I think the explain handler needs some revisit, I hope it can also explain `create index`, `create table`, etc...

**Comment by liurenjie1024** [comment]
> I think the explain handler needs some revisit, I hope it can also explain `create index`, `create table`, etc...

I think you mean `show create table/index`?

**Comment by skyzh** [comment]
Nope, I mean explain a create table statement. We should be able to print the materialize view plan of create table / create index?

**Comment by liurenjie1024** [comment]
I got what you mean, `create table` and `create index` are essentially equals to `create materialized view` in our system, so we should print their plan. Sounds reasonable.
