### ISSUE TITLE
Empty query result for TPC-H Q10

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2071]
**Describe the bug**

https://github.com/singularity-data/risingwave/runs/6143952340?check_suite_focus=true

The result set is empty.

**To Reproduce**
On CI

**Expected behavior**
Correct TPC-H Q10 query result

**Additional context**
Happens after https://github.com/singularity-data/risingwave/pull/2043 gets merged, not sure if this PR is causing the issue.

**Comment by wenym1** [comment]
#2043 only modifies the newly implemented lru cache, and it's not used yet. So this PR may not be the cause of the issue.

**Comment by skyzh** [comment]
Well, let's investigate it further later...

**Comment by skyzh** [comment]
Guess that's because we missed a `flush` in TPC-H slts. Should be fixed by https://github.com/singularity-data/risingwave/pull/2083
