### ISSUE TITLE
meta: store distribution_keys in table catalog

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2098]
* So that we can eliminate unnecessary exchanges between upstream and downstream nodes.
* When matching index, we must also follow distribution keys.

cc @zbzbw @yezizp2012 is there any plans to implement this? I think something similar has been mentioned in https://github.com/singularity-data/risingwave/pull/2040.

**Comment by zbzbw** [comment]
I will work on this👀

**Comment by yezizp2012** [comment]
@zbzbw will work on this this week.
