### ISSUE TITLE
ci: Improve our ci to to be more friendly to community contributor.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#2100]
**Is your feature request related to a problem? Please describe.**

Currently when a community contributor(contributor outside singularity data) opens pull request, the ci can't run. This is because our ci workflow needs to start an ec2 instance/runner, which requires an aws token. This aws token is stored in github as secrects to avoid leaking, and pull request issued by community user can't read this secret. That's why pull request from community user fails.

**Describe the solution you'd like**

Please help to investigate ways to improve this so that community user's PR can run our ci. Any solution can be investigated, including ci services from cloud providers such aws, azure.

**Describe alternatives you've considered**

Using github action provided ci service is rejected because it unstable and slow.

**Additional context**

**Comment by skyzh** [comment]
Also our CI doesn’t scale easily. I’d like to split e2e test into multiple jobs, but it’s hard under current configuration.

**Comment by D2Lark** [comment]
May I add another request? I can't see the documents you share which are hosted on quip. I can't read it without the company email

**Comment by liurenjie1024** [comment]
> May I add another request? I can't see the documents you share which are hosted on quip. I can't read it without the company email

Yes, we are supposed to put it in the doc folder of our repo.

**Comment by skyzh** [comment]
We're now using Buildkite for PRs. We will soon make it the default one.
