### ISSUE TITLE
storage: use binary search to locate SSTs in nonoverlapping levels on reads

### ISSUE THREAD

**Issue by hzxa21** [singularity-data/risingwave#2123]
Currently we use linear seach to locate SSTs for all levels in get/scan. Since SSTs in nonoverlapping levels are supposed to be ordered by key range under the current implementation, it is better to use binary search to locate SSTs instead.

**Comment by pleiadesian** [comment]
I'll work on this issue.

**Comment by pleiadesian** [comment]
Actually, we are already using binary search for SSTs on the non-overlapping levels, which is internally implemented by `partition_point` below. 🤔
https://github.com/singularity-data/risingwave/blob/721e93fa1231a565421dd677a21a78f716c298d1/src/storage/src/hummock/state_store.rs#L242-L250

**Comment by hzxa21** [comment]
> Actually, we are already using binary search for SSTs on the non-overlapping levels, which is internally implemented by `partition_point` below. 🤔
> https://github.com/singularity-data/risingwave/blob/721e93fa1231a565421dd677a21a78f716c298d1/src/storage/src/hummock/state_store.rs#L242-L250

 
We already uses binary search for point lookup but not range scan. We still iterate through all SSTs in non-overlapping level.

**Comment by pleiadesian** [comment]
Range scan retrieves the iterator by calling `prune_ssts`. I think we can optimize `prune_ssts` with faster searching algorithm, which would be better for callers in get/scan.
https://github.com/singularity-data/risingwave/blob/858d8e8151672108537ba6a4594400ddae8fa988/src/storage/src/hummock/utils.rs#L79-L99
