### ISSUE TITLE
frontend: Support `ORDER BY` arbitrary column

### ISSUE THREAD

**Issue by Enter-tainer** [singularity-data/risingwave#2124]
**Describe the bug**

Currently only `ORDER BY` can only apply to output columns. But actually, it should work with arbitrary columns, take the example from PostgreSQL's document. Column `c` is not `SELECT`ed, but we can still `ORDER BY c`.

``` SQL
/* this SHOULD work */
SELECT a, b FROM table1 ORDER BY a + b, c;
```

**To Reproduce**

```SQL
create table t(a int, b int);
dev=> explain select a from t order by b;
ERROR:  Item not found: output column "b"
```

**Expected behavior**
Should produce correct execution plan rather than errors.

**Comment by skyzh** [comment]
> SELECT a, b FROM table1 ORDER BY a + b, c;

This query might need some special care. `c` will become a hidden column in materialized view, but it's now a row_id as we expected before.

**Comment by skyzh** [comment]
I guess @likg227 can first help us support queries like `select a from t order by b;`. After that, we can then work on visibility issues like `b` should not be visible in both MV and batch queries.
