### ISSUE TITLE
refactor: remove calls to `gen_batch_query_plan`

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#2127]
Remove all calls to `gen_batch_query_plan()` and use `gen_dist_batch_query_plan()` instead.

https://github.com/singularity-data/risingwave/blob/3b06cfdd4a4a370e65e1933ab7e03a8053575505/src/frontend/src/optimizer/mod.rs#L158-L181

**Comment by skyzh** [comment]
Fixed this morning? https://github.com/singularity-data/risingwave/issues/2037

**Comment by fuyufjh** [comment]
Indeed. We shall these the comments

https://github.com/singularity-data/risingwave/blob/3b06cfdd4a4a370e65e1933ab7e03a8053575505/src/frontend/src/optimizer/mod.rs#L165-L169
