### ISSUE TITLE
refactor: PK of streaming TopN should be identical to its input's PK

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#2130]
Currently, for streaming TopN operators, we have:

- PK of internal state = sort_key + input.PK
- PK of TopN (i.e. PK of TopN's output) = **sort_key + input.PK**

Expected:

- PK of internal state = sort_key + input.PK
- PK of TopN (i.e. PK of TopN's output) = **input.PK**

See also https://singularity-data.quip.com/dv8VAq8e086h/Design-Primary-Key-of-Materialized-Data

**Comment by fuyufjh** [comment]
After that, changes in #2129 can be reverted

https://github.com/singularity-data/risingwave/pull/2129/files#diff-6437bdcdac1fd3dd16f24493763bfdd9a8ccf52f97d1d9f7e7641364434a935bR38

**Comment by lmatz** [comment]
let me fix this together with #2022
