### ISSUE TITLE
streaming: end-to-end back pressure

### ISSUE THREAD

**Issue by StrikeW** [singularity-data/risingwave#2137]
## Background 
Stream data is passed from upstream Actors to downstream Actors via `ExchangeService`, which is a RPC service. If the data from one Actor is generated too fast, it may lead to congestion of the shared communication link between compute nodes and high latency of checkpoint.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/7338536/165217384-26336724-5cb7-4c1a-922f-f15ecee92117.png">

### Flink approach
Flink has implemented a back pressure mechanism, [credit-based flow control](https://flink.apache.org/2019/06/05/flink-network-stack.html), to solve the similar problems. The key idea is that receivers will announce the availability of recv buffers as *credits* to the sender, 1 credit = 1 buffer. Senders will forward data buffers to the lower network stack only if credit is available. Sender will also announce the number of pending data buffers (*backlog*) to receivers.

The challenge in implementing this solution is mainly that the ExchangeService relies on the [tonic](https://github.com/hyperium/tonic) library. We don't have full control over our own network communication layer like Flink does. 

Post the problem here just for open discussion.

related: #990 #616

**Comment by skyzh** [comment]
> The challenge in implementing this solution is mainly that the ExchangeService relies on the [tonic](https://github.com/hyperium/tonic) library. We don't have full control over our own network communication layer like Flink does.

Probably not a big problem. gRPC supports bi-directional channels. So the sender can control whether to send a chunk based on ACK message received from the receiver side.

**Comment by StrikeW** [comment]
We use gRPC as our communication layer, which is built on top of HTTP2. As HTTP2 has native support for multiplexing (multiple **streams** over one connection) and flow control for each stream, we can leverage the HTTP2 to achieve back pressure in our streaming engine.
We decide to use the default settings of tonic gRPC library as our baseline implementation of back pressure. And we will evaluate its efficiency in more scenarios.
