### ISSUE TITLE
streaming: fix lookup union executor behavior

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2141]
Union should take all data from one side, then another side, one by one in order. The current barrier aligner for union needs to be refactored.

**Comment by fuyufjh** [comment]
> Union should take all data from one side, then another side, one by one in order.

🤔 Why?

**Comment by skyzh** [comment]
Given two records from one table R1, R2, if R1 happens before R2, then the output of the whole delta join should also have the property that R1 happens before R2. Union can ensure this property by using the strategy described in PR body.

e.g. R1 is delete, R2 is insert, if their order gets reversed, the output stream is incorrect.

**Comment by skyzh** [comment]
Changes of the table will not only affect the stream input of its side, it will also affects the content of the arrangement. So we must order those inputs in union.

**Comment by fuyufjh** [comment]
I am considering another case: `select * from source_1 union all select * from source_2`

The Union here does not care about where the chunks from - it should emit any chunk it received

**Comment by skyzh** [comment]
That's another union 🤣 Let's rename the current union to `LookupUnion`.
