### ISSUE TITLE
Negative num mod error 

### ISSUE THREAD

**Issue by XieJiann** [singularity-data/risingwave#215]
In pg, the result is :
```
postgres=# SELECT (-32768)::int2 % (-1)::int2;
 ?column?
----------
        0
(1 row)
```

In our system,  the result is:
```
dev=>SELECT (-32768)::int2 % (-1)::int2;
Error: Out of range
(1 row)
```

**Comment by xxchan** [comment]
Similar to https://github.com/singularity-data/risingwave/issues/4344, I think this behavior differs from PG but is acceptable. e.g., in rust:
```rust
  |
9 |         let c: i16 = -32768 % -1;
  |                      ^^^^^^^^^^^ attempt to compute the remainder of `i16::MIN % -1_i16`, which would overflow
  |
```

To be more specific, this is about the arithmetic for the minimum values of signed integer types. I will close it for now, and we can reopen it if further dicisions are made like #4344.
