### ISSUE TITLE
Is scan still useful when we have iter?

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#2221]
For example, `scan` is used in `CellBasedTableRowIter`'s `comsume_more`. This cumbersome manual buffering can be removed if we use `iter`.

Is there any legacy reason why we are using `scan` instead?

**Comment by skyzh** [comment]
Lookup executor currently is using scan. Basically, it will need to scan all keys belonging to a join key. Scan is easier to use than iter in this case.

**Comment by lmatz** [comment]
I see, if we use `iter` instead of `scan`, the lifetime would be infectious for any struct that contains the iterator recursively.

**Comment by skyzh** [comment]
DIdn't we removed the lifetime of iterators days before? 🤣 The problem for batch query is that, it might run for a long time, and storing an iterator would pin a version for too long.

**Comment by skyzh** [comment]
Currently, the vacuumer will only delete files < min pinned epoch. But if we optimize it to delete all files that aren't referenced, it's also okay to store the iter inside batch scan.
