### ISSUE TITLE
frontend: empty result returned if compactor panics

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2234]
https://github.com/singularity-data/risingwave/runs/6223691809?check_suite_focus=true

Not sure what's happening in the background... But I guess that might be a frontend's issue. sqllogictest gets an empty result, but the cause is indeed compactor panics.

<img width="975" alt="image" src="https://user-images.githubusercontent.com/4198311/165897011-93ece604-a019-4c3a-b9be-5312ee5f8bfc.png">

**Comment by skyzh** [comment]
... this happens on Java frontend, not sure if Rust frontend will have the same issue.

**Comment by skyzh** [comment]
[risedev-logs-6.zip](https://github.com/singularity-data/risingwave/files/8588793/risedev-logs-6.zip)

**Comment by skyzh** [comment]
cc @zwang28 it seems that failure in compactor will cause version corruption? Would you like to take a look after the holiday?

**Comment by zwang28** [comment]
> cc @zwang28 it seems that failure in compactor will cause version corruption? Would you like to take a look after the holiday?

I suspect the version is already corrupted as mentioned in https://github.com/singularity-data/risingwave/issues/2219#issuecomment-1113538546, then compactor panics as a result.
