### ISSUE TITLE
Vaccum more aggressively to reduce space amplification when iterator is used

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#2238]
I'd prefer to get this merged only when

> Currently, the vacuumer will only delete files < min pinned epoch. But if we optimize it to delete all files that aren't referenced, it's also okay to store the iter inside batch scan.

... this optimization is done. Otherwise, space amplification would be rather high.

_Originally posted by @skyzh in https://github.com/singularity-data/risingwave/issues/2236#issuecomment-1113010574_

**Comment by skyzh** [comment]
Another concern is that, after compaction, we can always get lower read-amp. However, if we always work on a single version during batch plan, it might not be efficient to scan.

**Comment by hzxa21** [comment]
> Currently, the vacuumer will only delete files < min pinned epoch. But if we optimize it to delete all files that aren't referenced, it's also okay to store the iter inside batch scan.

Pinned epoch is used to fence compaction not vacuuming. Currently, vacuumer will delete all files that are not pinned and not in the current HummockVersion (LSM MANIFEST).

> Another concern is that, after compaction, we can always get lower read-amp. However, if we always work on a single version during batch plan, it might not be efficient to scan.

I think this is the real concern.

**Comment by skyzh** [comment]
> Pinned epoch is used to fence compaction not vacuuming. Currently, vacuumer will delete all files that are not pinned and not in the current HummockVersion (LSM MANIFEST).

Sorry, I mean pinned version. Iter pins a version.

**Comment by lmatz** [comment]
The vacuuming part is done. Now we vacuum all the stale ssts that are not used by any older version. And we change the criteria of deleting a version to: a version's stale ssts can all be vacuumed and it is not pinned. (And of course, it cannot be the largest version, which stays the same).

For the other epoch part, i.e. 
1. pin_snapshot by frontend -> 
2. wait for each compute node to create an iterator and hold a version -> 
3. unpin_snapshot

I will probably do it after #2364 gets implemented as we need to deal with potential failures in the second step. Once failure occurs, the pinned snapshot should be unpinned.
