### ISSUE TITLE
should we depracate StreamServiceImpl's usused functions?

### ISSUE THREAD

**Issue by D2Lark** [singularity-data/risingwave#2260]
**Describe the bug**
I find that StreamServiceImpl only have flush function work . create_materialized_view and  drop_materialized_view are impled by DdlServiceImpl Instead. Should we keep then?
src/rpc_client/src/meta_client.rs
> macro_rules! for_all_meta_rpc {
>     ($macro:ident $(, $x:tt)*) => {
>         $macro! {
>             [$($x),*]
>             ,{ stream_client, flush, FlushRequest, FlushResponse }
>             ,{ ddl_client, drop_materialized_source, DropMaterializedSourceRequest, DropMaterializedSourceResponse }
>             ,{ ddl_client, drop_materialized_view, DropMaterializedViewRequest, DropMaterializedViewResponse }
>         }
>     };
> }
> 

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
add some commend or remove them

**Additional context**

**Comment by yezizp2012** [comment]
The other two RPC functions are used in our legacy Java frontend. We may have to keep it until the Java frontend deprecated.

**Comment by D2Lark** [comment]
Thanks for answering my questions~
