### ISSUE TITLE
Proposal: push down all predicate to LogicalScan in logical phase

### ISSUE THREAD

**Issue by st1page** [singularity-data/risingwave#2343]
propose to add a condition field in `LogicalScan` and push down all predicate to `LogicalScan` node, in other word, remove the pattern `LogicalFilter-LogicalScan` in the LoicalPlan.
- the `to_batch` and `to_stream` methods of `LogicalScan` will check if the predicates can be really push-down and the Scan with predicate can convert to some special physical operator such as `PointGet`, `index_scan`.
- in the `to_batch` and `to_stream` methods of `LogicalJoin`, we can easily check the pattern `LogicalJoin-LogicalScan` and then try to use `LookUpJoin`.

**Comment by skyzh** [comment]
I would +1 for this, especially for shared state and delta join.

What lookup executors can read from index are determined by the filter between join plan node and scan plan node. In fact, filter + scan together is a full representation of shared index. If we separate the plan node into filter + scan, some logics might be hard to write.

So the filter itself is part of the "arrangement" information. This change will definitely help if we want to easily support delta join with filter + joins.
