### ISSUE TITLE
Support `generate_series` for timestamp

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#2344]
**Is your feature request related to a problem? Please describe.**

It will be useful in testing for time window.

https://www.postgresql.org/docs/current/functions-srf.html

```
generate_series ( start timestamp, stop timestamp, step interval ) → setof timestamp
```

**Note: Consider reuse some codes with `generate_series_i32`**

**Comment by D2Lark** [comment]
I would like to try
