### ISSUE TITLE
Specify the additional independencies in doc when optional feature is enabled

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#2350]
For example, when the dashboard is enabled in risedev, `npm` needs to be installed first and then the user needs to install packages by `npm`.

**Comment by mikechesterwang** [comment]
Dashboard v2 does not require `npm`. To enable dashboard v2, simply set `enable-dashboard-v2` to true in `risedev.yml`, then it will automatically download the built artifact in `dashboard-artifact` branch of this repo.

But if you set `ENABLE_BUILD_DASHBOARD_V2`, which is for dashboard development, you should install `npm`.

**Comment by lmatz** [comment]
> Dashboard v2 does not require `npm`. To enable dashboard v2, simply set `enable-dashboard-v2` to true in `risedev.yml`, then it will automatically download the built artifact in `dashboard-artifact` branch of this repo.
> 
> But if you set `ENABLE_BUILD_DASHBOARD_V2`, which is for dashboard development, you should install `npm`.

I see, thanks for the explanation! I indeed tried to enable the dashboard by `./risedev configure`.
