### ISSUE TITLE
Dashboard v2 failed to parse the data from meta-node

### ISSUE THREAD

**Issue by mikechesterwang** [singularity-data/risingwave#2359]
**Describe the bug**
The parser in dashboard v2 failed to parse the data about stream plan.

**To Reproduce**
1. use frontend-legacy
2. run
```bash
./risedev slt -p 4567 -d dev './e2e_test/streaming/tpch/tpch_snapshot.slt'
```
3. start dashboard v2 via yarn
```bash
cd dashboard && yarn dev
```

**Comment by mikechesterwang** [comment]
1. Introduce type system 
2. Parse data via protobuf

**Comment by skyzh** [comment]
frontend-legacy will be deprecated soon. IIRC, the new frontend works perfectly with dashboard v1 and v2.

**Comment by skyzh** [comment]
Oops, it seems that dashboard v1 also doesn't work. I guess it's the problem of renaming node -> nodeBody?

**Comment by skyzh** [comment]
I guess we will need something like https://github.com/stephenh/ts-proto to ensure type safety. Also we will need to enable dashboard check when proto folder changes.

**Comment by mikechesterwang** [comment]
I'm not sure. Seems rust frontend failed to run tpch_snapshot.slt because of some `not implemented` panic. 
And the structure of the data is different, so the dashboard failed to parse and render the data correctly.

**Comment by skyzh** [comment]
Rust frontend should use v2 test cases.

```
./risedev slt -p 4566 './e2e_test/v2/streaming/tpch_snapshot.slt'
```

Most of the proto changes might be related to this PR: https://github.com/singularity-data/risingwave/pull/2255

**Comment by mikechesterwang** [comment]
Good to know. I will fix this now.

**Comment by mikechesterwang** [comment]
The operatorId is not unique for now. Seems this is inconsistent with the design. I will fix this issue after the operatorId issue is fixed.

**Comment by skyzh** [comment]
> The operatorId is not unique for now

Yes, now the fragment id is unique. Indeed, I'm thinking of whether we can visualize using fragment info, and attach actor id on each fragment.

**Comment by mikechesterwang** [comment]
They would be much easier since we don't have to group actors in the same fragment together.

**Comment by skyzh** [comment]
But one thing to notice is that, fragment doesn't have dispatcher and receiver / merger nodes. Also, fragment doesn't contain the link from upstream node to chain node.

**Comment by mikechesterwang** [comment]
> A good way to use fragment is to get the mapping from fragment to actors (1:n).

Hmm. This could save some works in dashboard UI. But the dashboard UI already finished the job, it might be a waste of time to implement this feature again in the meta node.
