### ISSUE TITLE
let GenericExchangeExecutor2 poll all the sources at the same instead of polling them sequentially

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#2362]
Currently, the executor would poll each upstream sources sequentially.

        loop {
            if self.source_idx >= self.sources.len() {
                break;
            }
            if self.current_source.is_none() {
                let proto_source = &self.sources[self.source_idx];
                let source =
                    CS::create_source(self.env.clone(), proto_source, self.task_id.clone()).await?;
                self.current_source = Some(source);
            }
            let mut source = self.current_source.take().unwrap();
            match source.take_data().await? {
                None => {
                    self.current_source = None;
                    self.source_idx += 1;
                }
                Some(res) => {
                    if res.cardinality() == 0 {
                        debug!("Exchange source {:?} output empty chunk.", source);
                        assert_ne!(res.cardinality(), 0);
                    }
                    self.current_source = Some(source);
                    yield res;
                }
            }
        }

This is less efficient than polling all the upstream sources at the same time,
as no matter which upstream source has data chunk being ready to be fetched, the downstream can immediately process the data chunk instead of waiting for a specific upstream source.

We may make `CS::create_source` return a stream for each upstream source, and then `select_all` them.

**Comment by D2Lark** [comment]
I wanna try this

**Comment by lmatz** [comment]
> I wanna try this

Thanks for your interest and contribution! Please feel free to ping me on Slack (@Martin) if there is any question.
