### ISSUE TITLE
Use background thread to pin snapshots, rather than pin/unpin snapshot each time.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#2364]
* [x] add unpin_snapshot_before RPC: #2964 
* [x] use this rpc in frontend hummock snapshot manager. It only affects unpin. #2993 
* [ ] ~~meta auto pin the epoch and push to all FEs (switched to push-based)~~

**Comment by lmatz** [comment]
Will this solve issue #2356?

**Comment by liurenjie1024** [comment]
> Will this solve issue #2356? 

Yes

**Comment by BowenXiao1999** [comment]
This issue may divide into some parts

* [ ]: add unpin_snapshot_before RPC
* [ ]: use this rpc in frontend hummock snapshot manager. It only affects unpin. 
* [ ]: meta auto pin the epoch and push to all FEs (switched to push-based)

**Comment by ZENOTME** [comment]
for now, we have a new implementation of HummockSnapshotManager after https://github.com/singularity-data/risingwave/issues/3551. 
Using background thread to pin snapshots seems not a good idea (it will cause consistency problem #3559). 
To prevent pin/unpin snapshots each time, the next implementation is the 'push-base'.  So I think we can close this issue now?
