### ISSUE TITLE
RFC: DataGen source

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#2377]
Flink supports a [DataGen Connector](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/table/datagen/) to generate rows, which is very useful for quick tests. 

Example:

```sql
CREATE TABLE Orders (
    order_number BIGINT,
    price        DECIMAL(32,2),
    buyer        ROW<first_name STRING, last_name STRING>,
    order_time   TIMESTAMP(3)
) WITH (
  'connector' = 'datagen'
);
```

Then you can run queries againest this table.

**Comment by neverchanje** [comment]
This had been discussed in https://github.com/singularity-data/risingwave/issues/2323. Probably a duplicated issue?

**Comment by StrikeW** [comment]
Is it an append only stream or a general stream?

**Comment by fuyufjh** [comment]
> Is it an append only stream or a general stream?

It's append-only in my imagination, but it would be great to enhance it to general

**Comment by fuyufjh** [comment]
> This had been discussed in https://github.com/singularity-data/risingwave/issues/2323. Probably a duplicated issue?

I had not dived into the generated data of NexMark. If it can be used as a general random data generator, we can close this issue as duplicated

**Comment by TennyZhuang** [comment]
Kexiang and I have come to some agreement.

NexMark's schema is specified and it's non-trivial to generate it. Kexiang will create NexMark source or connector, and leave the general datagen for the issue.

**Comment by fuyufjh** [comment]
replaced by #2401
