### ISSUE TITLE
Append-only HashJoin Executor

### ISSUE THREAD

**Issue by StrikeW** [singularity-data/risingwave#2407]

**Comment by fuyufjh** [comment]
Before starting coding, let's figure out the questions: What can be done to optimize HashJoin executor if its inputs are append-only?

**Comment by lmatz** [comment]
If the columns of the join key happen to be the same as the columns of the primary key, then once there is a match of equal condition, records can be deleted.

**Comment by jon-chuang** [comment]
> If the columns of the join key happen to be the same as the columns of the primary key, then once there is a match of equal condition, records can be deleted.

Must be primary on both sides.

**Comment by lmatz** [comment]
> > If the columns of the join key happen to be the same as the columns of the primary key, then once there is a match of equal condition, records can be deleted.
> 
> Must be primary on both sides.

Yes 👍 

And no need to be the same, the join key containing the primary key also works.

Then data records can also be deleted even when there is no match of equal join condition, i.e. both sides have seen data records with the same primary key, but the join keys are different.
