### ISSUE TITLE
Stop a running batch task

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#2411]
When we schedule a number of batch tasks belonging to the same stage, we may cancel running tasks when some other tasks fail so that we can reschedule the whole stage.

It is also possible that we only re-schedule those failed tasks in certain cases, and thus less time is wasted. But this is a trade-off. We implement the functionality first.

**Comment by lmatz** [comment]
Related: #2364

**Comment by liurenjie1024** [comment]
This is in fact tracked here: https://github.com/singularity-data/risingwave/issues/1977.

Currently, when one task failed, we should cancel the whole query. Our batch query engine serves for adhoc query and has no fault tolerance policy. This is different from etl tools like spark. We may need change our design if fault tolerence if needed.
