### ISSUE TITLE
Avoid unnecessary new hummock version

### ISSUE THREAD

**Issue by zwang28** [singularity-data/risingwave#2414]
**Is your feature request related to a problem? Please describe.**
Current we store `max_committed_epoch` in `HummockVersion`. We will create a new hummock version **even no data is updated** in a epoch, just in order to increase `max_committed_epoch`: https://github.com/singularity-data/risingwave/blob/4706d773a140a79053a922c6232449887c92a3b3/src/meta/src/hummock/hummock_manager.rs#L800
The problem is vacuum(metadata) can spend a lot of time removing these no-data-changed `HummockVersion` before doing actual work.
vacuum(SST) is not related here.

**Describe the solution you'd like**
Can we make `commit_epoch` no-op if no data changed within that epoch? That is neither `max_committed_epoch` changed or new `HummockVersion` added.

~~Store a `max_committed_epoch` -> `HummockVersion`s mapping in meta, instead of storing `max_committed_epoch` in each `HummockVersion`.~~
~~Now `HummockVersion`s with same id may contain different `max_committed_epoch`. Changes required in local version management.~~

**Comment by hzxa21** [comment]
The reason why `max_committed_epoch` does not come with changes in the SST set is because we put uncommitted SSTs in HummockVersion first via `add_tables` RPC and commit those SSTs via `commit_epoch`. Maybe it is time to get rid of `add_tables` RPC completely?

**Comment by hzxa21** [comment]
Btw, there is data updated in HummockVersion on `commit_epoch`: we move SSTs in uncommitted_epoch into level0 so I don't think version update can be skipped.

**Comment by zwang28** [comment]
> > Can we make `commit_epoch` no-op if no data changed within that epoch? That is neither `max_committed_epoch` changed or new `HummockVersion` added.
> 
> I think we need to bump max_committed_epoch even if no data has changed in that epoch in order to make wait_epoch works.

Yes I mean wait_epoch need to know no data changed between epoch_1 and epoch_2. For example barrier can carry this info.
