### ISSUE TITLE
RFC: use pk of the table to accelerate the query

### ISSUE THREAD

**Issue by st1page** [singularity-data/risingwave#2429]
use pk of the table to accelerate the query
we can implement it step by step
- [x] condtion: pk EQ const
- [x] condition pk_prefix EQ const
- [x] condition pk_prefix GT(or LT) const 
#### storage
  - [x] CellbasedTable::get_row
  - [x] #2811
    - maybe we can use `CellBasedTableStreamingIter` here because the data are not too much. just do not forget to wit epoch. https://github.com/singularity-data/risingwave/issues/2795 streaming part has the same requirement. 
#### field addition
- [x] add optional pk_prefix and pk bounds(upper, lower) on RowSeqScan's executor, proto and BatchPlanNode #3014
#### batch executor
- #3014
  - when the RowSeqScan with the pk.len() == pk_prefix.len() it will use the cellbasedTable::get_row()
  - use CellbasedTable::iter for the pk_prefix and pk bounds(upper, lower)
#### optimizer
- https://github.com/singularity-data/risingwave/issues/2343
- in LogicalScan::to_batch, extract the comparison predicate on the pk #3014
   - put the predicates inside the BatchSeqScan
   - gen  a BatchFilter with the other predicates
- [ ] https://github.com/singularity-data/risingwave/issues/3477
#### scheduler
- [ ] for the fragment with hashShard(key) and the key are on an Equal predicate, we can ensure it can only be on one hash shard, the scheduler should be aware of that and determine which CN it should run on.
  - it is just a optimization and we can do it later
  - need more design
  - https://github.com/singularity-data/risingwave/issues/3450

**Comment by st1page** [comment]
There still are some questions not very clear, so I will re-think this issue later.

**Comment by liurenjie1024** [comment]
I think we also need to think about the `in (const1, const2. ...)` case
