### ISSUE TITLE
Implement generate_series(int) in frontend correctly

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#2443]
We may need a schema infer for table function?

**Comment by xiangjinwu** [comment]
`generate_series(int)` was never fully implemented in rust frontend: #1139

**Comment by D2Lark** [comment]
> `generate_series(int)` was never fully implemented in rust frontend: #1139

Yes. Although we now have a logical_generate_series, a PlanNode that can only resolve time parameters, there is a generate i32 series in the batch executor, but no corresponding front-end

**Comment by D2Lark** [comment]
I wanna try this
