### ISSUE TITLE
bug: `IN` expression doesn't work

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#2456]
```
eric=> select * from orders where o_orderkey in (9,10);
ERROR:  internal error: internal error: [PlanNode: Ok(Filter(FilterNode { search_condition: Some(ExprNode { expr_type: In, return_type: Some(DataType { type_name: Boolean, precision: 0, scale: 0, is_nullable: true, interval_type: Invalid, field_type: [] }), rex_node: Some(FuncCall(FunctionCall { children: [ExprNode { expr_type: InputRef, return_type: Some(DataType { type_name: Int64, precision: 0, scale: 0, is_nullable: true, interval_type: Invalid, field_type: [] }), rex_node: Some(InputRef(InputRefExpr { column_idx: 0 })) }, ExprNode { expr_type: Cast, return_type: Some(DataType { type_name: Int64, precision: 0, scale: 0, is_nullable: true, interval_type: Invalid, field_type: [] }), rex_node: Some(FuncCall(FunctionCall { children: [ExprNode { expr_type: ConstantValue, return_type: Some(DataType { type_name: Int32, precision: 0, scale: 0, is_nullable: true, interval_type: Invalid, field_type: [] }), rex_node: Some(Constant(ConstantValue { body: [0, 0, 0, 9] })) }] })) }, ExprNode { expr_type: Cast, return_type: Some(DataType { type_name: Int64, precision: 0, scale: 0, is_nullable: true, interval_type: Invalid, field_type: [] }), rex_node: Some(FuncCall(FunctionCall { children: [ExprNode { expr_type: ConstantValue, return_type: Some(DataType { type_name: Int32, precision: 0, scale: 0, is_nullable: true, interval_type: Invalid, field_type: [] }), rex_node: Some(Constant(ConstantValue { body: [0, 0, 0, 10] })) }] })) }] })) }) }))] Failed to build executor: internal error: child.get_expr_type()? == expr_node::Type::ConstantValue
```

**Comment by xiangjinwu** [comment]
https://github.com/singularity-data/risingwave/blob/79d451e1ee3fc2acbcd2eb7e161f161ffb6c4699/src/expr/src/expr/build_expr_from_prost.rs#L145-L149

For some reason it was implemented to only support `InputRef` in `[Literals]`.

In this case, `o_orderkey` is `bigint` but `9` and `10` are `int`. So there is an implicit cast `9::bigint` that violates the requirement of `Literal`.

**Comment by TennyZhuang** [comment]
We can rewrite the other arguments to `OR` conditions

**Comment by fuyufjh** [comment]
> We can rewrite the other arguments to `OR` conditions in frontend

-1, that could be a long list

**Comment by xiangjinwu** [comment]
* Seem the restriction of `Literal` on right side can be relaxed to expressions that can be folded into a constant.
* If there are InputRefs on the right side, they will need to be rewritten as `OR`. The subset of const exprs can remain in `in-list`.

For example:
`v1 in (3, 2+2, v2, 7, v3+5)` -> `v1 in (3, 4, 7) or v1 = v2 or v1 = v3+5`

Besides, the left side should be able to handle any expr beyond `InputRef`.

For now, folding `2+2` into `4` is not supported. But it is easy to impl `is_foldable` as `! expr.has_input_ref`.

**Comment by TennyZhuang** [comment]
> > We can rewrite the other arguments to `OR` conditions in frontend
> 
> -1, that could be a long list

I mean rewrite `where x in (y, 1, 2, 3, 4)` to `where x = y and x in (1, 2, 3, 4)`

Please note that:

1. It's very rare for an in expression that contains multiple non-literal arguments after we implement constant folding correctly, unless we support wide table later.
2. In fact, they share the same complexity before and after rewrite. Assume that we have m literal args and n non-literal args, all we can do is constructing an hashmap with O(m) space and spend O(1) lookup and O(n) compare for each record. It's unavoidable.
3. They will be exact same thing if we implement our expression framework using code generation technology. They will be compiled to exact the same thing, but rewrite it in frontend can make the logical of `in` really simple.
4. Unfortunately, we use vectorized model now. The only overhead of the rewrite is more chunk allocation during evaluation. Based on 1, I think it's acceptable.
