### ISSUE TITLE
Error Handling in zero division and integer overflow

### ISSUE THREAD

**Issue by marvenlee2486** [singularity-data/risingwave#2473]
**Describe the bug**
```
create table t (v1 int, v2 int);
insert into t values (1,0);
select v1/v2 from t;
```

The error shown is 
`ERROR:  internal error: internal error: broken fifo_channel`

**Expected behavior**
Showing The error Zero division or NULL.

**Additional context**
Proper error handling should goes for integer overflow too.
```
create table t (v1 int, v2 int);
insert into t values (1000000,1000000);
select v1*v2 from t;
```

**Comment by BugenZhao** [comment]
Actually we implement arithmetic expressions with `checked_` API, if we directly select an expression of literals we will get the proper error message.

```
bugenzhao=> select 1::int / 0::int;
ERROR:  internal error: Out of range
bugenzhao=> select 1000000::int * 1000000::int;
ERROR:  internal error: Out of range
```

The `broken fifo_channel` is likely due to the batch exchange's implementation not handling or reporting errors from input correctly.

**Comment by liurenjie1024** [comment]
Yes, we should refine error report later.

**Comment by xxchan** [comment]
close in favor of https://github.com/singularity-data/risingwave/issues/3908
