### ISSUE TITLE
pgwire: frontend crashed on invalid sql input

### ISSUE THREAD

**Issue by cykbls01** [singularity-data/risingwave#2485]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/36026213/168195238-974d17ab-de16-431b-a91d-36cf41c3e1e0.png">

To Reproduce
Use psql to execute an invalid input sql.

Expected behavior
Display the error instead of panic.

**Comment by neverchanje** [comment]
Good finding! I think this bug is reproducible only if we are using a Postgres client SDK since most of the terminals don't accept non-utf8 chars.
