### ISSUE TITLE
bug: the implementation of BatchAgg might be wrong.

### ISSUE THREAD

**Issue by likg227** [singularity-data/risingwave#2486]
**Describe the bug**
I modified tpch q21 to only `select *`, and it outputs 15 rows, which is correct. But, when I modified it to `select count(*)`, it returns 0, which is absolutely wrong. BTW, `select count(s_name)` returns 15, which is correct.
Besides, I add `group by s_name` and `select count(s_name)` and it returns 609, which is incorrect.

**To Reproduce**
```
select
    count(*) 
from
    supplier,
    lineitem l1,
    orders,
    nation
where
    s_suppkey = l1.l_suppkey
    and o_orderkey = l1.l_orderkey
    and o_orderstatus = 'F'
    and l1.l_receiptdate > l1.l_commitdate
    and exists (
        select
            *
        from
            lineitem l2
        where
            l2.l_orderkey = l1.l_orderkey
            and l2.l_suppkey <> l1.l_suppkey
    )
    and not exists (
        select
            *
        from
            lineitem l3
        where
            l3.l_orderkey = l1.l_orderkey
            and l3.l_suppkey <> l1.l_suppkey
            and l3.l_receiptdate > l3.l_commitdate
    )
    and s_nationkey = n_nationkey
    and n_name = 'IRAQ';
```
You can change q21 to this to reproduce the bug.

**Expected behavior**
We expect `count(*)` to return 15.

**Additional context**
I think there are something wrong with the implementation of BatchAgg.

**Comment by liurenjie1024** [comment]
Is this in new frontend or old frontend?

**Comment by liurenjie1024** [comment]
cc @xiangjinwu @st1page

**Comment by likg227** [comment]
> Is this in new frontend or old frontend?

I only test it in new frontend.

**Comment by StrikeW** [comment]
For the query you provided, the reason why `count(*)` is 0 is that **there is no input to the SimpleAgg**. 
```
                                                           QUERY PLAN
--------------------------------------------------------------------------------------------------------
 BatchSimpleAgg { aggs: [count] }
   BatchExchange { order: [], dist: Single }
     BatchProject { exprs: [] }
       BatchHashJoin { type: LeftAnti, predicate: $0 = $2 AND ($3 <> $1) }
         BatchHashJoin { type: LeftSemi, predicate: $0 = $2 AND ($3 <> $1) }
           BatchProject { exprs: [$1, $2] }
             BatchExchange { order: [], dist: HashShard([1]) }
               BatchHashJoin { type: Inner, predicate: $0 = $3 }
                 BatchProject { exprs: [$0, $1, $2] }
                   BatchExchange { order: [], dist: HashShard([0]) }
                     BatchHashJoin { type: Inner, predicate: $1 = $3 }
                       BatchProject { exprs: [$1, $2, $3] }
                         BatchExchange { order: [], dist: HashShard([2]) }
                           BatchHashJoin { type: Inner, predicate: $0 = $3 }
                             BatchExchange { order: [], dist: HashShard([0]) }
                              ...
```

The query plan shows that the expressions for the child Project operator is empty. And according to the implementation of project executor, its output will be empty if the project expression is not provided. So is it the expect behavior of Project executor? Or the query plan is wrong? @liurenjie1024 

> Besides, I add group by s_name and select count(s_name) and it returns 609, which is incorrect.

For this I think there is no clear clues show that the wrong result is caused by BatchHashAgg. Maybe you should dig it deep. Since the `count(*)` is wrong just because there is no input. @likg227

**Comment by likg227** [comment]
It is correct that count(*) has no argument, and we may have zero columns with non-zero cardinality.

**Comment by BugenZhao** [comment]
> It is correct that count(*) has no argument, and we may have zero columns with non-zero cardinality.

You may check whether the chunk with empty columns is correctly handled by `DataChunk::new_dummy`. May related #182.

**Comment by BugenZhao** [comment]
It seems when there's no output, the cardinality is not preserved in batch's ProjectExecutor.

https://github.com/singularity-data/risingwave/blob/10f0d2eb580ebac13329b2e33ac7e9ada5a9e35c/src/batch/src/executor2/project.rs#L47-L63
