### ISSUE TITLE
kafka: No data was consumed if there's no such topic

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#2487]
**Describe the bug**

No data was consumed from kafka if the source was created on a non-existed topic.

**To Reproduce**
Steps to reproduce the behavior.

```sql
create materialized source ad_source (
  user_id bigint, ad_id bigint, click_timestamp timestamp, 
  impression_timestamp timestamp
) with (
  'connector' = 'kafka', 'kafka.topic' = 'ad_clicks', 
  'kafka.brokers' = 'localhost:29092', 
  'kafka.scan.startup.mode' = 'earliest'
) row format json;
```

Firstly, create a topic right before creating the corresponding kafka topic. 
Secondly, load the data to kafka, and it will subsequently create a kafka topic.  

```
./target/debug/workload_generator --config ./configs/case-ad.yaml
```

I tried scanning from the source but even after a long time, the source is still empty.

```
dev=> select * from ad_source;
 user_id | ad_id | click_timestamp | impression_timestamp
---------+-------+-----------------+----------------------
(0 rows)
```

**Expected behavior**

An increasing number of records must be inserted. 

**Additional context**

I think it could due to `KafkaSplitEnumerator` failing to fetch the offset of a non-existed topic, and this is unexpected.

**Comment by shanicky** [comment]
At this stage, creating a Source on a topic that has not been created should report an error, I'll fix it.
