### ISSUE TITLE
bug: database space exceeded in etcd after the cluster becomes idle for a long time

### ISSUE THREAD

**Issue by hzxa21** [singularity-data/risingwave#2491]
**Describe the bug**
Encounter "etcdserver: mvcc: database space exceeded" when I leave the cluster idle for a while and re-run some queries.
```
patrick=> select * from mv1;
ERROR:  internal error: Error while interact with meta service: grpc request error: status: ResourceExhausted, message: "etcdserver: mvcc: database space exceeded", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```
**To Reproduce**
- Start a cluster with `./risedev dev full`
- Write some data with kafka source, create a MV and run some queries
- Leave the cluster idle for a while (in my case, I leave it idle for 12hr...)
- Run some queries again

**Expected behavior**
- Cluster should be up and healthy, and queries should still succeed after it has been idle for a long time.
- Should we expose etcd error directly to the sql client?

**Additional context**
[meta-node-5690.log](https://github.com/singularity-data/risingwave/files/8683902/meta-node-5690.log)
[etcd.log](https://github.com/singularity-data/risingwave/files/8683904/etcd.log)
[compute-node-5688.log](https://github.com/singularity-data/risingwave/files/8683905/compute-node-5688.log)

My guess is we write metadata on every barrier even when there is no write into the cluster and etcd compaction cannot keep up. Also I saw meta node recovery in the log. Not sure whether it is related.

**Comment by zwang28** [comment]
> My guess is we write metadata on every barrier even when there is no write into the cluster and etcd compaction cannot keep up

I think so. auto-compaction-retention is disabled according to etcd.log.
