### ISSUE TITLE
RFC: make predicates pushdown a trait and impl it for PlanNode.

### ISSUE THREAD

**Issue by likg227** [singularity-data/risingwave#2502]
We currently using rules to push predicates down. One limitation of this method is that PlanNodes must satisfy some patterns(e.g. Filter->Join) so that predicates can be pushed down. This method can solve all of the cases but we have to match too many patterns, which is lack of flexbility and can be a little annoying. Besides, it's easy to miss some patterns. A related issue is #2463.

To eliminate this limitation, We can have a trait named `PredicatesPushdown` which has a function named `push_down`, and implement it for every PlanNode, just like `prune_col`. The signature of `push_down` can be like this: `push_down(&self, predicates) -> PlanRef`. 

There are three kinds of predicates: 
1. those can't be pushed down. We just create a LogicalFilter for them above the current PlanNode.
2. those can be merged with current PlanNode(e.g. LogicalJoin). We just merge the predicates with the Condition of it.
3. those can be pushed down. We pass them to current PlanNode's child.

This method is expected to solve #2463, and gives more flexiblity which is useful if we want to support more rules to push predicates down.

**Comment by skyzh** [comment]
Optimizer rules can have states. I guess we can implement this using optimizer rules, instead of introducing a new trait?

**Comment by likg227** [comment]
> Optimizer rules can have states. I guess we can implement this using optimizer rules, instead of introducing a new trait?

Just using rules can handle all the cases, but using a new trait can be more elegant and flexible.

**Comment by xxchan** [comment]
Although I can accept it, but I'd like to list some reasons to support just using rules.
1. Using traits to do RBO might be confusing. Future developers may still wonder why not simply using rules. Actually I did so for `ColPrunable`.
2. The trait implementations will be split into plan nodes, and the trait can be used in other places than optimizer. Comparatively, we have dedicated places to implement and use rules (better modularity).
3. The real implementation code won't be simplified. 
4. Is the "flexiblity" necessary for predicate pushdown? Probably there may not be many more cases to consider in the future.

**Comment by likg227** [comment]
3. To solve #2463, we need a new rule to match LogicalJoin, and duplicate some parts of code used in FilterJoin.
4. For those nodes can't be pushed filter through, we just use a default implementation for them, which is creating a LogicalFilter above them. Besides, we don't need FilterMerge anymore. For flexibility, one thing to note that we have LogicalHopWindow now, and we may push filters throught it, cc @TennyZhuang. Also, we may push predicates through LogicalLimit. If a LogicalLimit is in subquery and we can push predicates from outer query through it. In conclusion, impl a trait forces us to consider each case.
As for 1 and 2, predicates pushdown is just like prune_col.

**Comment by st1page** [comment]
> impl a trait forces us to consider each case.

+1 for this. The predicate seems should be like col_prune and every logical plan node should implement it.
 
>Is the "flexiblity" necessary for predicate pushdown? Probably there may not be many more cases to consider in the future.

the `col_prune` and `push_down` actually completely pass and rewrite the whole plan tree. we might want to do that lazily in some rules. but in that case we can simply insert a Filter or Project operator in the tree and do the whole tree rewriting other where.

**Comment by st1page** [comment]
> we can simply insert a Filter or Project operator

even we can add a `prune_col_non_recursive`, and `push_down_non_recursive` method when we really want them.
