### ISSUE TITLE
ci: add cargo doc test

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#2504]
> > LGTM. a little confused why this passed CI, but did not pass `cargo test`. Is there different between cargo test and risedev test？
> 
> Maybe cargo nextest doesn't run doctests?

<img width="902" alt="image" src="https://user-images.githubusercontent.com/36908971/168263702-3eb563e0-92a9-488f-a358-c191ffc56dfe.png">

indeed. We may need a extra doc test in CI

_Originally posted by @BowenXiao1999 in https://github.com/singularity-data/risingwave/pull/2503#issuecomment-1125886719_

**Comment by BowenXiao1999** [comment]
nextest not support default doc test. So we need to switch back to cargo test to test it.

**Comment by st1page** [comment]
is this a kind of bug？#bugbash

**Comment by D2Lark** [comment]
Can the` doc test `also be added to `. /risedev check` ? I've been screwed many times :)

**Comment by skyzh** [comment]
> Can the`doc test`also be added to `. /risedev check` ? I've been screwed many times :)

My consideration is that, risedev check should only check for most common issues (e.g. clippy, fmt, unit test) while not checking complicated and infrequent ones (sqllogictest, doc test). It's of low chance that people would get doc tests wrong, so I believe it's okay to leave it only running on CI. 🤣

**Comment by D2Lark** [comment]
> My consideration is that, risedev check should only check for most common issues (e.g. clippy, fmt, unit test) while not checking complicated and infrequent ones (sqllogictest, doc test). It's of low chance that people would get doc tests wrong, so I believe it's okay to leave it only running on CI. 🤣

you are right, maybe it's because I have refactored too many issues in one breath before...
