### ISSUE TITLE
add e2e v2 test for batch join non-equi condition in 

### ISSUE THREAD

**Issue by yuhao-su** [singularity-data/risingwave#2512]
@yuhao-su Could you add a regression test somewhere (maybe in e2e tests) to show that this no longer fails?

_Originally posted by @jon-chuang in https://github.com/singularity-data/risingwave/issues/2462#issuecomment-1125413684_

**Comment by likg227** [comment]
I have added e2e test for it.
https://github.com/singularity-data/risingwave/blob/main/e2e_test/v2/batch/subquery.slt
