### ISSUE TITLE
create database is not behaving normally

### ISSUE THREAD

**Issue by mikechesterwang** [singularity-data/risingwave#2529]
**Describe the bug**
1. Drop database is not working.
2. A table in a database should be invisible to the other database.

**To Reproduce**
```bash
psql -h localhost -p 4566
```
1. create a database
```bash
mike=> create database test;
```
2. switch to the new database
```bash
mike=> \c test
test=>
```
3. drop database (bug 1: this database is dropped. but we can still use this database)
```bash
test=> drop database test;
DROP_DATABASE
test=> drop database test;
ERROR: Catalog error: database not found: test
```
4. create a datababse
```bash
test=> \c mike
psql (14.2, server 0.0.0)
You are now connected to database "mike" as user "mike".
mike=> create table t ();
```
5. switch to the database already dropped. (bug 1: we've already dropped this database before, but we can still switch to it)
```bash
mike=>\c test
psql (14.2, server 0.0.0)
You are now connected to database "test" as user "mike".
test=> 
```
5. show tables. (bug 2: table `t` is created in database `mike`, but it is visible in database `test`)
```bash
test=> show tables;
 Name 
------
 t
(1 row)
```

**Expected behavior**
1. Tables should be invisible to the other database
2. Dropped database should be dropped.

**Additional context**

**Comment by likzn** [comment]
Is below code the reason of it? Because we all use mock connection now so the operations are all in the same database.
https://github.com/singularity-data/risingwave/blob/fb519e5d47c4a6481cd91f49454dd403847104dd/src/utils/pgwire/src/pg_protocol.rs#L114-L126

**Comment by mikechesterwang** [comment]
> Is below code the reason of it? Because we all use mock connection now so the operations are all in the same database.
> 
> https://github.com/singularity-data/risingwave/blob/fb519e5d47c4a6481cd91f49454dd403847104dd/src/utils/pgwire/src/pg_protocol.rs#L114-L126

oh, make sense. This explains everything :)
