### ISSUE TITLE
Migrate existing E2E test cases to Rust frontend

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#2538]
> Check E2E test cases and make sure all cases are covered in `v2/` before removing them

See also #2523

**Comment by TennyZhuang** [comment]
Almost done in #2536, may @liurenjie1024 can review again in batch.

**Comment by TennyZhuang** [comment]
It's too difficult to check all tests are migrated, I will remove the legacy tests anyway.
