### ISSUE TITLE
expr: `pg_sleep` should not put the thread to sleep

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#2561]
We currently use `std::thread::sleep` to implement `pg_sleep`, which will put the current thread to sleep. This may block other coroutines from running and reduce system throughput.

https://github.com/singularity-data/risingwave/blob/afae907958792aa4f3f325973dfc43160a89e39a/src/expr/src/expr/pg_sleep.rs#L58-L66

**Comment by skyzh** [comment]
But expr evaluation is not async 🤣

**Comment by BugenZhao** [comment]
> But expr evaluation is not async 🤣

That's why I'm giving no idea how to resolve this. 🤣

**Comment by skyzh** [comment]
Previously I had a proposal that we only allow pg_sleep as the outer-most level function call. e.g, `pg_sleep(100)`, `pg_sleep(x)`. The expr evaluation will only evaluate the inner args. After the evaluator gets the result from inner args, it will call tokio's sleep instead.

**Comment by BugenZhao** [comment]
> Previously I had a proposal that we only allow pg_sleep as the outer-most level function call. e.g, `pg_sleep(100)`, `pg_sleep(x)`. The expr evaluation will only evaluate the inner args. After the evaluator gets the result from inner args, it will call tokio's sleep instead.

So the caller may still face an async `eval` interface? If so, another solution might be use `spawn_blocking` once we find there's a `pg_sleep` inside the expr tree.

**Comment by skyzh** [comment]
I think the above logic can be written in ProjectExecutor.

**Comment by liurenjie1024** [comment]
+1 for remove `pg_sleep`. It was used in test and I think it should (or already) be supported by sqllogictest.
