### ISSUE TITLE
bitmap: use compact encoding on prost

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2569]
```
    pub fn to_protobuf(&self) -> ProstBuffer {
        let mut buf = ProstBuffer::default();
        for b in self.iter() {
            buf.body.push(b as u8);
        }
        buf
    }
```

Currently, we encode 1 bit as 1 byte, which is extremely inefficient.

**Comment by BugenZhao** [comment]
Sames as the `BoolArray`.

https://github.com/singularity-data/risingwave/blob/46160cc052911b65e55f2f5c59e4578808f67667/src/common/src/array/bool_array.rs#L73-L93

**Comment by BugenZhao** [comment]
> Same as the `BoolArray`.
> 
> 
> 
> https://github.com/singularity-data/risingwave/blob/46160cc052911b65e55f2f5c59e4578808f67667/src/common/src/array/bool_array.rs#L73-L93

Seems it's not trivial to refactor bool array with compacted encoding since we need to provide a cursor-read API?
