### ISSUE TITLE
config: using reasonable value for default config

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2578]
https://github.com/singularity-data/risingwave/blob/main/src/config/risingwave.toml

* block size is too small. We used to use 64KB months ago. I couldn't remember when we've changed it.
* block cache could be bigger (e.g. 4GB)
* config items can be expressed in mb
* bloom_false_positive generally should be like 0.01

**Comment by zwang28** [comment]
Notice that `block_cache_capacity` and `meta_cache_capacity` are actually used as number of entries rather than size, in cache implementation.
