### ISSUE TITLE
streaming: avoid exhausting resource in SourceExecutor

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2600]
Currently, if we received a large chunk from Kafka, the chunk will be split and fully sent to downstream before a barrier can be injected.

https://github.com/singularity-data/risingwave/blob/6f76c26cc4be97b6ab28e9676fad5877acaa7a47/src/stream/src/executor/source.rs#L258-L275

We should prefer barrier in all cases.

**Comment by skyzh** [comment]
maybe related to https://github.com/singularity-data/risingwave/issues/2580

**Comment by tabVersion** [comment]
fixed in #2608, I will make some restrictions on chunk size in connector or source later.
