### ISSUE TITLE
Pgwire Extended Query

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#2621]
https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

## References

As postgres has not a good document in detail of the message format, I suggest reading the cratedb implementation of pgwire:
- https://github.com/crate/crate/blob/master/server/src/main/java/io/crate/protocols/postgres/PostgresWireProtocol.java#L557:18

**Comment by BowenXiao1999** [comment]
Previous implemented pg-wire tracking issue also provide useful resources:
https://github.com/singularity-data/risingwave-legacy/issues/2019

I often looked at previous zenith (https://github.com/neondatabase/neon/blob/main/libs/utils/src/pq_proto.rs) for ref. But they do not support extended query in rust well (Only some control method). See https://github.com/neondatabase/neon/issues/1759

I also found below resources useful:
https://www.highgo.ca/2021/12/10/a-look-inside-postgresqls-extended-query-protocol/
https://blog.hackeriet.no/Simple-and-Extended-postgresql-queries/

**Comment by neverchanje** [comment]
> I propose to merge a naive PR first and do it step by step.
Sure.

>  We should also look at how metabase use pg client.
Technically, you can test the functionality using rust's pg client, and I believe it's able to issue extended-mode queries as long as it's mature enough.

**Comment by ZENOTME** [comment]
Below is the todo list used to gradually implement the Pgwire Extended Query step by step.
- [ ] #2924
