### ISSUE TITLE
streaming: stall source if barrier latency is significantly large

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2625]
If we don't stall, there a vicious cycle:

still doing checkpoint -> meta don't send a new barrier -> source consuming data -> making this epoch bigger and bigger -> next barrier takes longer and longer

Barrier latency is a good indicator of how the system is processing data. If, for example, source executor didn't receive a barrier > 200ms, then source should be stalled.

**Comment by yuhao-su** [comment]
Would another strategy be something similar to the one conducted by `RearrangedChainExecutor`?

**Comment by skyzh** [comment]
> Would another strategy be something similar to the one conducted by `RearrangedChainExecutor`?

Would you please elaborate in more details?

**Comment by StrikeW** [comment]
Will the concurrent checkpoint will ease the problem?

**Comment by fuyufjh** [comment]
Not sure whether this is necessary 🤔

Assuming that the system becomes slow because CPU resource is exhausted, in this case, the source actually consumes messages more slowly, which constitutes a natural negative feedback loop.

**Comment by yuhao-su** [comment]
> > Would another strategy be something similar to the one conducted by `RearrangedChainExecutor`?
> 
> Would you please elaborate in more details?

I'm thinking about buffering barriers generated by meta (while they might not have to wait until the last epoch finish to generate a new barrier). And then take barriers from the buffer and inject them into the big epoch from the source similar to how we steal barriers in `RearrangedChainExecutor`.

**Comment by skyzh** [comment]
> Will the concurrent checkpoint ease the problem?

Yes for sure! If we can send barrier by fixed interval, then there won't be problems on barrier. But now checkpoint will become heavier and heavier, we will still find other ways to limit data in one epoch.

**Comment by skyzh** [comment]
> Assuming that the system becomes slow because CPU resource is exhausted, in this case, the source actually consumes messages more slowly because it has less CPU time to poll, which constitutes a natural negative feedback loop.

In my benchmark cases, CPU is far from being exhausted 🤣

**Comment by skyzh** [comment]
> I'm thinking about buffering barriers generated by meta (while they might not have to wait until the last epoch finish to generate a new barrier).

But barrier won't be generated if checkpoint is not complete. We don't have barriers to steal!

**Comment by fuyufjh** [comment]
> In my benchmark cases, CPU is far from being exhausted 🤣

So the bottleneck is the IO to object storage? interesting 😇

**Comment by lmatz** [comment]
Can we just make `shared_buffer_uploader_tx` a Bounded Channel by bounding the actual size of the items being sent over the channel?
https://github.com/singularity-data/risingwave/blob/main/src/storage/src/hummock/local_version_manager.rs#L325

So at least the pressure on the storage gets pushed to the execution layer, which fits into the `natural negative feedback loop.`

**Comment by hzxa21** [comment]
> Can we just make `shared_buffer_uploader_tx` a Bounded Channel by bounding the actual size of the items being sent over the channel? https://github.com/singularity-data/risingwave/blob/main/src/storage/src/hummock/local_version_manager.rs#L325
> 
> So at least the pressure on the storage gets pushed to the execution layer, which fits into the `natural negative feedback loop.`

Is the shared buffer capacity not taking any effect? If sync to S3 is being slow, I think eventually the executor write_batch will hit the shared buffer capacity and write stall will happen, which trigger the  `natural negative feedback loop`

**Comment by lmatz** [comment]
> > Can we just make `shared_buffer_uploader_tx` a Bounded Channel by bounding the actual size of the items being sent over the channel? https://github.com/singularity-data/risingwave/blob/main/src/storage/src/hummock/local_version_manager.rs#L325
> > So at least the pressure on the storage gets pushed to the execution layer, which fits into the `natural negative feedback loop.`
> 
> https://github.com/singularity-data/risingwave/blob/94e22e59ce623e41e92e67ab1b920a25f2125d27/src/storage/src/hummock/local_version_manager.rs#L249
> 
> Is the shared buffer capacity not taking any effect? If sync to S3 is being slow, I think eventually the executor write_batch will hit the shared buffer capacity and write stall will happen, which trigger the `natural negative feedback loop`

You are right, I was just wondering why the source is not affected by this `natural negative feedback loop` and thought `write_batch` is not blocking.

**Comment by skyzh** [comment]
> Is the shared buffer capacity not taking any effect

If sync is already slow, write batch would be big, and the next epoch will be even bigger.

**Comment by skyzh** [comment]
So basically I'm thinking of two paths:

1. concurrent checkpoint with write_batch backpressure. Concurrent checkpoint ensures all epochs are of bound size, there won't be extra large write batches. Therefore, if checkpoint is slow, we can stall on write_batch. Also we should let write batch of lower epoch go first.
2. limit source throughput based on barrier received on source. This will have effect even when concurrent checkpoint is not implemented.

I'd go with 2 for now.

**Comment by hzxa21** [comment]
> > > Can we just make `shared_buffer_uploader_tx` a Bounded Channel by bounding the actual size of the items being sent over the channel? https://github.com/singularity-data/risingwave/blob/main/src/storage/src/hummock/local_version_manager.rs#L325
> > > So at least the pressure on the storage gets pushed to the execution layer, which fits into the `natural negative feedback loop.`
> > 
> > 
> > https://github.com/singularity-data/risingwave/blob/94e22e59ce623e41e92e67ab1b920a25f2125d27/src/storage/src/hummock/local_version_manager.rs#L249
> > 
> > Is the shared buffer capacity not taking any effect? If sync to S3 is being slow, I think eventually the executor write_batch will hit the shared buffer capacity and write stall will happen, which trigger the `natural negative feedback loop`
> 
> You are right, I was just wondering why the source is not affected by this `natural negative feedback loop` and thought `write_batch` is not blocking.

`write_batch` should be blocked when shared buffer reaches its capacity. But I think I know why the `natural negative feedback loop` is not triggered:

Executor only write_batch when receiving the barrier and without concurrent checkpoint, barrier is only injected when previous barrier's "sync to s3" completes. In this case, shared buffer will not reach its capacity since by the time the executor starts write_batch, batches of the previous epoch in shared buffer should have been uploaded and memory of shared buffer is freed.  The current mechnism can only stall writes when we have multiple executors in the same CN trying to write large states to storage.
