### ISSUE TITLE
perf: unbounded memory usage

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2673]
**Describe the bug**
<img width="727" alt="image" src="https://user-images.githubusercontent.com/4198311/169265637-af9d5596-bd62-476f-8e81-47097a447121.png">

When ingesting data into RisingWave without QPS limit, memory usage keeps growing.

**To Reproduce**
Run TPC-H bench.

**Expected behavior**
Memory usage should be limited.

**Additional context**

will update config and git hash later

**Comment by zwang28** [comment]
> config:
> 
> ```
> shared_buffer_threshold = 268435456
> sstable_size = 268435456
> block_size = 4096
> bloom_false_positive = 0.1
> data_directory = "hummock_001"
> async_checkpoint_enabled = true
> block_cache_capacity = 268435456
> meta_cache_capacity = 67108864
> ```
> 
> I'll double check tomorrow and run some benchmarks on latest main...

I guess it's due to "almost unlimited" block cache size: https://github.com/singularity-data/risingwave/issues/2578#issuecomment-1128874077

**Comment by skyzh** [comment]
Oh, that's true. I forgot this again 🤣 Let me check this and revert the config change tommorrow.

**Comment by skyzh** [comment]
block_cache_capacity is actually the memory usage instead of entry cnt, so it's 256MB here indeed. I'll bench again later with latest main 😇
