### ISSUE TITLE
frontend: move DeltaJoin related logics to frontend

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2688]
# Delta Join on Frontend

## Background

Previously, we have implemented two types of delta join planning.

* Arrange on-the-fly. If we want to use delta join for an existing hash join, we will rewrite HashJoin into delta join fragments on meta.
* By index. If indices are created for join sides, we will create an `IndexDeltaJoin` pseudo plan node, and rewrite it on fragmenter.

This approach poses a lot of problems for us.

* Meta need to know so much about the plan node. e.g., distribution, things inside hash join, meta will need to understand them to create a delta join plan.
* Hard to do extensions. Currently, there's no way of pushing down filters down into lookups.
* Manually reorder columns in `LookupExecutor`, which should be done by projection instead.
* Too many pseudo plan nodes. Making proto hard to understand.

Therefore, I'd like to unify the design and integrate the whole process into the frontend.

## Design

**Lookup Plan Node**

The lookup plan node will now be part of the optimizer plan node. It has two children: where one side must be `IndexScan`.

**Delta Join Rule**

The join rule is applied after `MultiJoinJoinRule` and before `ReorderMultiJoinRule`.

Delta Join rule will check if all indices are available for LogicalMultiJoin. If yes, it will immediately convert it to a delta join plan using delta join solver (in fact it's quite similar to join reordering). The plan will be like:

```
LogicalLookupUnion
  LogicalLookup
    LogicalIndexScan A
    LogicalLookup
      LogicalIndexScan B
      LogicalIndexScan C
  LogicalLookup
    LogicalIndexScan C
    LogicalLookup
      LogicalIndexScan A
      LogicalIndexScan B
  LogicalLookup
    LogicalIndexScan C
    LogicalLookup
      LogicalIndexScan B
      LogicalIndexScan A
```

... for 3-way joins, and

```
LogicalLookupUnion
  LogicalLookup
    LogicalIndexScan A
    LogicalIndexScan B
  LogicalLookup
    LogicalIndexScan B
    LogicalIndexScan A
```

... for 2-way joins.

After that, we can easily apply filter push-down and column reordering / column prune.

Note that this rule will only be enabled for streaming plans. We have two ways of implementing this: expose an `is_streaming` flag in optimizer to enable this specific rule, or just panic if `LogicalLookup` is produced for batch plans.

**Code Cleanup**

We should then disallow create arrangement on-the-fly, and remove delta join tests. We should add e2e tests for TPC-H with indices.

We can remove a lot of pseudo plan nodes, like Arrange, IndexDeltaJoin, and `is_delta` in HashJoin.

## Future Optimizations

* use rearranged chain for indices
* other optimizations in https://github.com/singularity-data/risingwave/issues/2016
* eliminate duplicated StreamIndexScans by broadcasting (will also be useful in CTEs)

**Comment by st1page** [comment]
will the "Lookup Plan Node" be a streaming node or logical node? I propose to make it as a stream node and implement the "Delta Join Rule" at the LogicalMultiJoin::to_stream.

`

**Comment by skyzh** [comment]
Can we do predicate push-down on stream plan nodes? Also, `to_stream` operates on a single plan node, while this rule will rewrite the whole children plan nodes.

If all above issues are solved, this looks like a good solution.

**Comment by skyzh** [comment]
... and of course, we can introduce yet another `adhoc_multi_way_join_to_stream`

**Comment by st1page** [comment]
I am not sure if the predicate pushdown is same with batch plan in multijoin to delta join transformation.

**Comment by skyzh** [comment]
The transformation process is like:

* We use delta join solver to create n join paths.
* We clone the original MultiJoin for n times, and reorder it using each path from solver, while having a filter on each path of predicates.
* We union the n paths using lookup union.

Then we do push down as normal.

**Comment by skyzh** [comment]
Maybe I need to elaborate my expected planning process in detail:

Firstly, we have a MultiJoin:

```
MultiJoin <condition>
  TableScan
  TableScan
  TableScan
```

Then, we find that all equal conditions have index. So we use delta join solver to get 3 lookup paths. For example, it tells us 3 paths: [[a, b, c], [b, a, c], [c, b, a]].

So we construct 3 multi join nodes by reordering the current one: MultiJoin a, b, c; MultiJoin b, a, c, MultiJoin c, b, a. Now we directly convert MultiJoin into DeltaJoin. For example, for the first path,

```
Filter <condition>
  Lookup
    IndexScan c
    Lookup
      IndexScan b
      IndexScan a
```

Then, union 3 paths:

```
LookupUnion
  Filter
    <lookups>
  Filter
    <lookups>
  Filter
    <lookups>
```

And finally, do the push-down as normal.

**Comment by xxchan** [comment]
close as tracked
