### ISSUE TITLE
Making connectors interface more friendly

### ISSUE THREAD

**Issue by shanicky** [singularity-data/risingwave#2696]
Currently, we use the connector crate to encapsulate external systems such as MQ/S3 to limit the coupling of the code as much as possible, which requires some work to make the interface connector crate more friendly to the community developers. 

- [x] #2697
- [ ] Refactoring `From<SplitImpl> for ConnectorState` cc @tabVersion 
- [x] #2720
- [ ] Update documents for connector development
- [x] #2698

**Comment by pangzhenzhou** [comment]
The connector of RisingWave has several design changes. We need to describe the purpose of this design and how it allows developers to get familiar with it faster. CC @tabVersion @fuyufjh @TennyZhuang @twocode @neverchanje
