### ISSUE TITLE
Discussion: Should the connector know the columns?

### ISSUE THREAD

**Issue by shanicky** [singularity-data/risingwave#2698]
The previous idea about the connector was to encapsulate all the external code inside the connector crate, which is only responsible for the corresponding io behavior, thus producing a unified message structure to the source crate to parse and generate a `StreamChunk` for the source executor. So the previous setting is that the schema information of the source is only provided in the source crate, which is sufficient for most connectors such as pulsar/kafka.

But when we implement the datagen connector, we need to generate the corresponding messages according to the schema, which requires sinking the schema information to the connector crate, the current practice is to provide a `Vec<Column>` but whether this is a permanent setting we need to discuss

**Comment by liurenjie1024** [comment]
Please describe problem in more detail?

**Comment by shanicky** [comment]
> Please describe problem in more detail?

Added, sorry for the delay

**Comment by shanicky** [comment]
> 1. I think passing schema to connector is good practice, this will be useful for file sink with schemas, for example parquet file.
> 2. The `Vec<Column>` seems like a simplified version of `Schema`, why not use `Schema` in common crate?

1. Sounds so reasonable
2. Because the column provided when we create a source may not correspond to the column when we create the materialized view, we may need to use `column_ids` for a projection, but the `Vec<Field>` in the `Schema` does not have column_id, but Vec<ColumnDesc> looks like it can be
