### ISSUE TITLE
optimizer: prioritize picking tables of same distribution on multi-way join

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2710]
Currently, the heuristic ordering of join only consider eq conditions.

https://github.com/singularity-data/risingwave/blob/23e4c1cd5e435ca61de889f31f63827882d93468/src/frontend/src/optimizer/plan_node/logical_multi_join.rs#L171-L250

Consider the following case:

```
select * from a, b, c, d where a.v1 = b.v1 and a.v1 = c.v1 and a.v2 = d.v2
```

In this case, the two orders can all be without nested loop join:

* ((a join b) join c) join d
* ((a join b) join d) join c

However, the second one will introduce 1 more shuffle, as `a join b`'s distribution is not the same as `d.v2`, and when joining c, we need to shuffle back to follow `c.v1`'s distribution. The first one only need to shuffle once at `join d`.

We can make this part of the join reordering heuristics. Also this heuristics has already been considered in delta join solver.

**Comment by fuyufjh** [comment]
Join reordering happens in logical optimization, so distribution is not available yet. A more accurate description of this requirement may be:

Let the 1-1 joins **with same join keys** be aside of each others. e.g. for `a.v1 = b.v1 and a.v1 = c.v1`, tables `a,b,c` should be put together, so the order `a, b, c, d` is better than the order  `a, b, d, c`

**Comment by skyzh** [comment]
> Join reordering happens in logical optimization, so distribution is not available yet. A more accurate description of this requirement may be:
> 
> Let the 1-1 joins **with same join keys** be aside of each others. e.g. for `a.v1 = b.v1 and a.v1 = c.v1`, tables `a,b,c` should be put together, so the order `a, b, c, d` is better than the order `a, b, d, c`

That's more accurate, thanks! 🤪

**Comment by Graphcalibur** [comment]
One idea I had to do this heuristic was to go through the join edges in BFS order (though DFS should also work). That way, edges that share a node with a previous edge will be joined first before other edges. Thoughts?

**Comment by fuyufjh** [comment]
Yes. We are using a similar approach:

https://github.com/singularity-data/risingwave/blob/753fd97a9895742a24bf7e3be9de25e58896712c/src/frontend/src/optimizer/plan_node/logical_multi_join.rs#L308-L327

**Comment by fuyufjh** [comment]
Close this issue. Please re-open it if need further improvement,
