### ISSUE TITLE
optimizer: multi join rule should absorb filter

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2711]
Otherwise some joins won't be merged together in this phase? We should have a stage to pull-up filters (or simply let multi join to absorb these filters into the condition). Otherwise some joins might not be processed by multi join rule.

e.g. if some queries generate plans like this before multi join stage:

```
Join
  Filter
    Join
      TableScan
      TableScan
  TableScan
```

The MultiJoin rule won't be able to reorder these two joins.

**Comment by jon-chuang** [comment]
I believe the predicate pushdown rule ought to already push down the filter into the join condition?

Can add a regression test.
