### ISSUE TITLE
storage: meta cache always miss when meta file is too large

### ISSUE THREAD

**Issue by Little-Wallace** [singularity-data/risingwave#2713]
## Problem
<img width="723" alt="image (1)" src="https://user-images.githubusercontent.com/16376959/169651537-a118c22e-3c5d-4009-b9b1-20f4dff277dd.png">

we find that the barrier latency of tpch q13 is too high (more than 20 seconds), and the throughput of object storage is very large.

## Root Cause
We split meta cache to 32 shards. And the default cache size of meta is only 64MB. It means that every shard could only hold a 2MB cache pool. If some meta block is more than 2MB, it may be evict after another small block inserted into.

**Additional context**

It seems that the compactor produced a large  file in L6 (more than 400MB), so its meta file is also very large, which is more than 5MB

**Comment by wenym1** [comment]
Why would some meta files be too large? I think we have an estimated block size and sst size upper limit

**Comment by Little-Wallace** [comment]
It seems another bug and I will investigate it later....
But meta-cache can not assume that the meta block must less than 1MB or smaller size.

**Comment by Little-Wallace** [comment]
@wenym1 It seems to be a mistake caused by metrics algorithm. I can not understand....

**Comment by Little-Wallace** [comment]
> Why would some meta files be too large? I think we have an estimated block size and sst size upper limit

fixed in https://github.com/singularity-data/risingwave/pull/2722/commits/7f8692326bff27690e6459d4ccc7c127524acc54
