### ISSUE TITLE
compactor occupies all threads in `risedev d`

### ISSUE THREAD

**Issue by hzxa21** [singularity-data/risingwave#2725]
**Describe the bug**
When running e2e with short barrier interval on a cluster started with `risedev d`, `wait_epoch` and `heartbeat` time out. 

`risedev d` will not start separate compactor nodes and compactor is embeded in compute nodes. The issue is most likely to caused by compactor occupying all threads in the compute node after #2591 since I saw long running compactor tasks with many splits.

**To Reproduce**
git commit: `3a22be299fd326065577d0ee31a90f5ee1b8113c`

1. Change the barrier interval to 30ms.
2. `risedev d`
3. `./risedev slt -p 4566 "./e2e_test/v2/streaming_delta_join/*.slt"` and `./risedev slt -p 4566 "./e2e_test/v2/streaming/*.slt"`
4. Check the logs:
```
risingwave_rpc_client::meta_client: Failed to send_heartbeat: timeout deadline has elapsed
risingwave_storage::monitor::monitored_store: Failed in wait_epoch: Hummock error: Wait epoch error timeout
```

**Expected behavior**
Compactor should not occupies all threads when it is embeded in compute node and timeout should not happen.

**Additional context**
[frontend-4566.log](https://github.com/singularity-data/risingwave/files/8750833/frontend-4566.log)
[meta-node-5690.log](https://github.com/singularity-data/risingwave/files/8750834/meta-node-5690.log)
[risedev.log](https://github.com/singularity-data/risingwave/files/8750835/risedev.log)
[compute-node-5688.log](https://github.com/singularity-data/risingwave/files/8750836/compute-node-5688.log)

**Comment by hzxa21** [comment]
@xxhZs found out the timeout issue when implementing concurrent checkpoint and realized that this issue also happened on main. 

I was able to reproduce the heartbeat timeout but not the wait_epoch timeout.

**Comment by hzxa21** [comment]
cc @zwang28

**Comment by zwang28** [comment]
Note that the issue doesn't only occur in embedded compactor scenario. `compact_shared_buffer` may encounter the same issue, when many splits can spawn many tasks.

[Yielding compaction](https://github.com/singularity-data/risingwave/commit/8b52d0d691fd05a622292c227c9e9795255c2b1e) more frequently can fix this issue (reproduced and tested). The downside of this approach is a compaction may take more time, due to scheduling overhead. Though it's not measured accurately yet.

What do you think?

**Comment by skyzh** [comment]
This commit https://github.com/singularity-data/risingwave/commit/8b52d0d691fd05a622292c227c9e9795255c2b1e might bring significant overhead, as we yield every time we add a new key. I would prefer to yield on block switch. For example, we can modify TableIterator to have a parameter "yield_on_block". Every time we seek to a new block in TableIterator, we force a yield.

**Comment by skyzh** [comment]
Maybe related to this issue: https://github.com/singularity-data/risingwave/pull/2630

**Comment by hzxa21** [comment]
> `compact_and_build_sst` only yield on block miss. So we'll have at most (#compaction_tasks x #splits) tokio tasks that seldom yields.
> 
> Note that the issue doesn't only occur in embedded compactor scenario. `compact_shared_buffer` may encounter the same issue, when many splits can spawn many tasks.
> 
> [Yielding compaction](https://github.com/singularity-data/risingwave/commit/8b52d0d691fd05a622292c227c9e9795255c2b1e) more frequently can fix this issue (reproduced and tested). The downside of this approach is a compaction may take more time, due to scheduling overhead. Though it's not measured accurately yet.
> 
> What do you think?

Ideally, I think we need a separate thread pool for compaction task instead of mixing the compactor threads, actor threads, I/O threads to avoid doing the yielding tricks.

**Comment by zwang28** [comment]
> Ideally, I think we need a separate thread pool for compaction task instead of mixing the compactor threads, actor threads, I/O threads to avoid doing the yielding tricks.

What about putting crucial tasks in separate thread pool, e.g. pin_version, send_heartbeat?

**Comment by skyzh** [comment]
> What about putting crucial tasks in separate threads

I guess it won't be easy. Maybe we can consider having multiple tokio runtimes and investigate it a little bit now?

**Comment by hzxa21** [comment]
cc @wangrunji0408 expert on tokio runtime and scheduler
