### ISSUE TITLE
optimizer: merge `LogicalProject` into `LogicalMultiJoin`

### ISSUE THREAD

**Issue by jon-chuang** [singularity-data/risingwave#2728]
Steps:
We first assume that a filter pushdown has been performed. This ensures that filters that are isolated to a subtree will already be in that subtree when we try to perform the merge.

Merging phase:
1. `LogicalMultiJoin` now has a projection as the top level node. So, morally, it looks like `Proj -> Filter -> [Inputs]`
2. When merging two logical multijoins, the projections on either side need to be pulled up through the join condition, and merged into the new projection. If the join condition references a non-simple projection expression, do not pull the projection up, and let the input remain as an atomic input to the multijoin. This means that input is now in a self-contained join subtree.
3. When merging a filter into a multijoin, push down the filter below the projection.
4. When merging a projection into a multijoin, merge the projection with the multijoin projection.
5. When issuing a left_deep_ordering, merge the reordering into the top-level projection.

Unoptimal cases:
1. Example: A join subtree is created due to the presence of a filter condition involving a non-simple expression. A relation in that join subtree could have acted as an edge in the eq join graph of the entire join tree but may not have an edge in the subtree. This causes an unnecessary crossjoin within the subtree. We will ignore optimizing such cases for now. In theory, one could find a better ordering by performing constrained optimization over the entire join tree, where the constraint is that certain subsets of relations need to be joined in a particular order (there is a partial order required on the join ordering).

Tracking issue: https://github.com/singularity-data/risingwave/issues/2530

**Comment by skyzh** [comment]
I think that will be handled by output index. In the future, logical plan won't have projection solely for reordering column.

Tracking issue: https://github.com/singularity-data/risingwave/issues/1922

MultiJoin in the future should also support output_index. 🤣

**Comment by skyzh** [comment]
Despite the most common case of projection (column reordering), maybe "join condition references a non-simple projection expression" will need special handling described as in this issue?

**Comment by jon-chuang** [comment]
Yes, I think maybe I'll just ignore projections with non-simple expressions for now, and leave the handling of reorderings to the output index of multijoins.

**Comment by st1page** [comment]
closed with #3351
