### ISSUE TITLE
Support subquery as time window input

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#2733]
Currently, only a table/source/mview can be used as the input of time window function.

There is no reason that disallows a subquery here.

```sql
SELECT TUMBLE((SELECT a FROM t1) t2, interval '5' minute)
```

**Comment by xiangjinwu** [comment]
Alternative is to use CTE #2708: `WITH t2 AS (SELECT a FROM t1) SELECT * FROM TUMBLE(t2, interval '5' minute)` if it is challenging to support this in parser ast.

**Comment by TennyZhuang** [comment]
> Alternative is to use CTE #2708: `WITH t2 AS (SELECT a FROM t1) SELECT * FROM TUMBLE(t2, interval '5' minute)` if it is challenging to support this in parser ast.

Looks good
