### ISSUE TITLE
support database-level isolation

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#2742]
**Is your feature request related to a problem? Please describe.**

Currently, tables in databases are not isolated.

```
$ psql -h localhost -p 4566 db1
psql (14.2, server 9.5.0)
Type "help" for help.

db1=> show tables;
   Name
----------
 region
 nation
 part
 orders
 lineitem
 customer
 supplier
 partsupp
(8 rows)


$ psql -h localhost -p 4566 db2
psql (14.2, server 9.5.0)
Type "help" for help.

db2=> show tables;
   Name
----------
 region
 nation
 part
 orders
 lineitem
 customer
 supplier
 partsupp
(8 rows)
```

**Describe the solution you'd like**

Every database should act like an isolated instance - objects like tables and indexes should be isolated between databases.

Also, please check Postgres for detailed behaviors.

**Describe alternatives you've considered**

**Additional context**

**Comment by hzxa21** [comment]
Related issue #2529
