### ISSUE TITLE
batch: `RowId` of empty set in hash join is incorrect everywhere

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#2749]
**Describe the bug**

In batch hash join, @liurenjie1024 introduced a struct `RowId { chunk_id, index }` to represent one record in `ChunkedData`, but the default value `{0, 0}` is invalid while there is no chunk in `ChunkedData`.

Many places assume that the RowID is always valid, and all of them will panic on an empty set.

**To Reproduce**

```
dev=> create table t1 (v1 int, v2 int);
CREATE_TABLE
dev=> create table t2 (v1 int, v2 int);
CREATE_TABLE
dev=> insert into t1 values (1,1);
INSERT 0 1
dev=> select * from t1 full outer join t2 on t1.v1 = t2.v1;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**Expected behavior**
Don't panic

**Additional context**
May also cause #2690

**Comment by yuhao-su** [comment]
`cur_remaining_build_row_id` is incorrectly set as default when initializing.

**Comment by liurenjie1024** [comment]
I think this is misuse of `RowId`. The data chunk should not be empty.

**Comment by TennyZhuang** [comment]
> I think this is misuse of `RowId`. The data chunk should not be empty.

Data chunk is not empty, but ChunkedData can have 0 chunks. In fact this is an empty set so you cannot avoid either allow empty chunk or allow empty ChunkedData, and 0,0 will always be invalid.
