### ISSUE TITLE
batch: Implement lookup join.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#2754]
- [x] #3685
- [x] #3686
- [x] #3687
- [x] #3801
- [x] #3769
- [x] #3822

**Comment by fuyufjh** [comment]
The RPC endpoint on compute note to execute fragments under local execution mode should be completed before this.

**Comment by liurenjie1024** [comment]
Yes, but I think @yuhao-su should give a design first?

**Comment by yuhao-su** [comment]
> Yes, but I think @yuhao-su should give a design first?

Sure, I'll write a doc.
