### ISSUE TITLE
bug: missing update on dependent tables' downstream actor info when finish MoM

### ISSUE THREAD

**Issue by yezizp2012** [singularity-data/risingwave#2762]
Previously when create MoM, its dependent tables' downstream actor info will be updated when finished, see [#1041](https://github.com/singularity-data/risingwave/pull/1041/files). But after some refactor on fragmenter, the `table_sink_map` is left without fill. This will cause recovery process hanging on finished collection, since the dispatcher between them will not be created automatically.

**Comment by neverchanje** [comment]
Is this bug related to #2759 ?

**Comment by yezizp2012** [comment]
> Is this bug related to #2759 ?

Unfortunately not 😭.

**Comment by neverchanje** [comment]
Okok hopefully you can elaborate some steps to reproduce this bug.
