### ISSUE TITLE
bug: panic on improper column usage in FROM

### ISSUE THREAD

**Issue by xiangjinwu** [singularity-data/risingwave#2771]
**Describe the bug**
Follow the repro steps below, and the frontend panics.

**To Reproduce**
```
create table a(a1 int);
create table b(b1 int);
create table c(c1 int);
explain select * from a, b join c on a1 + b1 = c1;
```

**Expected behavior**
Display an error on psql client: `column "a1" does not exist`

**Additional context**
When resolving `on` condition of `join c`, columns of `a` should not be in bind context.

**Comment by kwannoel** [comment]
I think it's just been resolved by #3788

```sql
dev=> create table a(a1 int);
CREATE_TABLE
dev=> create table b(b1 int);
CREATE_TABLE
dev=> create table c(c1 int);
CREATE_TABLE
dev=> explain select * from a, b join c on a1 + b1 = c1;
ERROR:  QueryError: Item not found: Invalid column: a1.
dev=> \q
```

cc @jon-chuang
