### ISSUE TITLE
frontend: Store sql in current execution context for better debugging.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#2777]
**Is your feature request related to a problem? Please describe.**

Currently after parsing, our raw sql is discarded. This make printing debugging information including sql impossible. 

**Describe the solution you'd like**

Store raw sql, in current execution context or session to so that following debugging will be easier.

**Describe alternatives you've considered**

No.

**Additional context**
No.

**Comment by nhzaci** [comment]
Hi, I would like to take this on, are there some useful places for me to start digging into to get into this task?

**Comment by lmatz** [comment]
> Hi, I would like to take this on, are there some useful places for me to start digging into to get into this task?

https://github.com/singularity-data/risingwave/blob/main/src/frontend/src/handler/query.rs#L148
could be a starting point.
