### ISSUE TITLE
Implement SPLIT_PART() function

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#2791]
**Purpose**
As part of the effort to support most commonly used functions in RisingWave, we want to implement the SPLIT_PART() function. We expect the function to work in the same way as in PostgreSQL. It splits a string on a specified delimiter and returns the nth substring.

**Example**
The statement below should return 'B'. 
SELECT SPLIT_PART('A,B,C', ',', 2); 

**Reference**
- https://www.postgresql.org/docs/14/functions-string.html
- https://www.postgresqltutorial.com/postgresql-string-functions/postgresql-split_part/

**Comment by hengm3467** [comment]
**Purpose**: As part of the effort to support most commonly used functions in RisingWave, we want to implement the SPLIT_PART() function. We expect the function to work in the same way as in PostgreSQL. It splits a string on a specified delimiter and returns the nth substring.

**Example**
The statement below should return 'B'. 
SELECT SPLIT_PART('A,B,C', ',', 2); 

**Reference**:
- https://www.postgresql.org/docs/9.1/functions-string.html
- https://www.postgresqltutorial.com/postgresql-string-functions/postgresql-split_part/

**Comment by alissa-tung** [comment]
> Moved the description to the top-most comment.

it would be nice to use the current version of docs.
wondering if there is someone who is willing to review the linked merge request

**Comment by hengm3467** [comment]
> > Moved the description to the top-most comment.
> 
> it would be nice to use the current version of docs. wondering if there is someone who is willing to review the linked merge request

Updated the doc link to point to the current version of PG (v14).

As for the reviewer, I think you can request @xiangjinwu to review your pull request.

**Comment by alissa-tung** [comment]
> > > Moved the description to the top-most comment.
> > 
> > 
> > it would be nice to use the current version of docs. wondering if there is someone who is willing to review the linked merge request
> 
> Updated the doc link to point to the current version of PG (v14).
> 
> As for the reviewer, I think you can request @xiangjinwu to review your pull request.

thx
