### ISSUE TITLE
Do we really need the `Buffer` adapted from arrow-rs?

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#2828]
The `Buffer` is currently only used by `Bitmap`, and it seems to be implemented exactly the same with `Vec<u8>`. If we gonna replace it with `Vec`, then some unsafe code under [src/common/src/alloc.rs](https://github.com/singularity-data/risingwave/blob/e6dd2bf50ee106b39b3d188d48eb69acdd878e7c/src/common/src/alloc.rs) can also be pruned.

cc @skyzh @liurenjie1024

**Comment by liurenjie1024** [comment]
Lgtm
