### ISSUE TITLE
Remove ManagedMViewState

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#2836]
So far I see no usage on ManagedMViewState. Maybe due to some dependency issue this is struct is not currently removed. We should resolve those issues and eventually delete ManagedMViewState.

**Comment by wcy-fdu** [comment]
Since flush status is still used by some executor, ManagedMViewState can not be removed now.
 
![image](https://user-images.githubusercontent.com/58715567/170461887-fa3491b5-c4ad-4fda-974f-83cff2c49c86.png)
