### ISSUE TITLE
run ./risedev d  error :note: collect2: fatal error: cannot find 'ld' compilation terminated.

### ISSUE THREAD

**Issue by databodys** [singularity-data/risingwave#2843]
**Describe the bug**
 run ./risedev d
 = note: collect2: fatal error: cannot find 'ld'
          compilation terminated.
error: could not compile `memchr` due to previous error
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit status: 1
e-ld=lld"
  = note: collect2: fatal error: cannot find 'ld'
          compilation terminated.
error: could not compile `syn` due to previous error
error: linking with `cc` failed: exit status: 1
  = note: collect2: fatal error: cannot find 'ld'
          compilation terminated.
error: could not compile `libc` due to previous error
error: linking with `cc` failed: exit status: 1

**To Reproduce**
Steps to reproduce the behavior.
1、install a min unbutn22.1 OS
2、mkdir  /home/xxx/ risingwave
3、cd /home/xxx/ risingwave
4、curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
5、git clone https://github.com/singularity-data/risingwave.git && cd risingwave
6、./risedev d
ps：
   /bin/ld -->/usr/bin/ld.bfd*
   /usr/bin/ld-->/usr/bin/ld.bfd*
   /usr/bin/ld.bfd -> x86_64-linux-gnu-ld.bfd*

**Comment by skyzh** [comment]
What’s the git hash you are using?

**Comment by BugenZhao** [comment]
Have you installed the dependencies mentioned here? https://github.com/singularity-data/risingwave/blob/main/docs/developer-guide.md#set-up-the-development-environment

**Comment by skyzh** [comment]
I guess you didn't install `lld`. Feel free to reopen if you met any further issues.

**Comment by databodys** [comment]
@skyzh  You are right, when I installed lld, the compilation was successful，Thanks to everyone who helped and paid attention to this issue！
