### ISSUE TITLE
Null element in the column will crash when query with order by and limit;

### ISSUE THREAD

**Issue by D2Lark** [singularity-data/risingwave#2858]
**Describe the bug**
when I type select * from t order by v1 limit 4, because there is a Null element in v1, RW return a error

**To Reproduce**
create table t (v1 int);
insert into t values (1),(2),(3),(null);
select * from t order by v1;
result is ok
select * from t order by v1 limit 4;
ERROR:  internal error: error reading a body from connection: broken pipe
**Expected behavior**

Null
1
2
3

**Additional context**

**Comment by xiangjinwu** [comment]
This has been fixed in the main branch: #2826
