### ISSUE TITLE
this project is brilliant,but it seems that I can install it in only one host instead of the distrubuted system according to the guide of installation

### ISSUE THREAD

**Issue by csuXinda** [singularity-data/risingwave#2863]
this project is brilliant,but it seems that I can install it in only one host instead of the distrubuted system according to the guide of installation

_Originally posted by @csuXinda in https://github.com/singularity-data/risingwave/discussions/2848_

**Comment by skyzh** [comment]
dup w/ https://github.com/singularity-data/risingwave/discussions/2848
