### ISSUE TITLE
ci: migrate to new CI pipeline

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2898]
- [x] deprecate old pipeline
- [x] migrate docker build pipeline
~~- [ ] migrate dashboard build and test~~
- [x] release workflow
- [x] upload failure logs
- [x] enable swapfile
- [x] cargo CI cache
- [x] build CI docker image automatically
- [ ] support x86 / aarch64 matrix on main branch
- [ ] assign different EC2 for each tests, for example, e2e test only needs a 8c16g EC2
- [x] enable spot instance

**Comment by skyzh** [comment]
cc @huangjw806 would you like to have a try? Most of the tasks are not very urgent, and we can migrate little by little. I'll deprecate the migrated pipeline this Friday if everything goes fine.

**Comment by huangjw806** [comment]
ok, I try to complete the above points step by step.

**Comment by skyzh** [comment]
note that docker build workflows can be done by mount host docker socket to the docker container itself. But I'm not sure whether this would introduce some security issues.

```
-v /var/run/docker.sock:/var/run/docker.sock
```

**Comment by skyzh** [comment]
release workflow: https://github.com/singularity-data/risingwave/issues/2972
