### ISSUE TITLE
storage: high read latency in streaming hash joins

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2901]
range scan now has ~20ms avg latency, guess it's caused by meta cache miss, which is because of frequent compaction.

<img width="1434" alt="image (1)" src="https://user-images.githubusercontent.com/4198311/170934781-2b52364d-0cc2-4554-8018-aa2074b58c7e.png">

**Comment by twocode** [comment]
I looked at this a while ago. It looks like to be cache penetrated (there should be a cache miss rate chart along side). I think sequential prefetching would help with this.
