### ISSUE TITLE
storage: Cleanup states for dropped TABLEs/MVs

### ISSUE THREAD

**Issue by hzxa21** [singularity-data/risingwave#2908]
We already support `DROP TABLE` and `DROP MATERIALIZED VIEW` in frontent and meta but the data belonging to dropped tables/mvs  still remain on storage occupying storage spaces and participating in compaction.

We should support state cleanup for dropped TABLEs/MVs. One feasible solution is to delete states via a compaction filter.

Related issues:
#191
#201
#1153 
#1212
#1272

**Comment by hzxa21** [comment]
> We already support `DROP TABLE` and `DROP MATERIALIZED VIEW` in frontent and meta but the data belonging to dropped tables/mvs still remain on storage occupying storage spaces and participating in compaction.
> 
> We should support state cleanup for dropped TABLEs/MVs. One feasible solution is to delete states via a compaction filter.
> 
> Related issues: #191 #201 #1153 #1212 #1272

**Comment by neverchanje** [comment]
I used to think that we rely on background compaction (vacuum) to remove the data because the table is basically a prefix on large shared storage, right? So we can not drop the files immediately after dropping the table.

**Comment by hzxa21** [comment]
> I used to think that we rely on background compaction (vacuum) to remove the data because the table is basically a prefix on large shared storage, right? So we can not drop the files immediately after dropping the table.

Right. Data of dropped table/mv should be invisible to user immeidately but should be cleaned up asynchorously via background compaction.

**Comment by twocode** [comment]
@mikechesterwang This looks like to be one of your requirements.

**Comment by TennyZhuang** [comment]
BTW different MVs may share the same arrangement, so the real drop happens on the arrangement.

**Comment by skyzh** [comment]
Streaming and Meta part:

- [ ] Change all node to use table id as prefix, remove executor and shared prefix
- [ ] Record table id belonging to a MV on meta (optional)
- [ ] Record drop prefix on drop MV / drop table / drop index
- [ ] Implement drop prefix compaction filter

**Comment by hzxa21** [comment]
#3038 resolves this issue.
