### ISSUE TITLE
RFC: extend CREATE TABLE syntax to support creating append-only table source

### ISSUE THREAD

**Issue by StrikeW** [singularity-data/risingwave#2962]
# RFC: extend CREATE TABLE syntax to support creating append-only table source

To support append-only table source use case and facilitate the e2e test of append-only data stream.

## Background

Currently we don't support creating an append-only table source, and to support this use case we need to extend the CREATE TABLE syntax.

## Design
The idea is to put the append-only attribute to the **_storage_parameter_** part in the WITH clause, which is consistent to CREATE SOURCE syntax.
For example, the SQL to create an append-only table named _orders_:

```
CREATE TABLE orders (
        o_orderkey BIGINT,
        o_custkey INTEGER,
        o_orderstatus VARCHAR(1),
        o_totalprice NUMERIC,
        o_orderdate DATE,
        o_orderpriority VARCHAR(15),
        o_clerk VARCHAR(15),
        o_shippriority INTEGER,
        o_comment VARCHAR(79))
        WITH (
         'appendonly'=true
        )
```
The append-only attribute will be stored in the corresponding struct in catalog. And the stream plan for MVs created on top of this table should be append-only true.

**Comment by fuyufjh** [comment]
+1 for this. It's similar to our `create source` syntax. Besides, [Greenplum](https://gpdb.docs.pivotal.io/5280/ref_guide/sql_commands/CREATE_TABLE_AS.html) uses a similar syntax.
