### ISSUE TITLE
metrics: fragment -> fragment and worker node -> worker node exchange throughput

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2986]
Currently, we have actor -> actor throughput. However, when parallelism gets very high, the metrics could be hard to be stored and analyzed. Therefore, it's better to have a fragment-level or worker node level exchange info.

**Comment by skyzh** [comment]
cc @StrikeW do you have interest in implementing this? 🤣

**Comment by StrikeW** [comment]
I think this can be a good first issue.☺️

**Comment by skyzh** [comment]
That's cool 🤤
