### ISSUE TITLE
2-phase agg for stream agg

### ISSUE THREAD

**Issue by kwannoel** [singularity-data/risingwave#2997]
related: https://github.com/singularity-data/risingwave/pull/2746/files

**Comment by kwannoel** [comment]
cc @fuyufjh

**Comment by fuyufjh** [comment]
FYI. It may be difficult to do LocalAgg for (non append-only) min/max, because the state of min/max of each group is a table instead of a single value, and the table has to be maintained in the LocalAgg side. We have not decided how to store these states.

Thus, please start from other aggregate function except (non append-only) min/max; and if there is an min/max in user's query, we may just skip it and simply use 1-phase aggregation for that.

**Comment by BowenXiao1999** [comment]
I have a question: How you persist 2-phase agg store data in relational table? 

For simple agg + not append only query + value state cases, the state is just a value, so the pk (note this is pk of relational table) should be empty vector and same for order types (Note: order types len should always = pk length). 

 [This Design](https://singularity-data.quip.com/LNrsAXTEhAtM/Proposal-Make-LocalAgg-Great-Again) local agg do not persist data in relational table, so it do not need to consider this question. So in new design, if you want to write state table for each local agg, we should have a shard-key as pk to avoid multi-write...

I may need more time to catch up the new design

**Comment by kwannoel** [comment]
> I have a question: How you write local data in relational table?
> 
> For simple agg + not append only query + value state cases, the state is just a value, so the pk (note this is pk of relational table) should be empty vector and same for order types (Note: order types len should always = pk length).
> 
> [This Design](https://singularity-data.quip.com/LNrsAXTEhAtM/Proposal-Make-LocalAgg-Great-Again) local agg do not persist data in relational table, so it do not need to consider this question. So in new design, if you want to write state table for each local agg, we should have a shard-key as pk to avoid multi-write...
> 
> I may need more time to catch up the new design

Will be writing up a doc to go over implementation design in greater detail. Will update soon.

**Comment by kwannoel** [comment]
> Will be writing up a doc to go over implementation design in greater detail. Will update soon.
https://singularity-data.quip.com/81m6AvnMIYgS/Design-2-Phase-Stream-Aggregation-Implementation
