### ISSUE TITLE
bug: clients can connect to inexistent database

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#3001]
**Describe the bug**

```
$ psql -h localhost -p 4566 dev
psql (14.2, server 9.5.0)
Type "help" for help.

dev=> \c xxx
psql (14.2, server 9.5.0)
You are now connected to database "xxx" as user "eric".
xxx=> \c yyy
psql (14.2, server 9.5.0)
You are now connected to database "yyy" as user "eric".
yyy=>
```

**To Reproduce**

See above

**Expected behavior**

Should raise an error: `database "xxx" does not exist`

```
$ psql -h localhost -p 5432 xxx
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "xxx" does not exist
```

**Additional context**

related #2751

**Comment by skyzh** [comment]
I think that's a feature instead 🤣 Currently, we don't need to specify database on psql. So psql will always connect using the current user's username. If we fix this issue, all user-facing docs need to be changed.
