### ISSUE TITLE
batch: use bounded channels for batch channels

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3024]
Otherwise it will easily OOM

**Comment by liurenjie1024** [comment]
I'll take a look at it.

**Comment by BowenXiao1999** [comment]
In what kind of scenario we should prefer unbounded? Never? 

BTW, We also use unbounded channel in source etc.

**Comment by liurenjie1024** [comment]
> In what kind of scenario we should prefer unbounded? Never?
> 
> BTW, We also use unbounded channel in source etc.

Yes, we should never use unbounded channel.

**Comment by BowenXiao1999** [comment]
Also usually how to determine the size of bounded buffer? Seems like I can only get some magic number myself.

**Comment by liurenjie1024** [comment]
> Also usually how to determine the size of bounded buffer? Seems like I can only get some magic number myself.
> 
> Skim repo and found we prefer "10".

"10" maybe too small, I think we should use make it configurable and use tests to determine it.
