### ISSUE TITLE
Deprecate parse_duration

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#3027]
[parse_duration](https://github.com/zeta12ti/parse_duration/) is no longer maintained and has some security alerts.

**Comment by nasnoisaac** [comment]
I'm willing to help with this

**Comment by TennyZhuang** [comment]
> I'm willing to help with this

Thanks! Before sending a PR, it’s better to propose your solution, such as which lib will be used instead? Or if you decide to write it manually, which functionality will be supported?

Don't worry, in fact we only use the lib in a few non-critical codes, and break change may also be acceptable. Feel free to post your solution here, since it can significantly reduce the review time.

**Comment by nasnoisaac** [comment]
[humantime](https://github.com/tailhook/humantime) seems a good alternative.  I think we can just use it for now.

**Comment by TennyZhuang** [comment]
LGTM
