### ISSUE TITLE
store the catalog of state table

### ISSUE THREAD

**Issue by st1page** [singularity-data/risingwave#3053]
We use a relational-table layer in both mview and internal state, and they share the same format. but now the meta just assign a table id for the plan node and the state table catalog is not stored and the stream executor infers the table's information(columnDesc, columnId, pk_indices etc) by themselves.

1. on fe infer the table catalog and store in the prost when the stream nodes serialize to prost.
2. meta not only assign the tableId, but also store the inferred table catalog in meta store like materialized view

**Comment by xx01cyx** [comment]
Also meta should notify fe of the state tables after an mview is created, if we are to support querying data of internal state tables.

**Comment by WindowsXp-Beta** [comment]
exactly, it will be done after #3139 get merged

**Comment by BowenXiao1999** [comment]
Can we provide a tracking todo-list for this issue?, cc @WindowsXp-Beta
