### ISSUE TITLE
Tracking: support `string_agg`

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#3115]
- [x] #3434 
- [x] #3720
- [x] #3390
- [x] #3838
- [x] #2868

Related:
- #3006

**Comment by BowenXiao1999** [comment]
> streaming: support creating string_agg state

Do you mean current string_agg state will no longer be used?

**Comment by skyzh** [comment]
It is not created for now, and we should integrate SQL with this state.

**Comment by BowenXiao1999** [comment]
I'll quickly removed the ManagedTableState trait on string_agg, for not blocking others.

**Comment by BugenZhao** [comment]
> I'll quickly removed the ManagedTableState trait on string_agg, for not blocking others.

So maybe I'll implement it back in #3390. 🥵

**Comment by richardchien** [comment]
Finally we have everything checked. Closing this tracking issue now.
