### ISSUE TITLE
ci: docker pull slow

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3125]
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/4198311/173009344-5230a193-a186-4c91-b5a6-2f33febbd86c.png">

After I introduced some cache in build image, the docker pull step becomes slow. I guess this is limited by disk bandwidth. We can configure our EC2's EBS gp3 to have a high throughput.

cc @huangjw806 may help take a look next week :)

**Comment by huangjw806** [comment]
add cargo cache in workflows to reduce image size, and upgrade ec2 instance type to improve throughput.
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/29391315/174700052-aab52da7-bdd0-4779-baac-decf53af1cad.png">

**Comment by skyzh** [comment]
Looks good!
