### ISSUE TITLE
boolean in `concat` should be formatted to `t f` instead of `true false`

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#3146]
**Describe the bug**
```
dev=> select true as col;
 col 
-----
 t
(1 row)

dev=> select true::varchar as col;
 col  
------
 true
(1 row)

dev=> select concat(true) as col;
 col  
------
 true
(1 row)
```

```
postgres=# select true as col;
 col 
-----
 t
(1 row)

postgres=# select true::varchar as col;
 col  
------
 true
(1 row)

postgres=# select concat(true) as col;
 col 
-----
 t
(1 row)
```

**To Reproduce**
As above.

**Expected behavior**
The same behavior with postgres.

**Comment by xiangjinwu** [comment]
https://github.com/postgres/postgres/blob/19408aae7fa2bf28866fb262b27f08405e71152e/src/include/catalog/pg_cast.dat#L437-L450
```
# Cross-category casts to and from TEXT
# We need entries here only for a few specialized cases where the behavior
# of the cast function differs from the datatype's I/O functions.  Otherwise,
# parse_coerce.c will generate CoerceViaIO operations without any prompting.
# Note that the castcontext values specified here should be no stronger than
# parse_coerce.c's automatic casts ('a' to text, 'e' from text) else odd
# behavior will ensue when the automatic cast is applied instead of the
# pg_cast entry!

{ castsource => 'bool', casttarget => 'text', castfunc => 'text(bool)',
  castcontext => 'a', castmethod => 'f' },
```
In PostgreSQL, most types (`smallint/int/bigint/numeric/real/double precision/date/timestamp/timestamp with time zone/time/interval`) share the same function for **datatype's I/O** and **casting from/to string**. But `bool` is an exception:
* Its datatype output function always emits either `t` or `f`. ([ref](https://www.postgresql.org/docs/current/datatype-boolean.html#:~:text=The%20datatype%20output%20function%20for%20type%20boolean%20always%20emits%20either%20t%20or%20f))
* Its cast-to-string function is defined specially as above. As tested, it outputs `true` or `false`.

We will need to revisit which callers should be **I/O** and which callers should be **cast**.
