### ISSUE TITLE
Infer null as wrong boolean types in function

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#3149]
**Describe the bug**

RW:
> select substr('hello', NULL);
> ERROR:  Feature is not yet implemented: Substr[Varchar, Boolean], Tracking issue: https://github.com/singularity-data/risingwave/issues/112
> select substr(NULL, 1);
> ERROR:  Feature is not yet implemented: Substr[Boolean, Int32], Tracking issue: https://github.com/singularity-data/risingwave/issues/112

PG:

> select substr('hello', NULL);
> (empty)
> select substr(NULL, 1);
> (empty)

**To Reproduce**

**Expected behavior**
Be the same with PG. A similar one happens in #3148.

**Additional context**
Type inference probably goes wrong.

**Comment by xiangjinwu** [comment]
Due to the lack of #1386 we do not have good support of using **literal** `null` as function arguments. It can only be used within `insert` context. To workaround testing an expr's behavior when any input is null, create a column of that type and insert nulls in it:
```
create table t (v1 varchar, v2 int);
insert into t values (null, null);
select substr('hello', v2) from t;
select substr(v1, 1) from t;
```
