### ISSUE TITLE
consistent-hash: support reading by single vnode for specific states

### ISSUE THREAD

**Issue by xx01cyx** [singularity-data/risingwave#3159]
Currently, all states will maintain **a set of vnodes**, which are stored in the state's keyspace. However, every state of hash agg and hash join will only query data that belongs to **one vnode**. Therefore, we could narrow the range of vnodes when reading data from storage, i.e., only pass in **one vnode** instead of a set of vnodes.

The vnode that belongs to a state could be computed when the state is created.

**Comment by skyzh** [comment]
So we'll need to compute hash before every get and prefix scan in storage?

**Comment by xx01cyx** [comment]
> So we'll need to compute hash before every get and prefix scan in storage?

For MV, maybe yes. For other states, we could directly use the pre-computed vnode.

**Comment by hzxa21** [comment]
> > So we'll need to compute hash before every get and prefix scan in storage?
> 
> For MV, maybe yes. For other states, we could directly use the pre-computed vnode.

How to pre-compute the VNode of a get/prefix_scan key beforehand? We don't know the key until we need to read it.

For internal state (i.e. non-MV state), I think compure hash before every get/prefix_scan is okay since we will only hit one VNode.
