### ISSUE TITLE
Tracking: Deep dive compaction.

### ISSUE THREAD

**Issue by twocode** [singularity-data/risingwave#319]
This is to observe, understand, and improve our compactors, so that we can come up with optimizations with regarding to performance, cost efficiency, and new compaction strategies.
- [x] #195 
- [x] Review compaction metrics under continuous workloads (TPCH, nexmark bench)
- [x] More code comments.
- [x] #811
- [x] Refactoring compactor.

**Comment by soundOfDestiny** [comment]
cc @zwang28 @Little-Wallace
