### ISSUE TITLE
batch: True parallel table scan.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#3237]
Currently, although we run table scan in parallel, in fact only one task truly works. This is a limitation in storage, and we need to make it truly parallel.

**Comment by BowenXiao1999** [comment]
> only one task truly works.

Are there more details on this?

**Comment by xxchan** [comment]
> > only one task truly works.
> 
> Are there more details on this? 

`RowSeqScanExecutor::is_primary`

**Comment by BugenZhao** [comment]
Related: #311
