### ISSUE TITLE
frontend: duplicated column name when create mv

### ISSUE THREAD

**Issue by cykbls01** [singularity-data/risingwave#3260]
**Describe the bug**
Using follow sql.
CREATE TABLE t (v1 int, v2 int,v3 timestamp);
CREATE MATERIALIZED VIEW t2 as select *from t;
CREATE MATERIALIZED VIEW t3 as select s1.v1 as v1,s1.v2 as v2,s1.v3 as v3 from t2 as s1 cross join t2 as s2 where s1.v1 = s2.v1;
CREATE MATERIALIZED VIEW t4 as select t2.v1 as v1 from t2 cross join t3 where t2.v1 = t3.v1;

<img width="383" alt="image" src="https://user-images.githubusercontent.com/36026213/173967946-10aa98dc-9c0e-4961-acbd-c2d51831d727.png">

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

**Comment by xiangjinwu** [comment]
might be related: #2662
