### ISSUE TITLE
batch: Datachunk in channel should be sent in parallel.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#3279]
Yes I thought about this. What about done this in anthor PR? Prevoius it is also not parallel.

_Originally posted by @BowenXiao1999 in https://github.com/singularity-data/risingwave/pull/3273#discussion_r898903137_

**Comment by liurenjie1024** [comment]
> Possibly not a big difference.
> 
> When no output hits the upper limit, send is not blocking.
> 
> When some output hits the upper limit, every one else will be waiting for it to be unblocked.

Why others need to wait for it?

**Comment by lmatz** [comment]
Let's say a broadcast channel tries to send the data chunk to task output 1,2,3,4,5.

Within this `fn send(&mut self, chunk: Option<DataChunk>) -> Self::SendFuture<'_> {` call,
we have to finish sending data chunks to all 5 output channels.

So the time spent in this call is determined by the straggler, e.g. the channel that hits the upper limit. In this case, even if we finish sending data chunks to 4 out of 5 output channels, we have to wait for the last one(which hits the upper limit) to be unblocked.

If no output channel hits the upper limit, with/without parallel sending is the same. The `send` on the `bounded channel` is not blocking.

**Comment by BowenXiao1999** [comment]
Indeed, the `send` on non-blocking channel should be fast enough that we can not get too much gains from parallelize (?).

**Comment by liurenjie1024** [comment]
Yes, concurrent send may cause other issue, e.g. memories not freed and hold by pending tasks of straggler. Let's close this.
