### ISSUE TITLE
Tracking: take vnode into consideration for key ordering

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#3316]
Design: [RFC: Take VNode into consideration for Internal State KV ordering](https://singularity-data.quip.com/F1qtAyCCHG5Q/RFC-Take-VNode-into-consideration-for-Internal-State-KV-ordering)

- [x] #3416
- [x] #3432
- [ ] fix executor usages and enable real vnodes (#3543)
- [x] pre-compute single vnode as an optimization (#3159)
- [ ] cleanup `ValueMeta`
- [ ] ...

**Comment by BowenXiao1999** [comment]
> support scanning and iterating with a range of vnodes using merge sort

In what kind of access patterns we need this?

**Comment by BugenZhao** [comment]
> > support scanning and iterating with a range of vnodes using merge sort
> 
> In what kind of access patterns we need this?

May check the Q&A part of the design doc posted by @fuyufjh. :)

**Comment by BugenZhao** [comment]
`ValueMeta` has been removed by #3779. Close this
