### ISSUE TITLE
Count(distinct column) not execute right in MATERIALIZED VIEW

### ISSUE THREAD

**Issue by cykbls01** [singularity-data/risingwave#3323]
**Describe the bug**
<img width="386" alt="image" src="https://user-images.githubusercontent.com/36026213/174504877-3bc449cf-25a3-4061-9ef8-49496d129984.png">
<img width="456" alt="image" src="https://user-images.githubusercontent.com/36026213/174504887-1f84de57-8531-40ec-87dc-e6fad5961baf.png">

Select count(distinct id) have different result in MATERIALIZED VIEW.
In pgsql, this sql should have same result.

**To Reproduce**
```
create table t (v1 int, v2 int, v3 int);
insert into t values (1,2,3), (1,3,4), (2,3,4);
select count(distinct v1) from t;
create materialized view t2 as select count(distinct v1) as v from t;
select * from t2;
```

**Expected behavior**

**Additional context**

**Comment by lmatz** [comment]
Related: #2915

**Comment by TennyZhuang** [comment]
Before it was implemented correctly, I think it's better to reject the query.

**Comment by st1page** [comment]
It is still now right now @likg227 
```
dev=> create table tt(v1 int, v2 int, v3 int);
CREATE_TABLE
dev=> insert into tt values (1,2,3), (1,3,4), (2,3,4);
INSERT 0 3
dev=> explain select count(distinct v1) from t;
                              QUERY PLAN                              
----------------------------------------------------------------------
 BatchSimpleAgg { aggs: [sum(count(t.v1) filter((flag = 0:Int64)))] }
   BatchExchange { order: [], dist: Single }
     BatchSimpleAgg { aggs: [count(t.v1) filter((flag = 0:Int64))] }
       BatchHashAgg { group_key: [t.v1, flag], aggs: [] }
         BatchExchange { order: [], dist: HashShard(t.v1, flag) }
           BatchExpand { column_subsets: [[t.v1]] }
             BatchScan { table: t, columns: [v1] }
(7 rows)

dev=> select count(distinct v1) from t;
 ?column? 
----------
        0
(1 row)

**Comment by xiangjinwu** [comment]
#3589 still have one open item

**Comment by st1page** [comment]
> #3589 still has one open item

Sorry, I forget it.

**Comment by st1page** [comment]
the distinct agg in batch query has been done and give right result of the case in the issue. #3589

**Comment by likg227** [comment]
In this case, the distinct agg in batch query and stream query both give correct result. However, the pk of expand is incorrect so distinct agg in stream query may give incorrect result #4179 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/55606560/183599878-ff67bdd8-398a-4860-a01f-08e8fa4335e8.png">
