### ISSUE TITLE
test: fix slow test case `test_compaction_drop_key_by_existing_table_id`

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3348]
```
PASS [  10.360s]                                risingwave_storage hummock::compactor_tests::tests::test_compaction_drop_key_by_existing_table_id
```

The value looks too big inside, which might make testing slow. May try reducing the value size and key count. Generally a single test should complete within 1-3 secs.

**Comment by skyzh** [comment]
... I found

```
PASS [   6.022s]                                risingwave_storage hummock::compactor_tests::tests::test_compaction_same_key_not_split
```

This case also becomes slower. Is that because of some recent changes in test case default options?

**Comment by Li0k** [comment]
> ... I found
> 
> ```
> PASS [   6.022s]                                risingwave_storage hummock::compactor_tests::tests::test_compaction_same_key_not_split
> ```
> 
> This case also becomes slower. Is that because of some recent changes in test case default options?

can not reappear this case (which spend 10s and 6s) in my machine

> ``` 
> test hummock::compactor_tests::tests::test_compaction_drop_key_by_existing_table_id ... ok
> test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 109 filtered out; finished in 4.81s
> ```

> ``` 
> test hummock::compactor_tests::tests::test_compaction_same_key_not_split ... ok
> test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 109 filtered out; finished in 3.24s
> ```

i guess it was affected by compaction_filter logic or value size , so that i try to shadow the filter function call , but it always slow 

> ```
> test hummock::compactor_tests::tests::test_compaction_drop_key_by_existing_table_id ... ok
> test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 109 filtered out; finished in 6.50s
>```

finally i reduce the value_size in unit test , we can control the cost of test less than 1s
> ```
> test hummock::compactor_tests::tests::test_compaction_drop_key_by_existing_table_id ... ok
> test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 109 filtered out; finished in 0.16s
>```
