### ISSUE TITLE
Sqlsmith: Generate CREATE MATERLIAZIZED VIEW statements

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#3368]

**Comment by kwannoel** [comment]
Closed via #3886

**Comment by kwannoel** [comment]
Still need to run in e2e, add generation to `create_tables`: https://github.com/singularity-data/risingwave/blob/dfa6ab3937e0ac326322a26adce90f714befc465/src/tests/sqlsmith/src/bin/main.rs#L72

Currently only frontend tests use this functionality.
