### ISSUE TITLE
Sqlsmith: Generate EquiJoin

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#3369]

**Comment by kwannoel** [comment]
Do either implementations of sqlancer generate this currently?
- https://github.com/anse1/sqlsmith
- https://sourcegraph.com/github.com/cockroachdb/cockroach@0782befa48d54a67c3830963280838137542539e/-/blob/pkg/internal/sqlsmith/sqlsmith.go

**Comment by kwannoel** [comment]
Closed by #3613
