### ISSUE TITLE
sqlsmith: flaky test

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3371]
**Describe the bug**

https://github.com/singularity-data/risingwave/issues/3361

Even if we are using a random seed, it seems that each run yields different SQL.

**To Reproduce**

**Expected behavior**
Always succeed, or always fail for one test case.

**Additional context**

**Comment by skyzh** [comment]
We should also run with random seed in daily test, instead of in every PR.

**Comment by liurenjie1024** [comment]
cc @neverchanje 
I also think we should use fixed seed in ci, and random seed in daily test.

**Comment by skyzh** [comment]
I've set a fixed seed, but it still fails randomly, so I'm investigating way.
