### ISSUE TITLE
Support configuration parameter `extra_float_digits`

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#3406]
**Describe the bug**
> SET extra_float_digits = 3;
> unrecognized configuration parameter "extra_float_digits"

**To Reproduce**

**Expected behavior**
The same as PG.

**Additional context**

**Comment by lmatz** [comment]
[postgresql.org/docs/current/datatype-numeric.html#DATATYPE-FLOAT](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-FLOAT)

>For compatibility with output generated by older versions of PostgreSQL, and to allow the output precision to be reduced, the [extra_float_digits](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-EXTRA-FLOAT-DIGITS) parameter can be used to select rounded decimal output instead. Setting a value of 0 restores the previous default of rounding the value to 6 (for float4) or 15 (for float8) significant decimal digits. Setting a negative value reduces the number of digits further; for example -2 would round output to 4 or 13 digits respectively.

>Any value of [extra_float_digits](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-EXTRA-FLOAT-DIGITS) greater than 0 selects the shortest-precise format.

>Applications that wanted precise values have historically had to set [extra_float_digits](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-EXTRA-FLOAT-DIGITS) to 3 to obtain them. For maximum compatibility between versions, they should continue to do so.

**Comment by lmatz** [comment]
My understanding is that setting to `3` for us is a no-op right now as we always output the shortest-precise format.

**Comment by liurenjie1024** [comment]
Should we close this issue now?
