### ISSUE TITLE
Utilize idle exit for cluster mode playground

### ISSUE THREAD

**Issue by breezewish** [singularity-data/risingwave#3447]
**Is your feature request related to a problem? Please describe.**

In cluster mode playground, when meta server is exited, other server is not stopped, so that the idle exit does not fully work.

**Describe the solution you'd like**

Bring down other servers when meta is down in the cluster mode playground.

**Describe alternatives you've considered**

**Additional context**

See https://github.com/singularity-data/risingwave/pull/3444 for the idle exit feature.

**Comment by xxchan** [comment]
close in favor of https://github.com/singularity-data/risingwave/issues/3608
