### ISSUE TITLE
batch: Implement partition pruning as much as possible.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#3450]
Currently for each table scan, we send requests to all partitions(vnodes) to scan. But it's unnecessary, for example, when we execute 
```
select * from t where a in (1, 2, 3)
```
and `a` is key of table `t`, we can use prune unnecessary partitions(vnodes) of table `t` and only send request to them.

Given currently we only have consistent hash as partition algorithm, we can start with a simple partition pruning algorithm:

1. Convert all filter in table into disjunct form, for above algorithm we can convert it into `a =1 or a = 2 or a = 3`
2. For each conditition with `a = ?` form, we can calculate its corresponding vnode and keep only necessary ones.

**Comment by xxchan** [comment]
Mostly finished. Further improvements tracked in https://github.com/singularity-data/risingwave/issues/3477
