### ISSUE TITLE
frontend: distribution key of `StreamNode::HashAgg` should be group key

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#3456]
https://github.com/singularity-data/risingwave/blob/78861e3092c361890bc1212d1557154e4ca47e8f/proto/stream_plan.proto#L67-L75

Related PR: #1342

**Comment by BowenXiao1999** [comment]
sure

**Comment by BowenXiao1999** [comment]
After review parts of the FE infer internal table for hash agg, there are several bugs. I will fix them but I'm not so sure the distribution key in the table catalog is correct.
