### ISSUE TITLE
feat(storage): refactor write operation on `local_version` to simple replace

### ISSUE THREAD

**Issue by Little-Wallace** [singularity-data/risingwave#3459]
### Background

* Now we will change `local_version` in `LocalVersionManager` when we need to pin a new version and generate a new upload task and it will block a lot of read requests on other thread.

### Solution

* copy the old `local_version` and replace it with new one. For example:

```rust
        let old_version = self.local_version.read().clone();

        if old_version.pinned_version().id() >= new_version_id {
            return false;
        }
        let new_version = old_version.as_ref().clone();
        new_version.set_pinned_version(newly_pinned_version);
        let mut guard = self.local_version.write();
       *guard = Arc::new(new_version);
```

**Additional context**

**Comment by skyzh** [comment]
🥵🥵🥵 looks cool! parking_lot also supports upgrade read lock, which might be helpful here.

**Comment by skyzh** [comment]
@Li0k told me he's interested in this issue. As I'll have a long vacation next week, he can have a try before I come back :)

**Comment by Li0k** [comment]
I take some bench test on ec2, found that the read_lock (which use in read_version) may cost more than 50 ms. As num of parallel increases, iter duration and lock_cost_ms also grows up.  Moreover, the lock_most is only a part of iter_duration , may be other time consuming issues.

**Comment by Little-Wallace** [comment]
closed by https://github.com/singularity-data/risingwave/pull/3620

**Comment by Little-Wallace** [comment]
> > read_lock (which use in read_version) may cost more than 50 ms
> 
> How did you measure? Sometimes Instant::now() may lead to syscall and in turn interfere with measure result. Use ministant or coarse clock instead?
> 
> > iter duration and lock_cost_ms also grows up
> 
> Did you bench with #3462?
> 
> The result doesn't look surprising :) We can see how to improve the lock contention here.

I think it is because our throughput is too low.... If the iter QPS could reach 500K or 1M we can find how much latency cost by lock contention
