### ISSUE TITLE
dropping source while associated fragments still exist

### ISSUE THREAD

**Issue by zwang28** [singularity-data/risingwave#3473]
**Describe the bug**
When running certain e2e test, the below warning is triggered from `SourceManager`:
```
        if core.source_fragments.contains_key(&source_id) {
            log::warn!(
                "dropping source {}, but associated fragments still exists",
                source_id
            );
        }
```

**To Reproduce**
1. ./risedev d
2. ./risedev slt -p 4566 -d dev -u root e2e_test/streaming/datagen.slt
3. Check meta node's log

**Expected behavior**
No warning.

**Additional context**

**Comment by shanicky** [comment]
let me figure it out
