### ISSUE TITLE
feature: evaluate expression in frontend

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#3479]
To generate the range for TableScan in the execution plan, it's inevitable to support evaluating expressions in frontend. 

This goal is also related to constant folding, considering that some predicates may contain constant expressions instead of literals.

---------------

> I agree, but we don't have eval in fe yet? 🤔

We need one!

_Originally posted by @fuyufjh in https://github.com/singularity-data/risingwave/pull/3470#discussion_r906972758_

**Comment by xxchan** [comment]
As suggested by @neverchanje offline, we could approach #3479 in a similar way:
```
impl ExprImpl {
    pub fn eval_row(&self, input: &Row) -> Result<Datum> {
        let be_expr = build_from_prost(&self.to_expr_proto())?;
        be_expr.eval_row(input)
    }
}
```
This interface is unlikely to change, and we can replace its implementation to avoid proto ser/de later.

At the caller side, we can:
```
lit.cast_implicit(return_type)?.eval_row(Row::empty())
```
There would be no `is_null` or `eval_as` on `Literal`.


Supporting const_expr beyond literals can also build on top of this.

---

The use of `cast_implicit` also reminds us of the following case:
```
select * from t where v1 < 60000 -- v1 is actually smallint
```
This should evaluate to true. But casting 60000 to smallint would result in an error. `cast_implicit` would report the error in all cases even when it is `v1 < 2` forcing us to handle this case, while `eval_as` only reports the error when it actually exceeds `32767`.

_Originally posted by @xiangjinwu in https://github.com/singularity-data/risingwave/pull/3507#discussion_r908013993_
