### ISSUE TITLE
refactor: Use `column_mapping` in stateful executor

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#3485]
The `proto::HashAgg` plan contains a field called column_mapping (mapping of input col index -> internal table idx), which is unused in CN yet. In theory it can simplify the logic in stream executor.

**Comment by richardchien** [comment]
It seems that `column_mapping` is necessary for `string_agg` with `order by` clause. I'm trying to build the mapping in `infer_internal_table_catalog` and use it in StringAgg, other aggregators may be refactored later.

**Comment by BowenXiao1999** [comment]
> It seems that `column_mapping` is necessary for `string_agg` with `order by` clause. I'm trying to build the mapping in `infer_internal_table_catalog` and use it in StringAgg, other aggregators may be refactored later.

I wrote a PR for only-frontend infer in #4108. Do you have some time to take a look at how to correctly use column_mapping in executor (When working on string_agg)? I tried a bit early and found there might need a lot refactor changes so postpone it 😢 .

I think at least require two things:
1. Use column_mapping in executor
2. Decouple AggState and state_table completely.

**Comment by richardchien** [comment]
I think we can close this issue, cuz streaming aggregators now use `column_mapping` inferred by frontend.

**Comment by BowenXiao1999** [comment]
Sure
