### ISSUE TITLE
meta: concurrent create MV

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3490]
After concurrent checkpoint has been introduced https://github.com/singularity-data/risingwave/issues/1156 https://github.com/singularity-data/risingwave/pull/2184, there's still one thing not solved: DDL cannot be concurrent. If there's build actor (config change) barrier, the whole system will fall back to single barrier mode.

Concurrent DDL might be already "supported" now if we remove the limit, but we're not sure about the correctness. We should revisit the meta service and do some refactors to take concurrent DDL into consideration everywhere, and therefure everything will work when we allow concurrent DDL barriers.

There's some issues related to concurrent DDL, like https://github.com/singularity-data/risingwave/pull/3084 https://github.com/singularity-data/risingwave/issues/3051, which caused compute node crash when running parallel e2e test. This might also be fixed after we've fully revisited the meta service's DDL related code.

This issue will be updated later with detailed design.

<del>@Shmiwy is currently doing some initial investigations, and might take this issue.</del> Need someone else to work on it!

**Comment by liurenjie1024** [comment]
Hmm, DDL is too broad and I don't think all DDL operations can be concurrent. It would be better to be precise about what operation you want it to be concurrent.

**Comment by skyzh** [comment]
Sure, then we change it to concurrent create MV :)

**Comment by BugenZhao** [comment]
Is there any unresolved issue related to concurrent mview creation for now?

**Comment by BugenZhao** [comment]
I've reviewed the procedure of creating mview these days and it should work well for concurrent mview creation:
- We'll create actors in the first step. The newly created actors are unconnected on the compute nodes and marked `Inactive` in the meta store.
- To truly activate these actors, we schedule and execute them in barrier manager sequentially.
- The concurrent checkpoint handles uncommitted command correctly in #3511.

**Comment by skyzh** [comment]
That's great! Let's close this issue now.
