### ISSUE TITLE
support Python PG client

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#3501]
as title.

**Comment by skyzh** [comment]
Maybe related: https://github.com/singularity-data/risingwave/issues/2621

**Comment by infdahai** [comment]
Maybe I can do this work in this week.

**Comment by fuyufjh** [comment]
> Maybe I can do this work.

Thanks! 🥰 Please self-assign it

**Comment by TennyZhuang** [comment]
> > Maybe I can do this work.
> 
> Thanks! 🥰 Please self-assign it

Only member can assign tasks :)

**Comment by TennyZhuang** [comment]
Related #3253

**Comment by TennyZhuang** [comment]
And I guess you mean psycopg2

**Comment by xxchan** [comment]
I tested `psycopg2` with some basic usage and it seemed to work 😄.
