### ISSUE TITLE
RFC: unnesting arbitrary subquery

### ISSUE THREAD

**Issue by likg227** [singularity-data/risingwave#3508]
## Background

Currently, we decorrelate correlated subquery according to [Microsoft's paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr-2000-31.pdf?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-dtJe0GmL.4SsJTkTske9LQ&epi=je6NUbpObpQ-dtJe0GmL.4SsJTkTske9LQ&irgwc=1&OCID=AID2200057_aff_7593_1243925&tduid=%28ir__h6q2mfqvsskf6hkumgqhu9cqon2xvszmcwvsveys00%29%287593%29%281243925%29%28je6NUbpObpQ-dtJe0GmL.4SsJTkTske9LQ%29%28%29&irclickid=_h6q2mfqvsskf6hkumgqhu9cqon2xvszmcwvsveys00). This approach is complicated and unclear. Besides, it makes some parts of result plan redundant. #3502 

## Design

We can implement this [paper](https://btw-2015.informatik.uni-hamburg.de/res/proceedings/Hauptband/Wiss/Neumann-Unnesting_Arbitrary_Querie.pdf) for RisingWave. It's much more flexible and not that tricky. See current implementation in #2880 

According to original paper, there are two phases: simple unnesting and general unnesting. 

1. The simple unnesting phase moves all dependent predicates up the algebra tree as far as possible. Some simple queries can be unnested in this phase, e.g. `t1.v1 in (select t2.v1 from t2 where t1.v2 = t2.v2)`. One thing to note that we currently only support pull up dependent predicates through Filter and Project. We just use the rule PullUpCorrelatedPredicate to pull up dependent predicates now, but we may extend simple unnesting's functionality in the future by adding more rules. 
2. The general unnesting phase pushes Apply down the plan. First, we translate the Apply into a “nicer” Apply (i.e., one that is easier to manipulate), and second, we will push the new Apply down into the query until we can transform it into a regular join. This phase can decorrelate all the subqueries theoretically, and it will be used to unnest all the subqueries that can't be unnested by simple unnesting. Please to note that we will introduce DAG when translating Apply.

## Future Optimizations

We can remove DAG if we can substitute it with values that already exist in the subtree anyway. Unfortunately, this optimization can only be applied to some special case(i.e. all the correlated columns are equal with uncorrelated columns). In other cases, we need join to ensure the correctness.

## Discussions

We had a discussion about predicate pushdown in subquery, which is not that simple to decide...........cc @xiangjinwu  @st1page

**Comment by st1page** [comment]
> We had a discussion about predicate pushdown in subquery, which is not that simple to decide

It is about if we can push down the predicate traversing the `LogicalApply` on both left and right sides. I used to doubt its correctness, but after trying to give a counterexample many times, I think it is right.
