### ISSUE TITLE
suspicious bug: Do not need explicit flush before create MV? 

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#3525]
I'm not sure whether it is bug or something. 

As the test below, we create MV and read recent insert data.
https://github.com/singularity-data/risingwave/blob/cb84b42c1010fc7830aa7b45c03c6772932382ee/e2e_test/streaming/append_only.slt#L1-L22

My question is: 

**Why mv1 can read data insert into t1, t2 without flush?**

IMO, the MV on table t1, t2 needs a BatchQuery Executor to read snapshot data. However, we do not explicit call "flush". 
It means the BatchQuery of mv1 might scan nothing if the data is not flushed to S3. If the batch query scans nothing, then select from mv1 should also be empty? 

Although mv1 will init a config change barrier, however it is not done before creating the stream. 

Guess reason why the test success:
The checkpoint increased exactly happen between insert and select. That's why we see the correct results.

Want to make sure my understanding is correct. cc @hzxa21 @fuyufjh @yezizp2012 @BugenZhao

**Comment by yezizp2012** [comment]
I did some test locally and found that query on mv alway occurred after a or some checkpoint barriers. One sample timeline list as follows:
T1(2022-06-28T11:20:38.278134Z): (ddl barrier injected) create mv
T2(2022-06-28T11:20:38.296021Z): checkpoint barrier
T3(2022-06-28T11:20:38.547189Z): checkpoint barrier
T4(2022-06-28T11:20:38.571381Z): starting query

So I think the reason you guessed is right. The InsertExecutor will ensure that the data will be taken by downstream before it response success. After checkpoint between insert and select, the data will be visible.

**Comment by yezizp2012** [comment]
And the ddl barrier is collected after the first checkpoint injected, which means before frontend received the ddl response a checkpoint already happened. And, the frontend should also wait for the mv create notification before it can response to the client. There's also a gap here.

**Comment by BowenXiao1999** [comment]
Well I found my understanding towards Mv on Mv is incorrect. Will summarize detail/conclusion later.

**Comment by BowenXiao1999** [comment]
discuss with @yezizp2012 

Conclusion: 
Q: How mv1 read data insert into table t1, t2?
A: When MoM (Mv on Mv), a barrier will flow through t1. data like (1, 2), (2, 3) will be flushed to storage. So chain of mv1 can read it from the snapshot data.  

Q: Why after create mv1, we do not need flush but can also read all data?
A: Current ddl procedure:
1. init a config change barrier, it will flow through the mv1. (Note: At this time, there is no data in mv1 stream, as config change barrier will not wait for chain op, so no data is flushed at this barrier).
2. Meta inject a periodically barrier, it will flow through mv1 and **collect info that chain op is done**. At this round, the data like (1, 2), (2, 3)  is flushed to storage. So in this way, batch query can read the data. 
3. After meta knows that chain op is done, it will then respond to frontend that ddl request was done. 

So create MV at least collect 2 barriers. One for config change (do not flush data), and one for period barrier (flush data + mark MoM done). 

This can explain why the e2e test is always succeed.
