### ISSUE TITLE
refactor: Remove `last_pinned` in pin_snapshot RPC

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#3550]
Previously becasue: https://singularity-data.quip.com/Qbv8AypJHU68/Retryable-pin-RPC-in-hummock, we need to have `last_pinned` as parameters.. 

Now we should remove it due to we have `unpin_snapshot_before()`. See the doc discuss:
https://singularity-data.quip.com/r3tLA5QxCCvc#CBQADA2GP5i

**Comment by Little-Wallace** [comment]
And context_id is also not necessary.

**Comment by BowenXiao1999** [comment]
Indeed

**Comment by BowenXiao1999** [comment]
Blocked on #3551

**Comment by ZENOTME** [comment]
for now, we have a new implementation of HummockSnapshotManager after #3551. I think last_pinned has been removed now. So we can close this issue now?
