### ISSUE TITLE
meta: do not persist pinned snapshots

### ISSUE THREAD

**Issue by Little-Wallace** [singularity-data/risingwave#3551]
### Background

see more recently changes in https://github.com/singularity-data/risingwave/issues/2364

Now we will call once `pin_snapshot` for every request in frontend and frontend will call `unpin_snapshots_before` periodically. But both  `pin_snapshot` and `unpin_snapshots_before` will start an meta transaction and persist changes to meta-storage (mostly ETCD).

The following code shows that every frontend node will have one request slow down by etcd when `max_committed_epoch` changes. And if  the frontend serves many requests with several threads, each thread will be block on this persist operation.

So we need a solution to support high performance `pin_snapshot` calls.

```rust
        if !context_pinned_snapshot
            .snapshot_id
            .contains(&max_committed_epoch)
        {
            snapshots_change = true;
            context_pinned_snapshot.pin_snapshot(max_committed_epoch);
        }

        if snapshots_change {
            commit_multi_var!(self, Some(context_id), context_pinned_snapshot)?;
        }
```

### Solution

- Do not acquire the same lock which may hold by other threads during persisting data to ETCD.
- Just return `max_committed_epoch` and do not record anything to ETCD.
- Since we have `unpin_snapshot_before` now, we only need to update and record `min { unpin_committed_epoch }` and we do not need to concern about which epoch is pinned.

The solution proposed by this PR has no effect on the behavior of the frontend.

**Describe alternatives you've considered**

- Compactor can not execute GC when some frontend lose connection with meta-service until it recovers to connect or be removed by meta-service.

**Additional context**

**Comment by BowenXiao1999** [comment]
I think after this PR, push-based pin/unpin is more naturally to impl. Now, meta do not need to auto pin new epoch for each context. It will make the epoch more updated and less error prone. 

After push based, for most cases, we will no longer use pin_snapshot

**Comment by BowenXiao1999** [comment]
This is a pre-req of #3577 . 
https://github.com/singularity-data/risingwave/blob/c3a17ce074d2ce710491bad03d3d4035fc4b9f26/src/meta/src/hummock/hummock_manager.rs#L573-L578
