### ISSUE TITLE
refactor: strong type Config

### ISSUE THREAD

**Issue by TennyZhuang** [singularity-data/risingwave#3562]
Store all config entries as string value is error-prone and inefficient, introduce some strong type Config.

Like this https://github.com/datafuselabs/databend/blob/main/query/src/config/inner.rs

**Comment by BowenXiao1999** [comment]
Previously I want one like this, but can not find the libs in rust....

https://github.com/singularity-data/risingwave-legacy/blob/3a1ebcf580eb7e807234c07c48bdf8b62d932a7c/java/common/src/main/java/com/risingwave/common/config/ConfigEntry.java

**Comment by TennyZhuang** [comment]
#3568
