### ISSUE TITLE
bug: Batch plan fragment may have more than one table scans.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#3569]
Currently it's not possible, since HashJoin has Exchange on both its inputs. What about doing it later when needed?

_Originally posted by @xxchan in https://github.com/singularity-data/risingwave/pull/3251#discussion_r910475638_

**Comment by skyzh** [comment]
I saw that ...

> since HashJoin has Exchange on both its inputs

Is this an explicit rule? The streaming fragmenter has made it a rule that one fragment will have at most one stateful executor. But for batch, I guess if distribution is satisfied, it won't have exchange in-between. e.g. join key is order-by / pk. 

cc @xxchan

**Comment by skyzh** [comment]
Maybe related: https://github.com/singularity-data/risingwave/issues/3607

**Comment by liurenjie1024** [comment]
> I saw that ...
> 
> > since HashJoin has Exchange on both its inputs
> 
> Is this an explicit rule? The streaming fragmenter has made it a rule that one fragment will have at most one stateful executor. But for batch, I guess if distribution is satisfied, it won't have exchange in-between. e.g. join key is order-by / pk.
> 
> cc @xxchan

Yes, it's possible if the joined tables have same distribution on join keys.
