### ISSUE TITLE
bug: no exchange for hopping window

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#3573]
Query:

https://github.com/singularity-data/risingwave/blob/5ff98d772f19ebb85aa3c6dd577db0c29693d1ab/e2e_test/streaming/time_window.slt.disabled#L1-L21

Explain:
```
dev=> explain create materialized view mv_hop as
select * from hop(t1, created_at, interval '15' minute, interval '30' minute);
                                                                         QUERY PLAN                                                                          
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 StreamMaterialize { columns: [row_id, uid, v, created_at, window_start, window_end, _row_id(hidden)], pk_columns: [_row_id, window_start], dist_keys: [4] }
   StreamHopWindow { time_col: $3, slide: 00:15:00, size: 00:30:00, output_indices: [0, 1, 2, 3, 5, 6, 4] }
     StreamTableScan { table: t1, columns: [row_id, uid, v, created_at, _row_id], pk_indices: [4] }
(3 rows)
```

Note that the table scan is distributed by `_row_id`, while materialize is distributed by `window_start`. There should be an exchange inserted between them, or should we use `_row_id`?

**Comment by fuyufjh** [comment]
+1. at least there should be an `Exchange` before `Materialize`

**Comment by skyzh** [comment]
> +1. at least there should be an Exchange before Materialize

If the key is distributed by row_id, it also satisfies `[_row_id, window_start]` distribution. So we don't need to insert an exchange.

**Comment by skyzh** [comment]
But we can always have an ad-hoc rule to insert an exchange before materialize so as to split them into two actors and thus improve parallelism 🤣

**Comment by BugenZhao** [comment]
> > +1. at least there should be an Exchange before Materialize
> 
> If the key is distributed by row_id, it also satisfies `[_row_id, window_start]` distribution. So we don't need to insert an exchange.

#3595 fixed the issue by distributing with the input pk without exchange, which also fulfill the idea of #3255. I think we can close this issue now.
