### ISSUE TITLE
test: order of e2e test results

### ISSUE THREAD

**Issue by xxchan** [singularity-data/risingwave#3583]
https://github.com/singularity-data/risingwave/pull/3582 should be revisited

Generally, we need to either:
1. default to `rowsort`, add `nosort` to tests with order
2. default to `nosort`, add `rowsort` to tests without order
3. add both, reject default order.

Since most queries don't require order, 1 is more convenient. But 2 is more safe. (3 is safer, which can force the developer to consider the order) 

---

Current (1 already merged) unsafe problems
- [ ] missing `nosort` on tests with order. They won't fail even if result order is incorrect.
- [ ] actually failing: batch parallel scan on ordered mv may have unorderd results. should do a merge sort after parallel scan.
  - [ ] currently workaround: only single task for scan. So #3237 is not enabled

---

other things about UX

* yes, but one special case that will affect user experience is window table functions / date time columns. Though order is not important in our system, users might feel weird that older windows appear later than newer windows when they select from table. Not sure whether we should make user happy or just tell them we do not ensure order...
* just an idea, maybe we can add a "RW_SORT_PK" mode for batch query so that users can get consistent output when select? We always produce output with pk sorted in batch query if this option is enabled.

_Originally posted by @skyzh in https://github.com/singularity-data/risingwave/issues/3582#issuecomment-1171522240_

**Comment by liurenjie1024** [comment]
I would vote for 2 or 3, since safety is more important to me in tests.

**Comment by liurenjie1024** [comment]
BTW I think we should revert #3582 first?

**Comment by liurenjie1024** [comment]
I think most of #3251 are done. How about we revert #3582 first, but do a small modification in scheduler to schedule one task for table scan to workaround this the bug?

**Comment by xxchan** [comment]
You mean only one task? LGTM

**Comment by liurenjie1024** [comment]
> You mean only one task? LGTM

Exactly. And we can do small changes to enable true full table scan after we fixed bugs.
