### ISSUE TITLE
bug: Barrier carry wrong create_mv msg from cn to meta(e2e_parallel_test_fail)

### ISSUE THREAD

**Issue by xxhZs** [singularity-data/risingwave#3598]
**Describe the bug**
We have been having a lot of failed in e2e_parallel_test_fail. We cannot query any things in mv.

<img width="1374" alt="WeChate97a86a773cc33db24df1a1953312231" src="https://user-images.githubusercontent.com/84456268/176855520-64efc406-a53d-4be7-9268-a706431a8a97.png">
And we can query the right result in the mv after some times. And @zwang28  find this bug easy to reproduce after concurrent checkpoint. https://github.com/singularity-data/risingwave/pull/2184

**To Reproduce**
@hzxa21 find the epoch of query large than the epoch of create_mv_over in frontend , But it will less than the epoch of mv written to hummock. So we think the cn tell frontend(or meta) a wrong epoch.
(write_to_hummock_epoch > query epoch > create_mv_over_epoch).

And we see the code of cn. we find how bugs are created

1. create_mv_barrier(epoch1) flows through all graph. but the mv is not finished.
2. when epoch2 flows through actor1, the mv is not finished, and barrier(epoch2)_collected is not finished too.
3. when epoch3 flows through actor1, the snapshot has all sent, so this actor is finished(ManagedBarrierState.progress.done = true).and barrier(epoch3)_collected is not finished too.
4. when epoch2 flows through actor2. barrier(epoch2)_collected is finish. So the barrier with `progress.done = true` send to meta, Then meta think this mv is over with epoch2. But it will be commit in epoch3. 
5. So query between epoch2 and epoch3 will wrong

**Additional context**

**Comment by hzxa21** [comment]
> So looks like it's a bug in meta? cc @hzxa21 @yezizp2012

No, it is a bug in the CN's local barrier manger. The root cause is: local barrier manager attaches the epoch2's CreateMviewProgress to epoch1 when we have concurrent checkpoint of epoch1 and epoch2. Therefore, meta thinks CreateMV succeeds in epoch1 instead of epoch2 and if the query uses epoch1 to read mv it will see nothing.

**Comment by skyzh** [comment]
So what about merging https://github.com/singularity-data/risingwave/pull/3084 to temporarily fix this issue?

**Comment by yezizp2012** [comment]
> So what about merging #3084 to temporarily fix this issue?

Finally fixed parallel sqllogictest on stream e2e. I'm not sure if it is the cause of this issue. But I passed all the test locally.

**Comment by hzxa21** [comment]
> So what about merging #3084 to temporarily fix this issue?

I believe #3602 can fix this issue. @xxhZs is trying it out.

**Comment by xxhZs** [comment]
I also believe https://github.com/singularity-data/risingwave/pull/3602 can fix this issue. And I think this [issue](https://github.com/singularity-data/risingwave/issues/3559) maybe cause to the parallel e2e test failure after https://github.com/singularity-data/risingwave/pull/3602. So, after I confirm, I will close this issue
