### ISSUE TITLE
function: regexp_match and regexp_matches

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#3605]
**Is your feature request related to a problem? Please describe.**

I need a function that can extract the hashtags from a tweet. In postgres, it's `regexp_match` and `regexp_matches `. 

```
postgres=# select regexp_matches('Hello #risingwave #singularity', '#\w+', 'g');
 regexp_matches
----------------
 {#risingwave}
 {#singularity}
(2 rows)
```

**Describe the solution you'd like**

https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP

- regexp_match(target Varchar, pattern Varchar);
- regexp_matches(target Varchar, pattern Varchar);
- regexp_matches(target Varchar, pattern Varchar, flag Varchar);

Rust regexp library: https://docs.rs/regex/latest/regex/

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by xxchan** [comment]
regexp_matches can be implemented after https://github.com/singularity-data/risingwave/pull/4030

**Comment by xxchan** [comment]
[Flags](https://www.postgresql.org/docs/current/functions-matching.html#POSIX-EMBEDDED-OPTIONS-TABLE) are not yet implemented. It's just ignored, which might be confusing. We'd better at least report an error @TennyZhuang 

```sql
dev=> select regexp_match('abc01234xyz', 'ABC', 'i');
 ?column?
----------

(1 row)
```

**Comment by neverchanje** [comment]
I feel it won't be an issue as long as we keep the code and the doc consistent. What do you say?

**Comment by xxchan** [comment]
> @xxchan I feel it won't be an issue as long as we keep the code and the doc consistent. What do you say?

Yes, indeed. But just in case, I've just added an argument check #4546
