### ISSUE TITLE
risectl: support dump internal table

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3609]

**Comment by alissa-tung** [comment]
I am interested in this ticket, may I have a try on this？

**Comment by skyzh** [comment]
Thanks!

**Comment by skyzh** [comment]
Hi @alissa-tung , I found that we have much more to do before adding support for dump internal table. The internal tables are not yet in catalog, and will take a lot of work before it can be used. I think it would be better for me to coordinate and take over this issue. What do you think? 🤣

**Comment by alissa-tung** [comment]
> Hi @alissa-tung , I found that we have much more to do before adding support for dump internal table. The internal tables are not yet in catalog, and will take a lot of work before it can be used. I think it would be better for me to coordinate and take over this issue. What do you think? rofl

thx fine. thx and sorry

**Comment by skyzh** [comment]
> that's fine. thx and sorry

My fault :)

**Comment by skyzh** [comment]
depends on https://github.com/singularity-data/risingwave/issues/3648

**Comment by skyzh** [comment]
Already supported.
