### ISSUE TITLE
Discussion: Syntax of Grouping Top-N

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#3646]
Grouping Top-N i.e. select the top-n elements of each group, seems a common requirement in real-world products, especially combined with temporal windows.

## Example: Flink

https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/dev/table/sql/queries/window-topn/

Flink officially recommends to use `ROW_NUMBER() OVER WINDOW` and `WHERE rownum <= ...`. The semantic is well-defined, but it seems a little tricky to optimize it in the optimizer.

Here is an example from NexMark written in Flink SQL dialect. 

```sql
--- Q19 ---
INSERT INTO discard_sink
SELECT * FROM
(SELECT *, ROW_NUMBER() OVER (PARTITION BY auction ORDER BY price DESC) AS rank_number FROM bid)
WHERE rank_number <= 10;
```

## Example: Materialize

https://materialize.com/docs/sql/patterns/top-k/

Materialize represents this with `LATERAL JOIN`. This seems more stright-forward compared with NexMark, but still unfriendly to users.

```sql
SELECT state, name FROM
    (SELECT DISTINCT state FROM cities) grp,
    LATERAL (
        SELECT name FROM cities
        WHERE state = grp.state
        ORDER BY pop DESC LIMIT 3
    )
```

## For RisingWave: ?

Should we choose from one of the above or introduce another syntax?

**Comment by xiangjinwu** [comment]
[PostgreSQL](https://www.postgresql.org/docs/14/functions-window.html) also uses the `over` syntax, although I do see it would make the binder/planner/optimizer more complicated.

The lateral join would be easier on our side, and pushes the complexity of rewriting to the user.

Both are common sql syntax that may be used in broader cases. Unless we have a better design or need it before full support of either, a dedicated syntax is less preferable.

**Comment by liurenjie1024** [comment]
Flink uses `over` syntax, and it provides time window top-n based on this:
https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/dev/table/sql/queries/topn/
https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/dev/table/sql/queries/window-topn/

When comes time window topn, it seeme reduntant to me to use lateral join.

**Comment by likg227** [comment]
> The lateral join would be easier on our side, and pushes the complexity of rewriting to the user.

Unfortunately, this may not be easy for us. IIUC, this is the same as a correlated subquery. We can't push Apply down TopN now, and I don't find a way to do it........

**Comment by fuyufjh** [comment]
Can we reach an agreement on Flink's approach?

**Comment by liurenjie1024** [comment]
LGTM

**Comment by xxchan** [comment]
Close discussion. Impl tracked in 4847
