### ISSUE TITLE
bug: Limit push down lost top limit.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#3726]
**Describe the bug**
The plan for distributed limit is incorrect.

**To Reproduce**
![image](https://user-images.githubusercontent.com/2771941/177746053-ef758d3c-d886-44db-a308-be898d8a259a.png)

**Expected behavior**
We should add a limit in top exchange.

**Comment by liurenjie1024** [comment]
cc @chenzl25

**Comment by xxchan** [comment]
I think there is no things like limit push down now.. We just need to let limit has single distribution?

**Comment by xxchan** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/37948597/177754826-888f8a1f-6625-4537-8b2a-c423566d4ea9.png">

minimal reproduce
