### ISSUE TITLE
Server crashes when equality columns of a hash join have different data types

### ISSUE THREAD

**Issue by Graphcalibur** [singularity-data/risingwave#3749]
**Describe the bug**
If a hash join is performed on two tables such that the equality columns have different data types (e.g. `a JOIN b ON a.a1 = b.b1` where `a.a`` is `int` while `b.b1` is `bigint`), the server will crash.

```
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**To Reproduce**
```
create table a(a bigint);
create table b(b int);
insert into a values (1);
insert into b values (2);
select * from a join b on a.a = b.b;
```

**Expected behavior**
Either the join is successful for types which can be compared (like `int` and `bigint`) or an error message is displayed that doesn't cause the server to stop.

**Additional context**

**Comment by xiangjinwu** [comment]
dup with #3478 ?

**Comment by Graphcalibur** [comment]
Ah, I did not notice that issue. I'll close this one then.
