### ISSUE TITLE
frontend: Move partition prunning/location logic to meta crate.

### ISSUE THREAD

**Issue by liurenjie1024** [singularity-data/risingwave#3799]
The partition pruning/localtion logic is also useful in lookup join executor, which lives in batch crate. To avoid circular dependency of frontend and batch crates, we should move it to meta crate.

The partition pruning logic:
https://github.com/singularity-data/risingwave/blob/b6189745e2ee9f863a6e17b65fc134f409f65442/src/frontend/src/utils/scan_range.rs#L65

The partition location logic: 
https://github.com/singularity-data/risingwave/blob/b6189745e2ee9f863a6e17b65fc134f409f65442/src/frontend/src/scheduler/worker_node_manager.rs#L84

**Comment by Graphcalibur** [comment]
Would it be better to place these in the common crate instead since the common crate is already a dependency of the batch and frontend crates?
