### ISSUE TITLE
feat(optimizer): simplify expand's column_subsets.

### ISSUE THREAD

**Issue by likg227** [singularity-data/risingwave#3806]
**Is your feature request related to a problem? Please describe.**

Sometimes, Expand's `column_subsets` is a little bit redundant and we can simplify it, which will improve its performance. 
Here are some examples: 

1. `LogicalExpand { column_subsets: [[0, 1, 2, 3]] }` and `input.schema.len() == 4`
2. `LogicalExpand { column_subsets: [[2, 1, 2], [1, 0], [1, 2]] }`

**Describe the solution you'd like**

For 1, we can just remove this unnecessary Expand.
For 2, we can merge subsets of `column_subsets`, and get a new concise `column_subsets`: [[1, 2], [1, 0]].

**Comment by xiangjinwu** [comment]
Another possible optimization (#4230): certain subset may be completely useless as their corresponding `flag` value is not used by parent:
```
- sql: |
    /* prune key of column_subsets */
    create table t(v1 int, v2 int);
    with z(a, b) as (select count(distinct v1), count(v2) from t) select a from z;
  optimized_logical_plan: |
    LogicalAgg { aggs: [count($0) filter(($1 = 1:Int64))] }
      LogicalAgg { group_key: [$0, $1], aggs: [] }
        LogicalExpand { column_subsets: [[], [0]] }
          LogicalScan { table: t, columns: [v1] }
```
