### ISSUE TITLE
frontend: literal type inference

### ISSUE THREAD

**Issue by Enter-tainer** [singularity-data/risingwave#3819]
### Problem
```rs
    pub fn new(data: Datum, data_type: DataType) -> Self {
        Literal { data, data_type }
    }
```
In the current code, to create a `Literal`, both `data` and `data_type` is required. However, it's easy to make mistakes when using an API like this: `data` and `data_type` may not match. Here is an example:

```rs
pub fn(&self, flag_value: i32) {
  // ...
  let filter_expr = FunctionCall::new(
    ExprType::Equal,
    vec![
        InputRef::new(pos_of_flag, DataType::Int64).into(),
        Literal::new(Some(flag_value.into()), DataType::Int64).into(), // bug here, flag_value is i32 but data_type is i64
    ],
  );
}
```

What makes it worse is that when such a situation happens, no error will be reported until the executors try to deserialize this `Literal`, This makes the bug very hard to diagnose.

### Possible solution
We may introduce type checking or even type inference to this to avoid the mismatch ~~since the `Datum` already contains the needed type info~~ .(**UPD:** This is not true according to @xiangjinwu 's comment below. But we may check the type in "best effort". )

**Comment by xiangjinwu** [comment]
> since the `Datum` already contains the needed type info

This is not true for the following types: `timestampz`, `list`, `struct`.

It is easy to update `timestampz` to use a wrapped chrono type rather than i64 in datum, but for list / struct it may not be possible.

**Comment by Graphcalibur** [comment]
Seems like we can just reuse the type checking for `LiteralExpressions`: https://github.com/singularity-data/risingwave/blob/main/src/expr/src/expr/expr_literal.rs#L84-L116
