### ISSUE TITLE
doc: add pgwire doc

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#3837]
PG-wire is a network layer interact with users. It may faces a lot of dev requirements from user-side, cloud team, product team. 

Aiming at making it easily for each devs to hack it, I plan to write a doc on how to contribute and some design arch. So that every one has a feat-request, they are capable operating on their own.

**Comment by BowenXiao1999** [comment]
Currently TODOs (Feel free to assign if you are interest)

- [ ] #3676 
- [ ] pgwire: SSL Support

**Comment by ZENOTME** [comment]
cool. I think pgwire will have a more concise arch after https://github.com/singularity-data/risingwave/issues/3829.

**Comment by BowenXiao1999** [comment]
Write a Quip doc named "pgwire layer". Closed.
