### ISSUE TITLE
test: enable current regress tests

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#3853]
One problem is dealing with the error messages.

Since we don't want to be completely compatible with PG in terms of error messages (too much effort),
I'd like to put error cases in another separate file, i.e. boolean.sql -> boolean.sql and boolean.error.sql

When we run the regress tests:
1.  by RW, the difference occurred in boolean.error.sql fails the test.
2. by PG, the difference occurred in boolean.error.sql does not fail the test. But we still output the difference in the error messages as a reference. 
This is for the convenience of gradually making RW's error messages make more sense. I suppose correcting error messages take time.

**Comment by liurenjie1024** [comment]
+1 for this proposal.

**Comment by neverchanje** [comment]
Please be noted that we should not fully support regess test at once. Because there are alot features that wont be considered at our current stage. Let's clarify the objective: we should focus on the tests that we currently support. Otherwise it can be delayed until we fully understand its requirement.

**Comment by liurenjie1024** [comment]
> Please be noted that we should not fully support regess test at once. Because there are alot features that wont be considered at our current stage. Let's clarify the objective: we should focus on the tests on the currently supported feature set. Features otherwise can be delayed until we fully understand their requirements. (its not worthwhile to support CREATE FUNCTION just because regress test has some cases relying on it.

Yes, and it's quite easy to achieve by gradually adding test case in schedule file.

**Comment by lmatz** [comment]
1. We prioritize testing all the queries that are supposed to be correct and supported. 
2. Testing queries that lead to errors are not urgent at the current moment.

Therefore, we comment out all the error queries for the moment.

The way of splitting into `boolean.sql` and `boolean.error.sql` has the problem that there could be `insert` statements in the middle of the file and they have side effects, as pointed out by @liurenjie1024. 

It can be solved if we interpret the test file or output file by ourselves, but don't want to make things complicated at the moment.
