### ISSUE TITLE
incorrect depth of correlated input ref after planner

### ISSUE THREAD

**Issue by xiangjinwu** [singularity-data/risingwave#3862]
**Describe the bug**

**To Reproduce**
Add the following to `src/frontend/test_runner/tests/testdata/subquery_expr_correlated.yaml` and run `./risedev do-apply-planner-test`:
```
- sql: |
    create table a (a1 int, a2 int);
    create table b (b1 int, b2 int);
    select * from a where a1 = (select min(b1) from (select * from b where b2 = a2) as z);
  logical_plan: |
    dummy
```
The generated logical plan (not optimized yet) is:
```
    LogicalProject { exprs: [$1, $2] }
      LogicalFilter { predicate: ($1 = $3) }
        LogicalJoin { type: LeftOuter, on: true, output_indices: all }
          LogicalScan { table: a, columns: [_row_id, a1, a2] }
          LogicalProject { exprs: [$0] }
            LogicalAgg { group_key: [], agg_calls: [min($0)] }
              LogicalProject { exprs: [$0] }
                LogicalProject { exprs: [$1, $2] }
                  LogicalFilter { predicate: ($2 = CorrelatedInputRef { index: 2, depth: 2 }) }
                    LogicalScan { table: b, columns: [_row_id, b1, b2] }
```
Note that the `CorrelatedInputRef` has `depth: 2` but no corresponding `LogicalApply`.

**Expected behavior**
TBD

In binder, the `depth` refers to the levels of `BindContext` it needs to go upside/outside. But in planner, it seems not to correspond to `LogicalApply` nicely.

The depth should not count ordinary joins either. For example:
```
select * from a where a1 = (select min(b1) from (select * from b where b2 = a2) as z join c on true);
select * from a where a1 = (select min(b1) from (select * from b where b2 = a2) as z join c on true join d on true);
```
The binder always sees the depth as 2, but the join nodes above `b2 = a2` can be arbitrarily more.

**Additional context**
Note this is the logical plan produced by planner and have not gone thru optimizer decorrelation yet.

Inspired by test case in https://github.com/singularity-data/risingwave/issues/3842#issuecomment-1182993119 where the depth in logical plan also looks incorrect.

**Comment by jon-chuang** [comment]
> The binder always sees the depth as 2, but the join nodes above b2 = a2 can be arbitrarily more.

So in my discussion with @likg227 I suggested that join should not contribute to correlation depth, and we should instantiate every subquery as a logicalapply instead of logicaljoin if uncorrelated. So correlation depth always corresponds to subquery depth as per now.

**Comment by chenzl25** [comment]
What I want to mention is that maintaining a related position (`depth`) on a plan node is not a good idea. You know, plan node can be  transformed by rule locally, whenever we apply a rule to a plan node we need to take care of all other nodes with related position and change it correctly to maintain the relationship. Maybe an absolute position(`CorrelatedId`) is a better way.

**Comment by chenzl25** [comment]
#4888 solves this issue
