### ISSUE TITLE
Sqlsmith: Generate Type Castings

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#3878]
We can reversely build the casting map from src/frontend/src/expr/type_inference/cast.rs `CAST_MAP` like what we did for the functions table. Then we can randomly choose a viable cast in `gen_expr`.

The reverse expr building path:

1. First we know exactly the select item's returning type.
2. Use `gen_expr` to randomly select an expr that will return the target type. At a certain probability, it tries to generate `cast`.
3. Reversely find the source type that is able to cast to the target type, according to the cast map.
4. Generate the cast.

Additionally, the non-viable castings are also needed to test. For example, `SELECT bool 'test'`. We will now fail on this SQL.

- [x] Gen viable cast: https://github.com/singularity-data/risingwave/pull/4419
- [x] Gen non viable cast. Track here instead: #4468

**Comment by xiangjinwu** [comment]
related: #1632

**Comment by kwannoel** [comment]
Completed by #4419 . Track non viable castings separately here: #4468 .
