### ISSUE TITLE
single quote string unqualified for table name

### ISSUE THREAD

**Issue by lmatz** [singularity-data/risingwave#3891]
**Describe the bug**
RW:
![SCR-20220714-p00](https://user-images.githubusercontent.com/5791930/178957127-cdd6d263-37b7-427d-8864-94a0dc8a8890.png)

**To Reproduce**

**Expected behavior**
PG:
![SCR-20220714-ozl](https://user-images.githubusercontent.com/5791930/178957161-8d3f0d3a-42ba-4b0a-812e-0e953979a9df.png)

**Additional context**
Block regress test

**Comment by lmatz** [comment]
Probably need to be dealt together with #3888

**Comment by lmatz** [comment]
since the message says it's a `syntax error`, the parser should already have the knowledge to reject it.

**Comment by xiangjinwu** [comment]
In PostgreSQL source code `parser`'s output is `optimizer`'s input:
https://github.com/postgres/postgres/tree/master/src/backend/parser

On our side, checking in sqlparser or binder both make sense to me.
