### ISSUE TITLE
lru: cancel in-flight requests if all listeners are cancelled 

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3912]
After https://github.com/singularity-data/risingwave/pull/3911 is merged, even when all listeners have been cancelled, the LRU cache may still have in-flight requests. We should optimize this.

**Comment by xxhZs** [comment]
Can I do it?

**Comment by skyzh** [comment]
We're discussing it in #wg-create-mv-stuck. May take a look at the discussions before taking this.

**Comment by fuyufjh** [comment]
Does it seem to be fixed already? Shall we close?

**Comment by skyzh** [comment]
Not yet

**Comment by Little-Wallace** [comment]
Since we have execute future in tokio-pool, if other calling cancel the future of `lookup_with_request_dedup`, the tokio-pool can still finish this future and clean the pending requests.
