### ISSUE TITLE
Sqlsmith: Form the dependency between only can choose one from Distinct or Orderby/Approx...

### ISSUE THREAD

**Issue by marvenlee2486** [singularity-data/risingwave#3933]

**Comment by marvenlee2486** [comment]
Two approach, 
One is before generation a query preset which mode to use

Another one is the mode is undefined until the 1st occurence of disntict or Orderby/Approx.

Still thinking which one to use but both required.
a mode variable in generator.

**Comment by kwannoel** [comment]
I don't quite understand this issue. Could you clarify further?

**Comment by marvenlee2486** [comment]
Distinct may also be disallowed by sibling agg calls, for example agg0(distinct ...), agg1(... order by ...), approx_xxx(...) is invalid. That is, when agg order by or approx_xxx is present, distinct is disallowed in ALL agg calls.
In addition, select/having/order  clauses are considered siblings:
```
select avg(distinct v1)
from t
having sum(v2 order by v3)
order by approx(v4)
```
is also invalid.
BTW rejection of such invalid query is a WIP PR #3920

Message from XiangJin in #proj_expr
