### ISSUE TITLE
failed to handle `hop(t, col, INTERVAL '10 minutes', INTERVAL '1 day')`

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#3966]
**Describe the bug**

```
dev=> SELECT
dev-> FROM
dev->     HOP(
dev(>         user_behaviors,
dev(>         event_timestamp,
dev(>         INTERVAL '10 minutes',
dev(>         INTERVAL '1 day'
dev(>     );
ERROR:  QueryError: Invalid Parameter Value: Invalid parameter 'window_size', 'window_slide': window_size 1 day 00:00:00 cannot be divided by window_slide 00:10:00.
```

`1 day` was regarded as 00:00:00. 

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

**Comment by fuyufjh** [comment]
@TennyZhuang any progress?

**Comment by TennyZhuang** [comment]
This is because postgresql doesn’t treat 1 day as 24 hours, it may be 23 or 25 instead.

I’m not sure what the correct behavior should be, and need to do some investigation.

**Comment by fuyufjh** [comment]
Shall we close this? @neverchanje

**Comment by neverchanje** [comment]
That works for me, though the error message is unfriendly :(

```sql
 select * from hop(t, report_time, interval '1 minute', interval '24 hours');
```
