### ISSUE TITLE
hop panics when window_start/window_end is not used

### ISSUE THREAD

**Issue by neverchanje** [singularity-data/risingwave#3967]
**Describe the bug**

```
dev = >
SELECT
    COUNT() AS view_count
FROM
    HOP(
        user_behaviors,
        event_timestamp,
        INTERVAL '10 minutes',
        INTERVAL '1440 minutes'
    )
GROUP BY
    target_id;

ERROR: QueryError: RPC error: Status { code: Internal,
message: "internal error: broken fifo_channel",
metadata: MetadataMap { headers: { "risingwave-error-bin": "CAESI2ludGVybmFsIGVycm9yOiBicm9rZW4gZmlmb19jaGFubmVs" } },
source: None }.
```

Although the displayed error appeared to be "broken fifo_channel", the root cause was in fact another: 

```
2022-07-18T08:10:15.798521Z ERROR risingwave_batch::task::task_execution: Execution failed [TaskId { task_id: 0, stage_id: 1, query_id: "99e70aad-e214-4b42-98ca-30dd11326e48" }]: BatchError: Internal(neither window_start or window_end is in output_indices
```

It was because `window_start`/`window_end` was not used. So if I also include `window_start` in the group by clause, the query will then succeed.

```sql
SELECT
    COUNT() AS view_count,
    window_start
FROM
    HOP(
        user_behaviors,
        event_timestamp,
        INTERVAL '10 minutes',
        INTERVAL '1440 minutes'
    )
GROUP BY
    target_id,
    window_start;
```

I know the latter is typically what is used in the real world. But it still ruins the user experience when users try to develop the SQL, as the error is counterintuitive.

**To Reproduce**
Steps to reproduce the behavior.

```sql
CREATE TABLE user_behaviors (
    user_id BIGINT,
    target_id VARCHAR,
    target_type VARCHAR,
    event_timestamp TIMESTAMP,
    behavior_type VARCHAR,
    parent_target_type VARCHAR,
    parent_target_id VARCHAR
);

SELECT
    COUNT() AS view_count
FROM
    HOP(
        user_behaviors,
        event_timestamp,
        INTERVAL '10 minutes',
        INTERVAL '1440 minutes'
    )
GROUP BY
    target_id;
```

**Expected behavior**

**Additional context**

**Comment by st1page** [comment]
the error is a check in compute node and I will remove it. Because we should not prevent users do anything SQL grammar allows. And maybe we should do the check in the frontend and give the user a warning, but process the query. 
And also we should improve the backend's error handling. now every internal query error message can not be delivered to users which is counterintuitive as you say.
