### ISSUE TITLE
streaming: `StreamChunk` needs a visible iterator

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#3970]
We have visible rows iterator for `DataChunk`, but the iterator do not contains ops. But in many case, executor needs op + data at the same time. 

So maybe we should create a visible iterator on `StreamChunk` that will return `Row` and `Op` corresponding.

**Comment by BugenZhao** [comment]
Is `StreamChunk::rows` what you need?

https://github.com/singularity-data/risingwave/blob/ac2068d3d8a2edcbe9ed201bc41b08a7ce7c71ec/src/common/src/array/stream_chunk_iter.rs#L31-L42

**Comment by BowenXiao1999** [comment]
Yes indeed! Thanks for the clarification
