### ISSUE TITLE
Sqlsmith: Use deterministic seed for sql gen

### ISSUE THREAD

**Issue by kwannoel** [singularity-data/risingwave#4002]
We want to be able to reproduce generated queries from branch in CI.
- In daily cron job, we can use random seed, so we can continually test new queries.
- In CI, we should use deterministic seed / madsim.
- Locally as well, for easier debugging.
- For frontend we can modify some data structures to be deterministic as suggested here: https://github.com/singularity-data/risingwave/issues/4002#issuecomment-1188654074
- However for e2e, this is much harder to do, since there are many more such instances to refactor. Probably better to wait for madsim effort to complete.

Previously mentioned here: https://github.com/singularity-data/risingwave/issues/3989#issuecomment-1188529519

Related: #3467

**Comment by skyzh** [comment]
I have already set a seed for all tests, but there're other indeterministic...

https://github.com/singularity-data/risingwave/blob/766f617982275f1aaa1c13a377bad2cfe2b8f4df/src/tests/sqlsmith/tests/test_runner.rs#L117-L126

**Comment by skyzh** [comment]
I think @wangrunji0408 may help integrate this with madsim :)

**Comment by kwannoel** [comment]
> I have already set a seed for all tests, but there're other indeterministic...
> https://github.com/singularity-data/risingwave/blob/766f617982275f1aaa1c13a377bad2cfe2b8f4df/src/tests/sqlsmith/tests/test_runner.rs#L117-L126

Don't quite understand. Aren't seeds deterministic (0..31):

https://github.com/singularity-data/risingwave/blob/766f617982275f1aaa1c13a377bad2cfe2b8f4df/src/tests/sqlsmith/tests/test_runner.rs#L128-L159

**Comment by skyzh** [comment]
Yes. But there might be HashMaps, accidentally created other rand gens, etc, that caused the test to behave in deterministically.

**Comment by xiangjinwu** [comment]
> Yes. But there might be HashMaps, accidentally created other rand gens, etc, that caused the test to behave indeterministically.

Function signatures are in a `HashMap`...
https://github.com/singularity-data/risingwave/blob/766f617982275f1aaa1c13a377bad2cfe2b8f4df/src/frontend/src/expr/type_inference/func.rs#L610-L613

Just sharing one idea I had before: we can update `build_type_derive_map() -> FuncSigMap` to `build_type_derive_map(&mut impl FuncSigContainer)`, so that type inference logic can build a HashMap from it, while sqlsmith can build a Vec.

Better ideas are welcome.

**Comment by wangrunji0408** [comment]
> I think @wangrunji0408 may help integrate this with madsim :)

Okay. I'm currently working on integrating madsim into e2e test. (In other words, trying to run the whole risingwave on a simulator.) I'll take a look at sqlsmith once it's done.

**Comment by wangrunji0408** [comment]
> Yes. But there might be HashMaps, accidentally created other rand gens, etc, that caused the test to behave indeterministically.

There's a little trouble dealing with HashMap. It has an internal thread local state as the seed. Every time a new map is created, the seed will be increased by 1, which makes it hard to be deterministic. ([source](https://doc.rust-lang.org/nightly/src/std/collections/hash/map.rs.html#3114))

However, I've found a dark magic that might work. [Take a look](https://github.com/madsys-dev/madsim/tree/main/madsim-norandom) if you're interested :)

**Comment by fuyufjh** [comment]
> In daily cron job, we can use random seed, so we can continually test new queries.

LGTM

> In CI, we should use deterministic seed / madsim.

I prefer to manually add the (once) failed cases into our e2e test suites.

**Comment by kwannoel** [comment]
Original goal for this was to reproduce generated query. This is resolved by logging failing queries #4228 . We can close this.
