### ISSUE TITLE
feat(meta): support authentication with etcd

### ISSUE THREAD

**Issue by arkbriar** [singularity-data/risingwave#4018]
**Is your feature request related to a problem? Please describe.**

According to the [src/meta/src/rpc/server.rs#L95-L101](https://github.com/singularity-data/risingwave/blob/0b7aea581774f70ddf91a811d7ad9ae68222a257/src/meta/src/rpc/server.rs#L95-L101), I think there's no authentication when connecting to the etcd. We could have one to explore a more secure way to establish connections between meta and etcd.

**Describe the solution you'd like**

Provide an option to specify the credentials of etcd, e.g., `--etcd-username` and `--etcd-password`, or just read the env `ETCD_USERNAME` and `ETCD_PASSWORD` like the AWS credentials. I prefer the latter.
The auth could be simply achieved with [`ConnectOptions::with_user`](https://docs.rs/etcd-client/latest/etcd_client/struct.ConnectOptions.html#method.with_user)

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by fuyufjh** [comment]
How about taking this by yourself 🥰
