### ISSUE TITLE
meta: Don’t Maintain SSTable Id in Meta

### ISSUE THREAD

**Issue by zwang28** [singularity-data/risingwave#4037]
# Don’t Maintain SSTable Id in Meta

## Background

To reduce meta store write by hummock service, we want to remove SstableIdInfo. 
Hummock service maintains a collection of SstableIdInfo. It tells when the SSTable id is created, when it's committed in version and when it's marked for deletion. Vacuum process uses it to identify SSTables qualified for deletion. Persisting SstableIdInfo brings considerable overhead when updating hummock version in meta node, because it results in many KV pairs written to meta store (proportional to number of SSTables to commit).

## Design
After removing SstableIdInfo, we need implement full GC in vacuum as:
1. Identifies candidate orphan SSTables by comparing full SSTs in object store with LSMtree in meta.
    - The object store list requires one or more charging IO. So full GC should be executed periodically, but not too often.
3. Filter out false positive orphan SSTables. Each node that updates hummock version should maintain a safe SST id locally. SST with id >= safe SST id should not be deleted because it may belong to a in-progress write op.

**Comment by yezizp2012** [comment]
We have implemented a `RowIdGenerator` using snowflake algorithm:[row_id.rs](https://github.com/singularity-data/risingwave/blob/cd35de56ff07d1424da3b5ae9ab59b689a54a80a/src/source/src/row_id.rs). Maybe we can move it to the common crate and do less refactor to meet both row and SStable id requirement.

**Comment by hzxa21** [comment]
> [MAX - timestamp] helps later vacuum process. It’s the prefix of id so that object store ordered list can work.

Will SST objects still be stored under the same parent prefix/folder after this change? Does the list operation rely on the assumption that all SST objects are stored under the same parent prefix/folder?

**Comment by zwang28** [comment]
> Will SST objects still be stored under the same parent prefix/folder after this change? 

I'd like to concat timestamp and uuid with a delimiter(e.g. '_') different from object store's ('/' currently). So timestamp is encoded in "file name" rather than represents a "folder".

> Does the list operation rely on the assumption that all SST objects are stored under the same parent prefix/folder?

No. But after multiple prefix is introduced, vacuum needs to additionally list all prefixes before processing each prefix.

**Comment by yezizp2012** [comment]
> Currently new SSTable id is generated by meta’s hummock service, during which a meta store write is required. The overhead is non-negligible under high SSTable creation rate.

Currently every 1000 id requests will trigger a meta store write, and Id generate support batch acquirement. Changing it to batch acquirement will reduce the cost.

**Comment by MrCroxx** [comment]
IMO, generated sst id doesn't need to be persisted. When recovery, Hummock needs to rebuild the manifest and the maximum sst id can be known at that point. 🤔

**Comment by zwang28** [comment]
> IMO, generated sst id doesn't need to be persisted. When recovery, Hummock needs to rebuild the manifest and the maximum sst id can be known at that point. 🤔

If we list object store on recovery, then yes. Otherwise there can be uncommitted SSTs, which is not tracked in LSM yet.

Anyway we will not persist generated SST id after this refactor.
