### ISSUE TITLE
Lookup Join throws an error when equality columns of join predicate have different data types

### ISSUE THREAD

**Issue by Graphcalibur** [singularity-data/risingwave#4044]
**Describe the bug**
When the equality columns of a join predicate in Lookup Join have different data types, the executor will throw an error instead of attempting to cast. This means even data types that are compatible with each other (i.e. int32 and int64) will still cause an error.

**To Reproduce**
```
set query_mode = local;
set rw_batch_enable_lookup_join = true;
create table t1 (v1 bigint, v2 int);
create table t2 (v1 int, v2 int);
create materialized view t3 as select v1, count(*) as v2 from t2 group by v1;
insert into t1 values (1, 3);
insert into t2 values (1, 4);
select * from t1 join t3 on t1.v1 = t3.v1;
```

Actual behavior: A `QueryError` is thrown and an error message is displayed.

**Expected behavior**
The query runs without error.
```
 v1 | v2 | v1 | v2 
----+----+----+----
  1 |  3 |  1 |  1
(1 row)
```

**Additional context**
Might be related: #3478

**Comment by liurenjie1024** [comment]
This is similar to other eq join conditions, and we should either disable different types for lookup join, or add cast to same types.
