### ISSUE TITLE
feat(pgwire): support BINARY format in extended query mode

### ISSUE THREAD

**Issue by ZENOTME** [singularity-data/risingwave#4049]
**Is your feature request related to a problem? Please describe.**
support BINARY format in extended query mode

**Comment by ZENOTME** [comment]
@BowenXiao1999  we need to decide where to convert to BINARY format.

original:
![image](https://user-images.githubusercontent.com/43447882/179945438-509871de-3774-4d70-b8c9-f83b9f15f0c9.png)

new design:
![image](https://user-images.githubusercontent.com/43447882/179945609-7395bf60-f09d-4619-885a-ceca4d93ccc4.png)

We can define a new type QueryResponse. When send back the query result, we use the PgResponse to construct QueryResponse(**We can convert to BINARY format at this construct process**). And we use QueryReponse to send back instead of PgResponse.

**Comment by BowenXiao1999** [comment]
> @BowenXiao1999 we need to decide where to convert to BINARY format.
> 
> original: ![image](https://user-images.githubusercontent.com/43447882/179945438-509871de-3774-4d70-b8c9-f83b9f15f0c9.png)
> 
> new design: ![image](https://user-images.githubusercontent.com/43447882/179945609-7395bf60-f09d-4619-885a-ceca4d93ccc4.png)
> 
> We can define a new type QueryResponse. When send back the query result, we use the PgResponse to construct QueryResponse(**We can convert to BINARY format at this construct process**). And we use QueryReponse to send back instead of PgResponse.

For send back you mean send back from handler? or write message?

**Comment by BowenXiao1999** [comment]
I think not necessary to introduce a new concept `QueryResponse`. 

Can we use some if-extended-flag stuff to do this?

**Comment by BowenXiao1999** [comment]
Got it. I think BinaryRow is good. Maybe we can make a enum contains `Row` and `BinaryRow`.

**Comment by ZENOTME** [comment]
https://www.postgresql.org/docs/current/protocol-message-formats.html#:~:text=The%20number%20of%20result,columns%20of%20the%20query.

there are three format cases according to the document:
1. default case(text format): the number of result-column format codes equals 0
2. uniform case: the number of result-column format codes equals 1, and the specified format code is applied to all result columns.
3. mix case: each column format can be either binary or text

the rust-postgres client is case2(uniform case). only case1 and case2 are more simple to implement (we can just use a 'bool' flag to identify case1 and case2.

And case 3 seems not common,  we can delay it now. what do you think? @BowenXiao1999

**Comment by BowenXiao1999** [comment]
> ase1 a

I agree with you. Add these statements to comment LGTM

**Comment by ZENOTME** [comment]
For binary format, we have build a framework. There are still some binary format haven't yet implement:
- [ ] Float32
- [ ] Float64
- [ ] Bool
- [ ] Decimal
- [ ] Interval
- [ ] NaiveDate
- [ ] NaiveDateTime
- [ ] Struct
- [ ] List

**Comment by ZENOTME** [comment]
I find serialized can make code easy
```
let mut serializer = Serializer::new(vec![]);
data.serialize(&mut serializer).unwrap();
serializer.into_inner().into()
```
And we don't have a serializer can convert to Postgres binary format, I think we can write a new serializer in utils.

**Comment by BowenXiao1999** [comment]
> I find serialized can make code easy
> 
> ```
> let mut serializer = Serializer::new(vec![]);
> data.serialize(&mut serializer).unwrap();
> serializer.into_inner().into()
> ```
> 
> And we don't have a serializer can convert to Postgres binary format, I think we can write a new serializer in utils.

Does Postgres binary format has a doc? I'm not sure whether we can find some crates people written before.

BTW, check neon and Materiliaze for some ref. But IIRC neon do not impl pg extended query mode.

**Comment by ZENOTME** [comment]
> > I find serialized can make code easy
> > ```
> > let mut serializer = Serializer::new(vec![]);
> > data.serialize(&mut serializer).unwrap();
> > serializer.into_inner().into()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And we don't have a serializer can convert to Postgres binary format, I think we can write a new serializer in utils.
> 
> Does Postgres binary format has a doc? I'm not sure whether we can find some crates people written before.
> 
> BTW, check neon and Materiliaze for some ref. But IIRC neon do not impl pg extended query mode.

I can't find an official doc for the binary format. I find a crate [postgres_types](https://docs.rs/postgres-types/0.2.3/postgres_types/) implement the ToSql for most of type, which is a trait convert the rust type into binary format. It works well in postgresSQL, so I think we can refer it. Actually I think we can reuse it directly in the serializer.

**Comment by BowenXiao1999** [comment]
Cool. Re-use other crates should be our first goal
