### ISSUE TITLE
Inconsistent style when building expression from prost

### ISSUE THREAD

**Issue by xxchan** [singularity-data/risingwave#4061]
Some uses functions `build_xx_expr`, while some implements `TryFrom`. They are effectly the same. Using the same style might be better. 

> **Note**
> Only applicable to single expressions. Not applicable to those functions using macros to build a group of different expreesions.

https://github.com/singularity-data/risingwave/blob/41e17b2a67477fdee5d5a669509771248cab3b0f/src/expr/src/expr/mod.rs#L103-L124

**Comment by Gun9niR** [comment]
I want to have a try at this. For the sake of consistency, perhaps we should replace all occurrences of `XxxExpression::try_from` with `build_xxx_expr`?

**Comment by xxchan** [comment]
Actually I slightly prefer the `try_from` style. cc @TennyZhuang What’s your opinion?

**Comment by TennyZhuang** [comment]
> Actually I slightly prefer the `try_from` style. cc @TennyZhuang What’s your opinion?

LGTM

**Comment by Gun9niR** [comment]
Not all kinds of expressions correspond to precisely one `Expression` type. 

For example, overlay expression may either create a `TernaryBytesExpression` or `QuaternaryBytesExpression`. So to refactor this using the `try_from` pattern, the only way I can think about is to create a separate type for each kind of expression, which is just a wrapper for `UnaryExpression/UnaryExpression`, etc. Is there a neater way to do this?

**Comment by xxchan** [comment]
We can keep complicate cases like `build_overlay_expr`, and refactor the other simple cases to make them more idiomatical. In other words, we can still use a `build_xxx` when necessary.
