### ISSUE TITLE
Tracking: Make `TableV2` a First-class Citizen!

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#408]
Currently when we are creating a table(v2), we're actually executing two SQLs:
```sql
create table_v1          _rw_source_table (v int);
create materialized view table as select * from _rw_source_table;
```

In fact, `_rw_source_table` has a lot in common with other sources like Kafka source:
- They are not responsible for materializing data to disk. The materialization is done by an associated streaming task which contains a `Materialize` executor.
- Since there's no materialized data, it's meaningless to do queries **on themselves**. We should do queries on materialized views. (exception: we have not decided whether we should disallow user to select from source directly)
- While `risingwave-stream` proceeds the stream chunks, their data is all input **from the outside**, like `risingwave-batch` and Kafka.

Also, there're some problems if we merge the concept of "Source" into "Table", like what we are doing now:
- We're using `TableId` to represent `SourceId`. Thus a table_v2 corresponds to two table ids, while one is for the table source, another is for the materialized view. User querying on the id of "table source" is non-sense.
- There are lots of fields specifically used by materialized view, in our current `Table` protobuf definition. Also, some fields are for Kafka source only.
https://github.com/singularity-data/risingwave-dev/blob/73765f7ff8d786cf1a061376c51f975a47e78d2c/proto/meta.proto#L30-L34

A possible solution is to separate `Source` from `Table`, and allocate `SourceId` specifically for them. `Table` will only represent materialized view in the future.

to be continued...

# Tasks

## Functionalities
- [x] #16
- [x] #784
- [ ] ...

## Table Catalog
- [x] #545
- [x] #866
- [ ] ...

## Native Support with the Rust Frontend
- [x] #1199  

### Column ID
- [ ] #480
- [x] Cell-based `MviewTable` serde with col index as col id, #642
- [x] #690
- [ ] ...

### Table and Table Manager
- [x] Remove the table v1 alternative `TestTable`, #673
- [x] #502
- [x] #431
- [ ] ...

## Unify with Stream Source
- [ ] ...

**Comment by xxchan** [comment]
Is this done?

**Comment by TennyZhuang** [comment]
> Is this done?

Yes
