### ISSUE TITLE
bug: 0.0.0.0 as host address?

### ISSUE THREAD

**Issue by wangrunji0408** [singularity-data/risingwave#4101]
**Describe the bug**
If we start a compute node with `--host 0.0.0.0:5688`, it will report `0.0.0.0` as its address to the meta node.
The meta can not reach the compute node via `0.0.0.0`.

**To Reproduce**
As above.

**Expected behavior**
Should we forbid `0.0.0.0` as host address?
Or we don't specify the host address on compute side, instead we use the [remote_addr](https://docs.rs/tonic/latest/tonic/struct.Request.html#method.remote_addr) from `tonic::Request` on the meta side?

**Additional context**

**Comment by skyzh** [comment]
You'll also need to specify client address. Host is for listen address. RiseDev already correctly handles this. See `.risingwave/log/risedev.log` on how we start the cluster.

**Comment by skyzh** [comment]
May use `--client-address <real_ip>:5688 --host 0.0.0.0:5688` to start compute node.

**Comment by wangrunji0408** [comment]
I see. We'd better add an assertion `client_address != 0.0.0.0` on compute side or meta side. Now communication will fail silently.

**Comment by wangrunji0408** [comment]
I see. Thanks!
