### ISSUE TITLE
reserve `0` for invalid variant in protobuf enums

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#4119]
Proto3 won't distinguish "enum is 0" and "enum field not set". Reserving `0` for the `INVALID` variant will be more friendly for debugging and version compatibility.

https://developers.google.com/protocol-buffers/docs/style#enums
> The zero value enum should have the suffix UNSPECIFIED.

**Comment by skyzh** [comment]
Note: we already have a layer to handle prost `Option` here:

https://github.com/singularity-data/risingwave/blob/6d3183927831ea9077499e01470e63f857337301/src/prost/helpers/src/generate.rs#L110-L112

May extend it to also handle the case for invalid enum variant.

**Comment by xiangjinwu** [comment]
Does this apply to `oneof` as well?
