### ISSUE TITLE
discussion(stream_pk): what should `DynamicFilter`'s distribution key be?

### ISSUE THREAD

**Issue by jon-chuang** [singularity-data/risingwave#4125]
If it can follow the upstream, we save a data shuffle.

If it is strictly the PK, we do not need to add anything to stream_pk.

If it is the comparison/join key, we do not get any benefit. This is the current behaviour so we should change it.

I think choosing the dist_key = PK is best. Any thoughts on this?

**Comment by fuyufjh** [comment]
> If it is strictly the PK, we do not need to add anything to stream_pk.

Didn't get it... If it is strictly the PK, what do we need to add into stream_pk?

**Comment by jon-chuang** [comment]
> Didn't get it... If it is not strictly the PK, what do we need to add into stream_pk?

For instance, if we use something other than PK, e.g. upstream key, then we will have to add that key to the stream_pk. So adds additional length to the key.

**Comment by fuyufjh** [comment]
After some discussion, we decided to use upstream's distribution key as DynamicFilter's distribution key.

**Comment by jon-chuang** [comment]
After offline discussion, we determined that its best for DynamicFilter's distribution to follow the upstream distribution. We should fix this in PR.

**Comment by fuyufjh** [comment]
> After offline discussion, we determined that its best for DynamicFilter's distribution to follow the upstream distribution. We should fix this in a PR.

Hi, @jon-chuang is this done yet?
