### ISSUE TITLE
rename (stream) `pk` to `stream_key`

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#4159]
Currently we use the word "PK" to describe the key of the output stream of this operator. 

https://github.com/singularity-data/risingwave/blob/c37c9c46baae1cfd2e007db963824bab70dfe3e3/src/frontend/src/optimizer/plan_node/plan_base.rs#L30-L31

However, this naming is too general and cause several times of misunderstanding, especially, confusing with the key of state. Thus, let's rename it as `stream_key` to reduce ambiguity.

Also mentioned in https://singularity-data.quip.com/3lUJAQMthect/RFC-Streamkey-instead-pk

**Comment by xiangjinwu** [comment]
dup with #3957 ?
