### ISSUE TITLE
Pass all columns from upstream chunk to agg states' `apply_batch`

### ISSUE THREAD

**Issue by richardchien** [singularity-data/risingwave#4185]
Since we have `args` and `order_pairs` which contains the upstream column indices in `risingwave_stream::executor::aggregation::agg_call::AggCall`, and `AggCall`s will be passed into `new` when creating `ManagedTableState` implementations, these agg states can store the upstream column indices in their struct. However, currently in `GlobalSimpleAggExecutor` and `HashAggExecutor`, we select several columns from upstream chunk then pass them to `agg_state.apply_batch`, this makes agg states hard to find interested columns according to saved indices. Agg states like `GenericExtremeState` now determine the input columns by hardcoded inference logic, when bugs appear, it's very hard to debug.

I propose that we just pass all the columns to `agg_state.apply_batch`, this will make agg states easy to write and debug. I've done this for newly added `ManagedStringAggState`, the code is much simpler.

**Comment by BowenXiao1999** [comment]
@st1page 's final vision also includes write state table in executor instead of AggState, so that AggState is unaware of `column_mapping`.

If this is the final version, what about move state table out from `apply_batch` and write it in executor first? Agree this but I'm not sure which is the best path.

**Comment by st1page** [comment]
> write state table in executor instead of AggState, so that AggState is unaware of column_mapping\

+1 for doing it first, which will actually reduce the workload of this issue.

**Comment by BowenXiao1999** [comment]
After some discuss with @st1page ,

My thoughts for column_mapping:

For max or min (table state), we need to update the `top_n` cache, which may still need to aware group key, stream pk, sort key.
And HashAgg needs to know group key or more keys to do partition of AggStates. So After we apply column_mapping, executor might still need to know group key, stream pk stuffs.

For sum or count (value state), column mapping can not help.

**Comment by st1page** [comment]
> After some discuss with @st1page ,
> 
> My thoughts for column_mapping:
> 
> For max or min (table state), we need to update the `top_n` cache, which may still need to aware group key, stream pk, sort key. And HashAgg needs to know group key or more keys to do partition of AggStates. So After we apply column_mapping, executor might still need to know group key, stream pk stuffs.
> 
> For sum or count (value state), column mapping can not help.

maybe not, let's wait for @richardchien's new design. I think he will give a more clear and more elegant solution.
