### ISSUE TITLE
playground: support multiple compute node and shared in-memory object store

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#4195]
So that people can test things out more easily.

**Comment by BugenZhao** [comment]
So how's deterministic e2e deployed now, with minio? Will it be replaced with in-memory object store?

**Comment by TennyZhuang** [comment]
> So how's deterministic e2e deployed now, with minio, or single node? Will it be replaced with in-memory object store?

I guess minio satisfies deterministic.

**Comment by TennyZhuang** [comment]
The only feature we depends is read-after-write.

We will never concurrent write an object, we even won’t write an object twice, so the result should be very determined, regardless of its internal implementation
