### ISSUE TITLE
SqlSmith: Bind error: column names window_start and window_end are not allowed in window table function's input.',

### ISSUE THREAD

**Issue by marvenlee2486** [singularity-data/risingwave#4215]
```
Panic on SQL:
SELECT INT '15' AS col_0, INT '67' - INT '29' AS col_1, (REAL '35.14174016837295' - (INT '61' / (SMALLINT '59' << t_5.col_3))) - SMALLINT '25' AS col_2 FROM m9 AS t_0, m9 AS t_1, nation AS t_2 JOIN part AS t_3 ON t_2.n_name = t_3.p_mfgr, m6 AS t_4, m6 AS t_5, tumble(m9, m9.col_0, INTERVAL '102196') AS tumble_6, part AS t_7, m8 AS t_8, orders AS t_9, m6 AS t_10, m6 AS t_13 WHERE t_1.col_0 <= t_10.col_0 GROUP BY t_9.o_orderstatus, t_7.p_retailprice, t_7.p_brand, t_13.col_3, t_7.p_partkey, t_5.col_0, t_4.col_0, t_7.p_name, t_7.p_comment, t_1.col_0, t_10.col_3, t_4.col_2, t_7.p_mfgr, t_5.col_3, t_9.o_custkey, t_13.col_2, t_9.o_comment, t_7.p_size, t_5.col_1, t_10.col_0, t_9.o_orderpriority HAVING true
Reason:
panicked at 'Failed to bind:
SELECT INT '15' AS col_0, INT '67' - INT '29' AS col_1, (REAL '35.14174016837295' - (INT '61' / (SMALLINT '59' << t_5.col_3))) - SMALLINT '25' AS col_2 FROM m9 AS t_0, m9 AS t_1, nation AS t_2 JOIN part AS t_3 ON t_2.n_name = t_3.p_mfgr, m6 AS t_4, m6 AS t_5, tumble(m9, m9.col_0, INTERVAL '102196') AS tumble_6, part AS t_7, m8 AS t_8, orders AS t_9, m6 AS t_10, m6 AS t_13 WHERE t_1.col_0 <= t_10.col_0 GROUP BY t_9.o_orderstatus, t_7.p_retailprice, t_7.p_brand, t_13.col_3, t_7.p_partkey, t_5.col_0, t_4.col_0, t_7.p_name, t_7.p_comment, t_1.col_0, t_10.col_3, t_4.col_2, t_7.p_mfgr, t_5.col_3, t_9.o_custkey, t_13.col_2, t_9.o_comment, t_7.p_size, t_5.col_1, t_10.col_0, t_9.o_orderpriority HAVING true
Reason:
Bind error: column names window_start and window_end are not allowed in window table function's input.', src/tests/sqlsmith/tests/test_runner.rs:109:41
test run_sqlsmith_on_frontend_6 ... FAILED
```

**Comment by marvenlee2486** [comment]
This happens when I try to enable subquery in FROM statement.

The implementation changes that cause this issue is when change the add relation to context to add to bound_coloumns and bound_relations only after all the FROM statement is defined, because they are parallel (or execute in the same level). 
Refer the bug 1 in issue  https://github.com/singularity-data/risingwave/issues/3935

Refer to the draft PR. https://github.com/singularity-data/risingwave/pull/4216

**Comment by marvenlee2486** [comment]
Panic on SQL:
SELECT t_6.p_type AS col_0, DATE '2022-07-21' AS col_1 FROM m4 AS t_0, m6 AS t_1, m7 AS t_2, m3 AS t_3, hop(m1, m1.col_0, INTERVAL '1', INTERVAL '370593') AS hop_4, m7 AS t_5, part AS t_6, partsupp AS t_7, nation AS t_8, customer AS t_9, (SELECT t_15.l_orderkey AS col_0 FROM part AS t_10, m4 AS t_11, m6 AS t_12, m7 AS t_13, part AS t_14, lineitem AS t_15, m3 AS t_16, supplier AS t_17, nation AS t_18, m7 AS t_19, m2 AS t_20, m6 AS t_21, m2 AS t_22, m3 AS t_23, m6 AS t_24, supplier AS t_25 GROUP BY t_14.p_partkey, t_19.col_1, t_17.s_acctbal, t_15.l_tax, t_13.col_2, t_15.l_quantity, t_12.col_0, t_10.p_type, t_17.s_name, t_14.p_name, t_17.s_comment, t_24.col_1, t_15.l_orderkey, t_25.s_address, t_16.col_0, t_11.col_1, t_14.p_retailprice, t_20.col_0, t_25.s_nationkey, t_15.l_partkey, t_10.p_container, t_15.l_shipmode, t_25.s_comment, t_17.s_phone, t_14.p_type, t_18.n_name, t_10.p_name, t_15.l_suppkey, t_15.l_commitdate, t_15.l_shipinstruct, t_15.l_returnflag, t_15.l_receiptdate, t_14.p_container, t_15.l_shipdate, t_15.l_comment, t_25.s_suppkey, t_10.p_size, t_12.col_1, t_15.l_linenumber) AS sq_26, m1 AS t_27, m4 AS t_28, customer AS t_29 WHERE false GROUP BY t_28.col_1, t_8.n_comment, t_1.col_0, t_6.p_partkey, t_8.n_nationkey, t_6.p_type HAVING false
Reason:
panicked at 'Failed to bind:
SELECT t_6.p_type AS col_0, DATE '2022-07-21' AS col_1 FROM m4 AS t_0, m6 AS t_1, m7 AS t_2, m3 AS t_3, hop(m1, m1.col_0, INTERVAL '1', INTERVAL '370593') AS hop_4, m7 AS t_5, part AS t_6, partsupp AS t_7, nation AS t_8, customer AS t_9, (SELECT t_15.l_orderkey AS col_0 FROM part AS t_10, m4 AS t_11, m6 AS t_12, m7 AS t_13, part AS t_14, lineitem AS t_15, m3 AS t_16, supplier AS t_17, nation AS t_18, m7 AS t_19, m2 AS t_20, m6 AS t_21, m2 AS t_22, m3 AS t_23, m6 AS t_24, supplier AS t_25 GROUP BY t_14.p_partkey, t_19.col_1, t_17.s_acctbal, t_15.l_tax, t_13.col_2, t_15.l_quantity, t_12.col_0, t_10.p_type, t_17.s_name, t_14.p_name, t_17.s_comment, t_24.col_1, t_15.l_orderkey, t_25.s_address, t_16.col_0, t_11.col_1, t_14.p_retailprice, t_20.col_0, t_25.s_nationkey, t_15.l_partkey, t_10.p_container, t_15.l_shipmode, t_25.s_comment, t_17.s_phone, t_14.p_type, t_18.n_name, t_10.p_name, t_15.l_suppkey, t_15.l_commitdate, t_15.l_shipinstruct, t_15.l_returnflag, t_15.l_receiptdate, t_14.p_container, t_15.l_shipdate, t_15.l_comment, t_25.s_suppkey, t_10.p_size, t_12.col_1, t_15.l_linenumber) AS sq_26, m1 AS t_27, m4 AS t_28, customer AS t_29 WHERE false GROUP BY t_28.col_1, t_8.n_comment, t_1.col_0, t_6.p_partkey, t_8.n_nationkey, t_6.p_type HAVING false
Reason:
Bind error: column names `window_start` and `window_end` are not allowed in window table function's input.', src/tests/sqlsmith/tests/test_runner.rs:109:41
test run_sqlsmith_on_frontend_2 ... FAILED

**Comment by marvenlee2486** [comment]
Panic on SQL:
CREATE MATERIALIZED VIEW m4 AS SELECT FLOAT '53.47903548938295' AS col_0, TIMESTAMP '2022-07-26 12:20:42' AS col_1 FROM hop(m3, m3.col_0, INTERVAL '1', INTERVAL '320709') AS hop_0 WHERE false
Reason:
panicked at 'Failed to handle SQL:
CREATE MATERIALIZED VIEW m4 AS SELECT FLOAT '53.47903548938295' AS col_0, TIMESTAMP '2022-07-26 12:20:42' AS col_1 FROM hop(m3, m3.col_0, INTERVAL '1', INTERVAL '320709') AS hop_0 WHERE false
Reason:
Bind error: column names `window_start` and `window_end` are not allowed in window table function's input.', src/tests/sqlsmith/tests/test_runner.rs:40:29
test run_sqlsmith_on_frontend_17 ... FAILED


This does not include any of the unstable generator - gen_agg and gen_subquery (possible with also)

**Comment by xiangjinwu** [comment]
FYI: #3189
I guess `m3` already contains columns `window_start` and `window_end`, so `hop(m3, ...)` is disallowed to produce two columns sharing the same name `window_start`.

In the tests, either give m3 columns aliases to avoid naming conflict, or avoid twtf-over-twtf completely.

**Comment by marvenlee2486** [comment]
I think it is my sqlsmith problem, I have solved it already under the PR dy. Sorry for that
