### ISSUE TITLE
bug sqlsmith: 'assertion failed: `(left == right)` , src/frontend/src/optimizer/plan_node/logical_expand.rs:156:13

### ISSUE THREAD

**Issue by marvenlee2486** [singularity-data/risingwave#4218]
WITH with_0 AS (WITH with_1 AS (SELECT TIMESTAMP '2022-07-26 22:16:07' AS col_0 FROM m4 AS t_2, m2 AS t_3, m2 AS t_6, m0 AS t_7, m6 AS t_8, m7 AS t_9, person AS t_10, m1 AS t_11, customer AS t_12, hop(bid, bid.date_time, INTERVAL '1', INTERVAL '167185') AS hop_13, m4 AS t_14, hop(m3, m3.col_1, INTERVAL '1', INTERVAL '208953') AS hop_15 GROUP BY t_10.id, t_12.c_custkey, t_14.col_3, hop_15.col_0, hop_13.auction, t_12.c_mktsegment, t_14.col_1, t_12.c_acctbal, t_9.col_0, hop_13.date_time, t_7.col_0, t_3.col_0, t_2.col_1, t_10.name, t_9.col_1, t_2.col_0, t_2.col_3, t_12.c_address, t_10.credit_card, hop_13.bidder, t_12.c_comment, t_14.col_2, t_12.c_name, hop_13.price, t_8.col_1, t_12.c_nationkey, t_12.c_phone) SELECT INTERVAL '200982' AS col_0, REAL '39.45580912111579' + avg(DISTINCT REAL '91.03378134824614') AS col_1, sum((((SMALLINT '61' | (SMALLINT '64' # INT '91')) - SMALLINT '5') + ((SMALLINT '27' << INT '77') * SMALLINT '43')) / FLOAT '77.58774593356736') AS col_2 FROM with_1, supplier AS t_16, m0 AS t_17, auction AS t_18, bid AS t_19, auction AS t_20, m5 AS t_21, auction AS t_22 JOIN part AS t_23 ON t_22.item_name = t_23.p_container, m4 AS t_24 GROUP BY t_18.description, t_16.s_acctbal, t_20.reserve, t_24.col_0, t_16.s_comment, t_18.reserve, t_16.s_name, t_17.col_0, t_20.date_time, t_18.expires, t_20.description, t_20.expires) SELECT DATE '2022-07-22' + (INT '7' + INT '16') AS col_0, DATE '2022-07-20' AS col_1 FROM with_0, supplier AS t_25, supplier AS t_26, nation AS t_27, m8 AS t_28, bid AS t_29, m2 AS t_30, supplier AS t_31, m0 AS t_32, region AS t_33, m7 AS t_34, orders AS t_37, m4 AS t_38 WHERE t_25.s_acctbal <> t_27.n_nationkey GROUP BY t_26.s_nationkey, t_27.n_nationkey, t_34.col_0, t_28.col_1, t_26.s_name, t_30.col_0, t_27.n_regionkey, t_37.o_orderkey, t_25.s_suppkey, t_26.s_comment, t_37.o_orderpriority, t_25.s_nationkey, t_38.col_2, t_27.n_name, t_33.r_regionkey, t_33.r_name, t_31.s_nationkey, t_31.s_name, t_34.col_2 ORDER BY t_34.col_0 DESC, t_38.col_2 DESC, t_26.s_name DESC, t_34.col_2 DESC LIMIT 10
Reason:
panicked at 'assertion failed: `(left == right)`
  left: `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14]`,
 right: `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]`', src/frontend/src/optimizer/plan_node/logical_expand.rs:156:13
test run_sqlsmith_on_frontend_16 ... FAILED

**Comment by marvenlee2486** [comment]
This occur when gen_agg is enable

**Comment by xiangjinwu** [comment]
cc @likg227

**Comment by xiangjinwu** [comment]
A shorter way to repro the same error:
```
create table t (v1 int, v2 int);
with z(a, b, c) as (select avg(distinct 1), v2, count(v1) from t group by v2) select a from z;
```
