### ISSUE TITLE
expr: implement `vnode` function

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#4247]
The function can only be generated in frontend instead of in user input. We can use this function in two-phase topN.

**Comment by fuyufjh** [comment]
How to pass total number of vnodes of this fragements? 

It seems more elegant to pass it within an expression context, which doesn't exist now.

**Comment by fuyufjh** [comment]
By the way, there is a `ROW(...)` function that accepts variable number of arguments, so this is not a problem now? Please take a look at it. cc. @st1page
