### ISSUE TITLE
Column missing in explain string if it doesn't have a name

### ISSUE THREAD

**Issue by richardchien** [singularity-data/risingwave#4283]
With #3798, we can't display column index number if the column has no name. Example:

```
dev=> explain verbose select sum(b) from (values('aaa',3),('bbb',2),('ccc',4),('ccc',2)) g(a,b);
                              QUERY PLAN
----------------------------------------------------------------------
 BatchSimpleAgg { aggs: [sum()] }
   BatchValues { rows: [[3:Int32], [2:Int32], [4:Int32], [2:Int32]] }
(2 rows)
```

---

Another problem is that, without the column index, we cannot easily check if a plan node is correctly using its upstream projection. In the following example, for the `BatchSimpleAgg` after `BatchProject`, we can't know it's aggregating expression `(t.b + 1:Int32)` or the output column of `BatchProject`.

```
dev=> create table t (a varchar, b int);
CREATE_TABLE
dev=> explain verbose select sum(b + 1) from t;
                               QUERY PLAN
-------------------------------------------------------------------------
 BatchSimpleAgg { aggs: [sum(sum((t.b + 1:Int32)))] }
   BatchExchange { order: [], dist: Single }
     BatchSimpleAgg { aggs: [sum((t.b + 1:Int32))] }
       BatchProject { exprs: [(t.b + 1:Int32)] }
         BatchScan { table: t, columns: [t.b], distribution: SomeShard }
(5 rows)
```

**Comment by richardchien** [comment]
cc @skyzh @chenzl25

**Comment by st1page** [comment]
> we can't know it's aggregating expression (t.b + 1:Int32) or the output column of BatchProject

I think we can know it by see where the expression first appears 

And for the first issue, I think we should add the field name in `LogicalValue`

**Comment by jon-chuang** [comment]
> I think we can know it by see where the expression first appears

I think it doesn't apply to all scenarios. For instance

LogicalAgg { agg: [sum(a+b)] }
Project { exprs: [a+b, a, b] }

**Comment by richardchien** [comment]
Hi all, I created a new issue #4455 to discuss the second problem, since the two problems are not quite related.

**Comment by jon-chuang** [comment]
Btw, this is how postgres handle anonymous column name from values:
```sql
postgres=# explain verbose select sum(b) from (values('aaa',3),('bbb',2),('ccc',4),('ccc',2)) g(a,b);
                            QUERY PLAN                             
-------------------------------------------------------------------
 Aggregate  (cost=0.06..0.07 rows=1 width=8)
   Output: sum("*VALUES*".column2)
   ->  Values Scan on "*VALUES*"  (cost=0.00..0.05 rows=4 width=4)
         Output: "*VALUES*".column1, "*VALUES*".column2
```
