### ISSUE TITLE
Sink: drop sink + drop table seems to result in infinite loop

### ISSUE THREAD

**Issue by nanderstabel** [singularity-data/risingwave#4302]
**Describe the bug**

**To Reproduce**
```
CREATE TABLE t (v1 int);
CREATE MATERIALIZED VIEW mv AS SELECT * FROM t;
CREATE SINK s FROM mv WITH (
    sink_type = 'mysql',
    endpoint = '127.0.0.1:3306',
    user = 'root',
    database = 'test',
    table = 't1'
);
DROP SINK s;
DROP MATERIALIZED VIEW mv;
DROP TABLE t; // <-- infinite loop here
```

**Expected behavior**
sink, materialized view and table should be dropped without infinite loop.

**Additional context**

**Comment by BugenZhao** [comment]
What do you mean by "infinite loop"? There should be no "loop" in the dropping code path. If the `drop sink` does not return in a reasonable time, I believe there's some wrong actor resolving in the barrier manager that can never be collected from.

**Comment by nanderstabel** [comment]
> What do you mean by "infinite loop"? There should be no "loop" in the dropping code path. If the `drop sink` does not return in a reasonable time, I believe there's some wrong actor resolving in the barrier manager that can never be collected from.

I was wrong the issue was not caused by an infinite loop.  Instead it was caused due to `Sink` being dropped in the catalog manager, but not in the stream manager (in `DdlServiceImpl::drop_sink()`. PR will follow shortly.
