### ISSUE TITLE
streaming: forbid or warn `order by` queries without `limit`

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#4309]
For example:

```sql
select * from tb1 order by id
```

The semantics of such kind of queries are not very clear, especially for the result MView should be distributed or singleton.

1. If the result MV is distributed, then a `select` query on it will get out-of-order result 
2. If the result MV is singleton, then the MaterializeExecutor must be bottleneck because all operators except it are distributed

It seems that the only feasible choice for us is 2, but I this may be not the expectation of users. So how about forbid/warn it?

**Comment by TennyZhuang** [comment]
I’d like to propose another solution.

1. Ignore order_by in subquery context.
2. For order_by on MV, remove it but store the order in catalog, and generate a Sort operator in batch query.

**Comment by fuyufjh** [comment]
```
For order_by on MV, remove it but store the order in catalog, and generate a Sort operator in batch query.
```

Are you sure to "remove it"? If so, the batch query would be very expensive.

An acceptable solution to me is to create distributed MV with order, and generate a MergeSort for batch query on that MV.

**Comment by TennyZhuang** [comment]
I prefer to treat a mview as a normal mview combined with a covered index.

In particular, we need to do the following things:

1. Create the mview without `order_by`.
2. Create an unnamed covered index over the mview.
3. Store an `order_by` flag on the meta store. (In the latter, we may refactor it as a logical view).

For the batch query over the mview:

1. We will automatically insert a `Sort` operator over the TableScan.
2. Then it may match some optimizer rule to make it an ordered scan.

For the streaming query over the mview:

1. We will use the mview without `order_by` directly.
