### ISSUE TITLE
avoid `let_underscore_lock` for tokio locks

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#4313]
There's a clippy rule named [`let_underscore_lock`](https://rust-lang.github.io/rust-clippy/master/#let_underscore_drop).

> **What it does**
Checks for `let _ = <expr>` where expr has a type that implements Drop
**Why is this bad?**
This statement immediately drops the initializer expression instead of extending its lifetime to the end of the scope, which is often not intended. To extend the expression’s lifetime to the end of the scope, use an underscore-prefixed name instead (i.e. `_var`). If you want to explicitly drop the expression, `std::mem::drop` conveys your intention better and is less error-prone.

It's only enabled on std and parking lot locks. So tokio locks are not checked.
https://github.com/rust-lang/rust-clippy/blob/a591e725a6f5c6097c30d91ec68c992310b7b1bc/clippy_lints/src/let_underscore.rs#L102-L109

For example, the `ddl_lock.read()` here does nothing since we are not binding it to an underscore-prefixed name.

https://github.com/singularity-data/risingwave/blob/a15b40a28e86db1bb4d5c9b35f7303249d8102fd/src/meta/src/rpc/service/ddl_service.rs#L279-L283

Besides, we should also avoid using `RwLock<()>` or `Mutex<()>`, which is orthometric to this issue.

**Comment by BugenZhao** [comment]
cc @KeXiangWang

**Comment by skyzh** [comment]
Oops, didn't realize this doesn't lock anything when reviewing 🥵

**Comment by skyzh** [comment]
Have you revisited all the places where we're using tokio locks?

**Comment by BugenZhao** [comment]
> Have you revisited all the places where we're using tokio locks?

Yep. Other occurrences give a suffix like `_xxx`. Actually, in most cases, the inner item is meaningful to us and we won't bind the guard to `_` or `_xxx`. 😄

**Comment by KeXiangWang** [comment]
Sorry for this bug😢. I've fixed the ddl_lock bug. Should we close this issue?

**Comment by BugenZhao** [comment]
> Sorry for this bug😢. I've fixed the ddl_lock bug. Should we close this issue?

I believe we can, since there seems to be no force check for this.

**Comment by xxchan** [comment]
Actually I think it should be `must_use` (but tokio doesn't have it) instead of `let_underscore_lock` 😄
