### ISSUE TITLE
sqlsmith bug hunt: parse negative numbers

### ISSUE THREAD

**Issue by kwannoel** [singularity-data/risingwave#4344]
**Describe the bug**

Parser should parse negative numbers as is, rather than into a unary_op `neg`, wrapping an inner value.
This is because that prevents certain valid numbers e.g. `-9223372036854775808` from being assigned the correct type.

**To Reproduce**

`rw`
```sh
dev=> select (-9223372036854775808) & (-9223372036854775808);
ERROR:  QueryError: Feature is not yet implemented: BitwiseAnd[Decimal, Decimal], Tracking issue: https://github.com/singularity-data/risingwave/issues/112.
dev=> select pg_typeof(-9223372036854775808);
 ?column? 
----------
 numeric
(1 row)

dev=> select pg_typeof(-9223372036854775807);
 ?column? 
----------
 bigint
(1 row)
```

This could be considered a bug in the parser, it parses `+/-` as unary op:
```
- input: SELECT -1.0
  formatted_sql: SELECT - 1.0 # notice the space between '-' and '1.0'
```

**Expected behavior**

`postgres`
```
postgres=# select (-9223372036854775808) & (-9223372036854775808);
       ?column?       
----------------------
 -9223372036854775808
(1 row)

postgres=# select -(9223372036854775808);      
 ?column?       
----------------------
 -9223372036854775808

postgres=# insert into t values (9223372036854775808);
INSERT 0 1

postgres=# select (-v)::bigint from t;                                                                               
         int8         
----------------------
 -9223372036854775808
(1 row)

postgres=# select -(9223372036854775807 + 1);
ERROR:  bigint out of range
```

**Additional context**

Apart from fixing simple negative expressions: `-1`,
it should also deal with complex expressions: `-(-(-1)) => -1`. Nested expressions are rare can be fixed separately.

This is to be consistent with postgres parser (output from [pglast](https://github.com/lelit/pglast)). Notice how it does not wrap the value in a unary op:
```sh
[nix-shell:~/projects/risingwave-nix]$ ./query_parser.py "select -(-(-(9223372036854775808)))"
{'@': 'SelectStmt',
 'all': False,
 'limitOption': {'#': 'LimitOption',
                 'name': 'LIMIT_OPTION_DEFAULT',
                 'value': 0},
 'op': {'#': 'SetOperation', 'name': 'SETOP_NONE', 'value': 0},
 'targetList': ({'@': 'ResTarget',
                 'location': 7,
                 'val': {'@': 'A_Const',
                         'location': 7,
                         'val': {'@': 'Float',
                                 'val': Decimal('-9223372036854775808')}}},)}
```

A possible workaround is to handle these in binder, similar to `rewrite_positive`.

**Comment by kwannoel** [comment]
Original generated query: https://gist.github.com/kwannoel/0411052cac745bd4b98e096bc90918fc

**Comment by BugenZhao** [comment]
Has the upstream sqlparser fix this in later commits? If not, it would be better if we also open an issue in the original repo.

**Comment by kwannoel** [comment]
> Has the upstream sqlparser fix this in later commits? If not, it would be better if we also open an issue in the original repo.

Seems like not:
```rs
fn main() {
    let sql = "SELECT -1;";
    let dialect = PostgreSqlDialect {};

    let ast = Parser::parse_sql(&dialect, sql).unwrap();

    println!("AST: {:#?}", ast);
}
```

`output`
```
AST: [
    Query(
        Query {
            with: None,
            body: Select(
                Select {
                    distinct: false,
                    top: None,
                    projection: [
                        UnnamedExpr(
                            UnaryOp {
                                op: Minus,
                                expr: Value(
                                    Number(
                                        "1",
                                        false,
                                    ),
                                ),
                            },
                        ),
                    ],
                    into: None,
                    from: [],
                    lateral_views: [],
                    selection: None,
                    group_by: [],
                    cluster_by: [],
                    distribute_by: [],
                    sort_by: [],
                    having: None,
                    qualify: None,
                },
            ),
            order_by: [],
            limit: None,
            offset: None,
            fetch: None,
            lock: None,
        },
    ),
]
```

**Comment by kwannoel** [comment]
Need to fix negative operator precedence too?:
```
dev=> SELECT -9223372036854775808::bigint;
ERROR:  QueryError: Invalid Parameter Value: Can't cast risingwave_common::types::decimal::Decimal to i64.
dev=> SELECT pg_typeof(-9223372036854775808);
 ?column? 
----------
 bigint
```

**Comment by skyzh** [comment]
> > Has the upstream sqlparser fix this in later commits? If not, it would be better if we also open an issue in the original repo.
> 
> Upstreamed: [sqlparser-rs/sqlparser-rs#549](https://github.com/sqlparser-rs/sqlparser-rs/issues/549)

IIRC we forked the sqlparser by ourselves. May fix it by ourselves https://github.com/singularity-data/risingwave/tree/main/src/sqlparser/src. A PR to upstream is also good!

**Comment by kwannoel** [comment]
Closing this issue. As of #4356 , parser is able to handle negative prefixed integers. e.g. `bigint::min`, `int::min`, etc...
For nested expressions, we currently do not follow the same behaviour as postgres, and it is fine because:
1. Expressions like -(-(-(9223372036854775808))) are rare.
2. Postgres evaluates the above to -9223372036854775808 `bigint`, but this behaviour is unintuitive.

See original comment by @xxchan : https://github.com/singularity-data/risingwave/pull/4729#discussion_r949952408
