### ISSUE TITLE
risedev: cannot start with `./risedev d`

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#4351]
cc @BugenZhao looks like a bug 🥵🥵🥵

**Comment by skyzh** [comment]
related: https://github.com/singularity-data/risingwave/pull/4332

**Comment by Li0k** [comment]
./risedev d use memory backend but not provide compactor, so it will be intercepted by the following logic

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/15023748/182159347-40c32cd4-da4b-4769-954a-4191679a016d.png">
