### ISSUE TITLE
Optimizer rule: try to pushdown function with one-sided dependency in equality join

### ISSUE THREAD

**Issue by jon-chuang** [singularity-data/risingwave#4360]
If an equality join takes the form of `f(a, b, c) = g(d, e, f)` where a,b,c belong to left table, and d,e,f belong to right table, we should pushdown f and g into projections before the join and then use the output of the function as the join key to the join.

See e.g. https://github.com/singularity-data/risingwave/pull/4349#discussion_r934522356 for example application

**Comment by st1page** [comment]
#4276

**Comment by jon-chuang** [comment]
Duplicate of: https://github.com/singularity-data/risingwave/issues/4360
