### ISSUE TITLE
assign internal table with more reasonable names

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#4366]
Currently there's no fragment id or operator id in the table names, so it might be hard for us to identify which table is what we want to query. 

Related: #2949 

```
#1002: person
#1004: auction
#1006: bid
#1007: nexmark_q8
#1008: __INTERNAL_nexmark_q8_HashJoinLeft_1008
#1009: __INTERNAL_nexmark_q8_HashJoinRight_1009
#1010: __INTERNAL_nexmark_q8_HashAgg_1010
#1011: __INTERNAL_nexmark_q8_HashAgg_1011
#1012: nexmark_q5
#1013: __INTERNAL_nexmark_q5_HashJoinLeft_1013
#1014: __INTERNAL_nexmark_q5_HashJoinRight_1014
#1015: __INTERNAL_nexmark_q5_HashAgg_1015
#1016: __INTERNAL_nexmark_q5_HashAgg_1016
#1017: __INTERNAL_nexmark_q5_HashAgg_1017
#1018: __INTERNAL_nexmark_q5_HashAgg_1018
#1019: __INTERNAL_nexmark_q5_HashAgg_1019
#1020: __INTERNAL_nexmark_q5_HashAgg_1020
```

**Comment by Li0k** [comment]
Tips:

1. the function of building internal_table names call `generate_intertable_name_with_type` in `src/common/src/catalog/internal_table.rs`

2. and it will be used in `src/meta/src/stream/stream_graph.rs` when `build_inner`, we can gather some info about `fragment_id` and `operator_id` when `build_inner` to make `generate_intertable_name_with_type` more reasonable
