### ISSUE TITLE
(refactor): cache physical execution plan

### ISSUE THREAD

**Issue by ZENOTME** [singularity-data/risingwave#4374]
Add plan cache for portal in extended query mode so that the execution of portal can directly use the plan rather than generating plan every time execute it.

Because different kinds of statement has different execution method. For now, I prioritize implementing for query statement first.

**Comment by liurenjie1024** [comment]
Can we postpone this first? This feature is quite error prone and has no much benefits. For example, when we do scale in/scale out, the distribution of mv may change, and the physical plan will change.

**Comment by ZENOTME** [comment]
Yes

**Comment by BowenXiao1999** [comment]
> Can we postpone this first? This feature is quite error prone and has no much benefits. For example, when we do scale in/scale out, the distribution of mv may change, and the physical plan will change.

Agreed. Postgresql is singleton so it is not so hard to do this as client-side cache. 

Also I think it will not be the must-require for e2e_test.
