### ISSUE TITLE
frontend panic when options parameter is empty

### ISSUE THREAD

**Issue by mikechesterwang** [singularity-data/risingwave#4387]
**Describe the bug**
If the options parameter is an empty string, then the frontend will receive the following config string in startupMessage:
*[] means \0 in byte*

```
case 1:
user[]root[]option[][]database[]dev[]application_name[]psql[]client_encoding[]UTF8
case 2:
user[]root[]database[]dev[]application_name[]psql[]client_encoding[]UTF8[]option
```

Situations like case 1 and case 2 appear randomly. If it is case 2. The number of segments is an odd number, which will make the following code in frontend panic:

src/utils/pgwire/src/pg_message.rs:61
```rust
        let config: Vec<&str> = config.split('\0').collect();
        
        config.chunks(2).for_each(|chunk| {
            map.insert(chunk[0].to_string(), chunk[1].to_string());
        });
```

Although clients like `psql` will omit `options` parameter if the connection string is like `psql "postgres://root:@localhost:4566/dev?options="`, malware can use this panic to make the RisingWave service not available. 

**To Reproduce**
Set options parameter in startupMessage to an empty string 

**Expected behavior**
Return an ErrResponse to the client

**Comment by BowenXiao1999** [comment]
This may relates to https://github.com/singularity-data/risingwave/pull/2751. 
cc @yezizp2012 @cnissnzg
