### ISSUE TITLE
bug: tumble does not take CTE as input

### ISSUE THREAD

**Issue by xiangjinwu** [singularity-data/risingwave#4389]
**Describe the bug**
The input of `tumble`/`hop` should allow CTE: #2733

**To Reproduce**
```
with t(ts) as (values ('2020-01-01 12:00:00'::timestamp)) select * from tumble(t, ts, interval '10' second) as z;
```

**Expected behavior**
```
         ts          |    window_start     |     window_end      
---------------------+---------------------+---------------------
 2020-01-01 12:00:00 | 2020-01-01 12:00:00 | 2020-01-01 12:00:10
(1 row)
```

**Additional context**
The prior PR only tests `hop` but not `tumble`: #3188

https://github.com/singularity-data/risingwave/blob/f05dcfd0efa4c5f24239984d2c6fe0c45a93b8fa/src/frontend/src/planner/relation.rs#L115-L119

The error message `the .` is not meaningful either.

**Comment by jon-chuang** [comment]
Strangely, the planner tests already tests for 

```sql
create table t1 (id int, v1 int, created_at date);
with t2 as (select * from t1 where v1 >= 10)
select * from tumble(t1, created_at, interval '3' day);
```

So I don't think the issue is arbitrary CTE. It may be the use of values in the CTE subquery...

**Comment by jon-chuang** [comment]
Oh wait, I see, this CTE is actually completely meaningless.
