### ISSUE TITLE
sqlsmith bug hunt: cannot recognize large numeric

### ISSUE THREAD

**Issue by kwannoel** [singularity-data/risingwave#4399]
**Describe the bug**

Large numeric is not recognized in RW: e.g. `f32::MAX: 340282350000000000000000000000000000000`.

**To Reproduce**

```sql
dev=> SELECT 340282350000000000000000000000000000000;
ERROR:  QueryError: Expr error: Cast("str", "risingwave_common::types::decimal::Decimal").
```

**Expected behavior**

```sql
postgres=# select 340282350000000000000000000000;
            ?column?            
--------------------------------
 340282350000000000000000000000
(1 row)

postgres=# select pg_typeof(340282350000000000000000000000);
 pg_typeof 
-----------
 numeric
(1 row)
```

**Additional context**

Can fix by indicating what is the max size of numeric we support. We may not strictly follow pg behaviour in this case. See #239 (currently using `rust-decimal` out of the 3).

**Comment by lmatz** [comment]
Probably due to the limitation of the current decimal crate we use #239

**Comment by neverchanje** [comment]
If it's a known issue then we can temporarily limit sqlsmith to only generate integers within the bound of int64.

**Comment by kwannoel** [comment]
Track in #239
