### ISSUE TITLE
binder: panics when joining 2 subqueries

### ISSUE THREAD

**Issue by xxchan** [singularity-data/risingwave#4418]
**To Reproduce**
```sql
dev=> select * from (select 1 as x) join (select 1 as x) using(x);

thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/frontend/src/binder/relation/join.rs:182:73
```

**Expected behavior**
In PG,
```sql
postgres=# select * from (select 1 as x) join (select 1 as x) using(x);
ERROR:  subquery in FROM must have an alias
LINE 1: select * from (select 1 as x) join (select 1 as x) using(x);
                      ^
HINT:  For example, FROM (SELECT ...) [AS] foo.
```

**Additional context**
Actually, In PG:
```sql
postgres=# select * from (select 1 as x);
ERROR:  subquery in FROM must have an alias
LINE 1: select * from (select 1 as x);
                      ^
```
But this is allowed in risingwave:
```sql
dev=> select * from (select 1 as x);
 x
---
 1
(1 row)
```

And join subquries with aliases is ok:
```sql
dev=> select * from (select 1 as x) t1 join (select 1 as x) t2 using(x);
 x
---
 1
(1 row)
```

So maybe we just need to follow PG to disable FROM subquery without alias.

**Comment by jon-chuang** [comment]
We also don't support subquery aliasing ATM, right?

**Comment by jon-chuang** [comment]
Note that the problematic code path, `get_table_name` will be removed in https://github.com/singularity-data/risingwave/pull/4401. This way, we'd always be able to reference the right subquery as a table in its own right, even without an alias (there will be an unamed alias that allows us to resolve any column names)

**Comment by jon-chuang** [comment]
So I'd say that for the moment, there is no strict necessity to enforce aliasing FROM subqueries.
