### ISSUE TITLE
feat: add CREATEUSER and NOCREATEUSER option for user create/alter

### ISSUE THREAD

**Issue by yezizp2012** [singularity-data/risingwave#4440]
`NOCREATEUSER` should be default option when not specified.
 And when create/alter user, the options should be subset of current user.

**Comment by yezizp2012** [comment]
Cc @CharlieSYH

**Comment by xiangjinwu** [comment]
Maybe a dumb question, but I cannot find `NOCREATEUSER` option in [PostgreSQL doc](https://www.postgresql.org/search/?u=%2Fdocs%2F14%2F&q=NOCREATEUSER).

**Comment by CharlieSYH** [comment]
> Maybe a dumb question, but I cannot find `NOCREATEUSER` option in [PostgreSQL doc](https://www.postgresql.org/search/?u=%2Fdocs%2F14%2F&q=NOCREATEUSER).

PG uses CREATEROLE/NOCREATEROLE:
https://www.postgresql.org/docs/current/sql-createrole.html
But we don't have "roles" in RIsingWave. I guess that's why we use CREATEUSER/NOCREATEUSER instead, right? @yezizp2012

**Comment by yezizp2012** [comment]
> Maybe a dumb question, but I cannot find `NOCREATEUSER` option in [PostgreSQL doc](https://www.postgresql.org/search/?u=%2Fdocs%2F14%2F&q=NOCREATEUSER).

In PostgreSQL, it's `NOCREATEROLE`. Since we don't have role concept yet, just use use instead for now.
