### ISSUE TITLE
better error message for `hop(t, col, INTERVAL '1', INTERVAL '0')`

### ISSUE THREAD

**Issue by kwannoel** [singularity-data/risingwave#4504]
**Describe the bug**

```
Reason:
db error: ERROR: ExecuteError: internal error: Invalid Parameter Value: Invalid parameter window: window_size 00:00:00 cannot be divided by window_slide 00:00:01.
', src/tests/sqlsmith/src/bin/main.rs:175:13
```

For those not familiar with semantics of `hop`, this error message is confusing, since it seems to state that `0` cannot be divided by `1`.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
1. State that window-size must be non-zero, otherwise we would be unable to `slide` the window forward.
2. ~~OR permit 0 divided by 1, if this is valid by semantics of `hop`.~~ Should prevent user from doing this.

**Additional context**

Related: https://github.com/singularity-data/risingwave/issues/3966

**Comment by xxchan** [comment]
> State that window-size must be non-zero

BTW, I think it should actually be *positive*? 🤔

```
dev=> select * from hop(t, x, INTERVAL '-1', INTERVAL '1');
ERROR:  QueryError: Invalid Parameter Value: Invalid parameter window: window_size 00:00:01 cannot be divided by window_slide 00:00:-1.
dev=> select * from hop(t, x, INTERVAL '1', INTERVAL '-1');
ERROR:  QueryError: Invalid Parameter Value: Invalid parameter window: window_size 00:00:-1 cannot be divided by window_slide 00:00:01.
dev=> select * from hop(t, x, INTERVAL '-1', INTERVAL '-1');
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?>
```
