### ISSUE TITLE
Introduce pprof-rs to risingwave

### ISSUE THREAD

**Issue by yuhao-su** [singularity-data/risingwave#4580]
**Is your feature request related to a problem? Please describe.**
Currently, we are profiling our system using Linux perf. It is inconvenient and even harder to do so in docker and when we have multiple node.

**Describe the solution you'd like**
[pprof-rs](https://github.com/tikv/pprof-rs) is a CPU profiler can be integrated into a rust program. We may try this in Risingwave.

There is another interesting project [pyroscope](https://pyroscope.io/docs/rust/ ) using pprof-rs as backend that can output the flamegraph to grafana. 

**Describe alternatives you've considered**
Alternatively, we may start our own process to perf the running process (by Linux perf) and form a report.

**Comment by fuyufjh** [comment]
It would be very nice if we can use `risedev ctl` to profile a node! (just like `risedev ctl stream trace`)

**Comment by yuhao-su** [comment]
Seems it's already down in #3824.

I'll try to make it available in risectl.
