### ISSUE TITLE
sql parser cannot parse consecutive right angle brackets when using nested structs

### ISSUE THREAD

**Issue by wzzzzd** [singularity-data/risingwave#4611]
**Describe the bug**
```
dev=> create table t (v1 struct<v1 varchar, v2 struct<v1 varchar, v2 int>>, v2 int);
ERROR:  QueryError: sql parser error: Expected ',' or ')' after column definition, found: v2.
```

But this is OK.
```
dev=> create table t (v1 struct<v1 varchar, v2 struct<v1 varchar, v2 int>>);
CREATE_TABLE
```

Also, if I insert a space into the angle brackets, the statement can be parsed correctly.
```
dev=> create table t (v1 struct<v1 varchar, v2 struct<v1 varchar, v2 int> >, v2 int);
CREATE_TABLE
```

Is this a feature or a bug? It reminds me of a C++ problem long ago that `vector<vector<int>>` must be written as `vector<vector<int> >`:joy:...

**To Reproduce**
As above.

**Expected behavior**
consecutive right angle brackets should be parsed correctly

**Comment by skyzh** [comment]
> Is this a feature or a bug? 

I believe this is a bug. But I guess if we want to support parse `>>`, it will take a lot of extra work in parser... Not sure how sqlparser is implemented for now. cc @ice1000 might have some ideas on this 🤣

**Comment by xxchan** [comment]
The problem is
https://github.com/singularity-data/risingwave/blob/c96fac4d4607e2832049c2c03c245eec39ec0ac6/src/sqlparser/src/tokenizer.rs#L549-L556

A solution can be: let lexer aware of `CREATE`, and do not generate `>>` in this case 🤔

ref https://www.stroustrup.com/C++11FAQ.html#brackets

**Comment by ice1000** [comment]
We can handle `>>` in parser: two consecutive `>` tokens with no space in-between is considered a `>>` ast node

**Comment by xxchan** [comment]
BTW I found we already *try to* parse it correctly. 

https://github.com/singularity-data/risingwave/blob/d1567a9649baee7148f5c050c9b063e86a1cd238/src/sqlparser/src/parser.rs#L116-L118

https://github.com/singularity-data/risingwave/blob/d1567a9649baee7148f5c050c9b063e86a1cd238/src/sqlparser/src/parser.rs#L2068-L2071

And the following SQL will succeed (the `struct` with `>>` is the last argument): 😄
```sql
create table t(v struct<v struct<v int>>);
```
