### ISSUE TITLE
DROP USER does not support double quotes

### ISSUE THREAD

**Issue by mikechesterwang** [singularity-data/risingwave#4623]
**Describe the bug**
By the convention, `-` should not appear in a name. However, we can create user with its name containing `-`. After we create the user, we cannot drop it.

So essentially the problem is:
1. cannot use double quote to escape keyword when using `DROP USER` statement.

**To Reproduce**
Problem 1
```bash
dev=> CREATE USER "n-m" WITH SUPERUSER CREATEDB PASSWORD '123';
CREATE_USER

dev=> DROP USER n-m;
ERROR:  QueryError: sql parser error: Expected end of statement, found: -.

dev=> DROP USER "n-m";
ERROR:  QueryError: Catalog error: user not found: "n-m".

dev=> DROP USER 'n-m';
ERROR:  QueryError: sql parser error: Expected identifier, found: 'n-m'.
dev=>

dev=> CREATE USER "mike;DROP" WITH SUPERUSER CREATEDB PASSWORD '123';
CREATE_USER
```

**Expected behavior**
Support double quotes

**Additional context**
/

**Comment by yezizp2012** [comment]
@cnissnzg please help to take a look, and check **alter user** as well.
