### ISSUE TITLE
feat(storage): use FixedLengthFilterKeyExtractor  as much as possible

### ISSUE THREAD

**Issue by Li0k** [singularity-data/risingwave#4640]
**Is your feature request related to a problem? Please describe.**
For now , we handle the table_catalog notification with `from_table` . Everytime receive a `table_catalog` , we try to parse it and build a `SchemaFilterKeyExtractor`.

```rust
impl FilterKeyExtractorImpl {
    pub fn from_table(table_catalog: &Table) -> Self {
        let dist_key_indices: Vec<usize> = table_catalog
            .distribution_key
            .iter()
            .map(|dist_index| *dist_index as usize)
            .collect();

        let pk_indices: Vec<usize> = table_catalog
            .order_key
            .iter()
            .map(|col_order| col_order.index as usize)
            .collect();

        let match_read_pattern =
            !dist_key_indices.is_empty() && pk_indices.starts_with(&dist_key_indices);
        if !match_read_pattern {
            // for now frontend had not infer the table_id_to_filter_key_extractor, so we
            // use FullKeyFilterKeyExtractor
            FilterKeyExtractorImpl::FullKey(FullKeyFilterKeyExtractor::default())
        } else {
            FilterKeyExtractorImpl::Schema(SchemaFilterKeyExtractor::new(table_catalog))
        }
    }
}

```

the `extract` function of `SchemaFilterKeyExtractor` will call `deserialize_prefix_len_with_column_indices` , to get `prefix` of `input` with deserialize. IMO, the dist_key builded by fixed_type like `Int64`, `Int32` in the most scenarious. Therefore, we have no need to calculate a fixed_type every time

**Describe the solution you'd like**
For those disk_key that only contains fixed_type, we can bulild the `FixedLengthFilterKeyExtractor` instead of `SchemaFilterKeyExtractor` to reduce claculation cost.

It means that we can check the data_type in dist_key to determine whether to use  `FixedLengthFilterKeyExtractor` (if the data_type of all column are fixed_type)

**Additional context**
- https://github.com/singularity-data/risingwave/pull/4394
- https://github.com/singularity-data/risingwave/pull/4530

**Comment by xxhZs** [comment]
We use `1` for `null` in the key, This means that we also need to deserialize to know if it is `null,` even if the data type is fixed for all columns.
