### ISSUE TITLE
primary key support for source

### ISSUE THREAD

**Issue by tabVersion** [singularity-data/risingwave#4696]
**Is your feature request related to a problem? Please describe.**

```sql
dev=> create materialized source s ( id integer primary key , first_name varchar , last_name varchar , email varchar ) with (connector = 'kafka', kafka.topic = 'dbserver1.inventory.customers', kafka.brokers = '127.0.0.1:29092' ) row format debezium_json;
ERROR:  QueryError: Feature is not yet implemented: column constraints "PRIMARY KEY", No tracking issue yet.
```
and CDC source is broken because of lacking the feature (#4694) 

in this way, it works but `primary key` info is still not passed to the downstream. 

```sql
dev=> create materialized source s ( id integer , first_name varchar , last_name varchar , email varchar , PRIMARY KEY ( id ) ) with (connector = 'kafka', kafka.topic = 'dbserver1.inventory.customers', kafka.brokers = '127.0.0.1:29092' ) row format debezium_json;
CREATE_SOURCE
```

the scene does not require impl pk constraint but pass the info to the downstream 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Related: #4256

**Comment by fuyufjh** [comment]
Please also help add some tests for Debezium source in e2e test

**Comment by tabVersion** [comment]
> Please also help add some tests for Debezium source in e2e test

Will do in the next pr
