### ISSUE TITLE
block cache data cache metrics abnormal

### ISSUE THREAD

**Issue by MrCroxx** [singularity-data/risingwave#4706]
**Describe the bug**

During benchmarking with tpc-h and nexmark, the block cache data cache metrics rate is abnormally low (even zero). But data cache is actually accessed, we can check it by printing log in `get`. I guess some local metrics is not collected or reported.

<img width="929" alt="image" src="https://user-images.githubusercontent.com/22407295/185098140-95d489f7-0fa1-4c23-a18c-d8a65fd0558e.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/22407295/185098329-dc05abc1-c9a9-47dc-840d-468cb1f9ea87.png">

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

**Comment by Li0k** [comment]
i found the reason， with PR (#2709) , we use `collect_local_statistic` function to get the `LocalStats` from `iterator`. But it miss impletement for HummockIteratorUnion. Therefore, the `iterator` wrapper by HummockIteratorUnion can not report anymore

<img width="711" alt="image" src="https://user-images.githubusercontent.com/15023748/185116469-ad6ca069-3bcc-4a80-9559-c66c3bfdee4e.png">


PR link:  https://github.com/singularity-data/risingwave/commit/c45c2f9b11e00e0b5ac2f670edd52ee875ca9275

**Comment by MrCroxx** [comment]
> i found the reason， with PR (#2709) , we use `collect_local_statistic` function to get the `LocalStats` from `iterator`. But it miss impletement for HummockIteratorUnion. Therefore, the `iterator` wrapper by HummockIteratorUnion can not report anymore
> 
> code path: `risingwave/src/storage/src/hummock/iterator/mod.rs`
> 
> <img alt="image" width="711" src="https://user-images.githubusercontent.com/15023748/185116469-ad6ca069-3bcc-4a80-9559-c66c3bfdee4e.png">
> 
> PR link: [c45c2f9](https://github.com/singularity-data/risingwave/commit/c45c2f9b11e00e0b5ac2f670edd52ee875ca9275)

Thanks! I added a bool field to find which stats is not reported, but I found merge iterators in `SsstableIterator`, which does not implemented `HummockIterator`.

**Comment by MrCroxx** [comment]
@Li0k Yep, you are right. After fixing bug in `SstableIterator`, bug in `HummockIteratorUnion` also raised. 🤣

I'll fix it tomorrow and see if there is more bugs. Besides, I think we should refactor the design to avoid it.
