### ISSUE TITLE
Feature request: Improve debug symbol display when profiling

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#4764]
**Is your feature request related to a problem? Please describe.**

Async Rust is compiled into FSM futures and the original function name was lost, which makes it very hard to identify functions when profiling RisingWave.

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/10192522/185657257-96f11da9-7421-4a8d-9ead-4c6fc67ab54c.png">

As you can see from the screenshot, all functions are named like `<futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next` instead of its name in source code.

**Describe the solution you'd like**

Need discussion.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by wangrunji0408** [comment]
How can I reproduce a flamegraph like this?

**Comment by xxchan** [comment]
> How can I reproduce a flamegraph like this?

`risedev ctl profile`

**Comment by StrikeW** [comment]
This [tool](https://github.com/koute/not-perf.git) can produce a detailed flamegraph including inline functions. But I didn't know how it works. 

```
nperf record -p `pidof compute-node` -o perf.data
nperf flamegraph perf.data > perf.svg
```

![topn-old-flame](https://user-images.githubusercontent.com/7338536/185782495-3bd79c0e-f004-4804-af97-65fc678c8075.svg)

**Comment by fuyufjh** [comment]
> How can I reproduce a flamegraph like this?

I used [flamegraph-rs](https://github.com/flamegraph-rs/flamegraph).

`risedev ctl profile` has some issues on Linux #4765

**Comment by fuyufjh** [comment]
> This [tool](https://github.com/koute/not-perf.git) can produce a detailed flamegraph including inline functions. But I didn't know how it works.
> 
> ```
> nperf record -p `pidof compute-node` -o perf.data
> nperf flamegraph perf.data > perf.svg
> ```

I just read this flamegraph carefully (requested a original copy from @StrikeW) and found an interesting fact: the original async fn was built into a closure inside of it. For example:

```rust
impl TopNExecutorWrapper {
  async fn top_n_executor_execute(mut self: Box<Self>) { ... }
}
```

was compiled into

```
inline risingwave_stream::executor::top_n_executor::TopNExecutorWrapper<E>::top_n_executor_execute::{{closure}}
```

in the flame graph.

This looks reasonable and acceptable to me. So let's close the issue now.
