### ISSUE TITLE
array/struct with empty string deserialized as NULL

### ISSUE THREAD

**Issue by xxchan** [singularity-data/risingwave#4768]
Here makes array/struct with empty string deserialized as NULL

_Originally posted by @name1e5s in https://github.com/singularity-data/risingwave/pull/2679#discussion_r950718133_

**Comment by xxchan** [comment]
```sql
create table t(x varchar[]);
insert into t values(ARRAY['1','','2']);
select * from t;
     x
------------
 {1,NULL,2}
(1 row)
```

**Comment by wzzzzd** [comment]
same with https://github.com/singularity-data/risingwave/issues/4521
