### ISSUE TITLE
CI: Include sqlsmith tests into PR workflow

### ISSUE THREAD

**Issue by kwannoel** [singularity-data/risingwave#4803]
Include fuzzing tests to PR Workflow to avoid fuzzing regressions. 
1. Fuzzing regressions also block changes to CI scripts, if they are triggers for running sqlsmith.
2. We can adjust workload accordingly to ensure it runs reasonably fast 1-2 min.
3. Our cron job runs daily, so we have to look through a day's worth of commits whenever a regression is caught by sqlsmith.
    That takes a while to find error source. It is faster to fix if we find the regression at the commit itself, or near to it.

Previously, I excluded it from PR workflow due to the following reasons:
1. Runs slow. 
    Even with PR workflow however, 
    we can resolve it by just lowering workload when needed. Coverage is still high from fuzzing since we run / pr.
    Edit: Another suggestion by @xxchan - run in separate workflow to speed things up.
5. It is non-deterministic, if random tests fail, it might not be due to the current PR.
    Maybe it just didn't run the failing test on a previous commit which caused the failure.
    However this should not block the PR. If the error occurs randomly, we can just rerun CI **if the PR's changes are clearly not the cause of the error**.
    Separately, we can look into this error, since we capture logs as well as stderr of failing queries.
    We can use these to reproduce the failure and debug from there.

**Comment by kwannoel** [comment]
cc @neverchanje , @marvenlee2486 .

**Comment by fuyufjh** [comment]
I think it should be run in a daily or nightly build CI instead of every PR.

Generally, we expect it to find out some 'unknown' bugs, so we should run it for a long enough time. While CI per PR is responsible to check the PR itself, I don't think it's a good place for sqlsmith test.
