### ISSUE TITLE
Use a separate table id for each source executor

### ISSUE THREAD

**Issue by shanicky** [singularity-data/risingwave#4817]
**Describe the bug**
Currently we use `table_id` and `split_id` to distinguish the internal state of each source executor, which is usually fine, but in the case of a source joining itself, it will lead to a key conflict in the state, and the temporary solution is to avoid it by adding `fragment_id`, but this is not a long-term plan, so we need to create a separate internal table id for each source executor

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

**Comment by shanicky** [comment]
cc @st1page

**Comment by fuyufjh** [comment]
If I understand correctly, even in different streaming jobs aka. `create materialised view`, the table_id will also be conflicted?

**Comment by yezizp2012** [comment]
> If I understand correctly, even in different streaming jobs aka. `create materialised view`, the table_id will also be conflicted?

Unfortunately yes.

**Comment by BugenZhao** [comment]
> > If I understand correctly, even in different streaming jobs aka. `create materialised view`, the table_id will also be conflicted?
> 
> Unfortunately yes, but will only have inconsistency after recovery. Cus they're keep using memory cache and persisting the state only.

I'm curious why we don't find write conflict in this case. 🤔

**Comment by tabVersion** [comment]
I will do a quick fix by adding fragment_id to split_ids. This can help isolate different fragments. 
Later we can switch to internal_table_id and can solve this elegantly.

**Comment by st1page** [comment]
> I'm curious why we don't find write conflict in this case.
- state store can not check the double write
- source executor has a local in-memory cache of its state(offset), so until a failover happens, it will not read from state store

**Comment by fuyufjh** [comment]
Any updates?

**Comment by tabVersion** [comment]
> Any updates?

discuss with @yezizp2012 , will use internal table id for each fragment and the prefix in state store will be different among the fragments. May pr tomorrow
