### ISSUE TITLE
planner test not showing panic or assertion failed message during testing

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#4858]
When running `./risedev do-apply-planner-test`, it tells me
```
ERROR: apply-planner-test panicked! Try run-planner-test to find which test case panicked.
/var/folders/h3/ky82klmd2ygfr58ppqm4js6m0000gn/T/fsio_VwYOVdxDH1/fsio/tzF36haIo0.sh: line 3: 17926 Abort trap: 6           cargo run --bin planner-test-apply
```

Then check `./risedev run-planner-test`: it just failed, not panicked.

```
Error: Expected batch_plan:
BatchUpdate { table: t1, exprs: [$0, $1, $2, 3:Int32::Int64] }
  BatchExchange { order: [], dist: Single }
    BatchLookupJoin { type: Inner, predicate: idx2.t1._row_id = t1._row_id, output: [t1._row_id, t1.a, t1.b, t1.c] }
      BatchScan { table: idx2, columns: [idx2.t1._row_id], scan_ranges: [idx2.b = Decimal(Normalized(2)), idx2.a = Int32(1)], distribution: SomeShard }

Actual batch_plan:
BatchUpdate { table: t1, exprs: [$0, $1, 3:Int32::Int64, $3] }
  BatchExchange { order: [], dist: Single }
    BatchLookupJoin { type: Inner, predicate: idx2.t1._row_id = t1._row_id, output: [t1.a, t1.b, t1.c, t1._row_id] }
      BatchScan { table: idx2, columns: [idx2.t1._row_id], scan_ranges: [idx2.b = Decimal(Normalized(2)), idx2.a = Int32(1)], distribution: SomeShard }


------------
     Summary [   0.241s] 12/33 tests run: 5 passed, 7 failed, 0 skipped
        FAIL [   0.205s] risingwave_frontend_test_runner::plan_test_runner agg_test
        FAIL [   0.059s] risingwave_frontend_test_runner::plan_test_runner array_test
        FAIL [   0.136s] risingwave_frontend_test_runner::plan_test_runner basic_query_test
        FAIL [   0.088s] risingwave_frontend_test_runner::plan_test_runner column_pruning_test
        FAIL [   0.083s] risingwave_frontend_test_runner::plan_test_runner common_table_expressions_test
        FAIL [   0.200s] risingwave_frontend_test_runner::plan_test_runner distribution_derive_test
        FAIL [   0.181s] risingwave_frontend_test_runner::plan_test_runner index_selection_test
```

> https://github.com/singularity-data/risingwave/issues/4858#issuecomment-1225491924
> Oops. There is actually an assertion failure, investigated by attaching the debugger. However, there seems to be no log for this, neither `panic` nor `assertion failed`. 😢

On [1006d47fc68e2f2406e22db3c0698ab598ed5cc1](https://github.com/singularity-data/risingwave/pull/4852/commits/1006d47fc68e2f2406e22db3c0698ab598ed5cc1)

cc @kwannoel @xxchan @skyzh

**Comment by xxchan** [comment]
Maybe other tests panicked?

**Comment by BugenZhao** [comment]
> Maybe other tests panicked?

Oops. There is actually an assertion failure, investigated by attaching the debugger. However, there seems to be no log for this, neither `panic` nor `assertion failed`. 😢

**Comment by xxchan** [comment]
Feel strange. Where is the assertion?

**Comment by BugenZhao** [comment]
> Feel strange. Where is the assertion? It seems it escaped from `catch_unwind` 😨

I think adding an intentional panic somewhere on the handler path can reproduce this. 🤔

**Comment by xxchan** [comment]
BTW, a minor improvement is to print the panic info here. 🤪 At least it can print one panic info. 

<img width="587" alt="image" src="https://user-images.githubusercontent.com/37948597/186413542-195f0d23-4ed5-482f-b3f6-b90710e5886c.png">

Why test runner failed to catch panic needs some investigation.

**Comment by kwannoel** [comment]
For `./risedev run-planner-test`, it will fail fast, if a certain number of test cases fail to match what is expected.
As such, *it will fail before even reaching the panicking testcase*.
To avoid this, solution is to do this:
```
./risedev run-planner-test --no-fail-fast
```

You can use this with the commit (https://github.com/singularity-data/risingwave/pull/4852/commits/1006d47fc68e2f2406e22db3c0698ab598ed5cc1) to see that panic occurs if we run all tests.
```
./risedev run-planner-test --no-fail-fast 2>&1 | rg panic -A 5 -B 5 -p
```

For `./risedev do-apply-planner-test`, even if tests doesn't match expected, it continues execution, since it just applies the diff.
So it will only fail on panics.

Hence difference in behaviour is expected.
